---
ID: "efd9b87c-a7fb-460d-89c5-3a43077b76a2"
Parent: "ba3a6fc8-f669-46e9-8a24-0789dac704b7"
Template: "ba3a6fc8-f669-46e9-8a24-0789dac704b7"
Path: "/sitecore/templates/Project/starter-collection/Pages/News/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{BA3A6FC8-F669-46E9-8A24-0789DAC704B7}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "039ca0bf-61c7-41e1-afcd-0bdb84e4ded7"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}"></d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "113d4926-f44c-4854-8265-96687c4030bd"
      Hint: SitemapPriority
      Value: 0.6
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260904T192150Z
    - ID: "2c76b5b6-739a-4b7e-b1be-692cfc24d8d8"
      Hint: TwitterCard
      Value: summary_large_image
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "699f7b97-f91b-406c-81ba-16fd6a24bad4"
      Hint: ChangeFrequency
      Value: monthly
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ca2ac87d-07c2-4236-8562-2d3e18420890"
    - ID: "acb9748b-ffe5-433d-8404-65a52adf82c3"
      Hint: OgType
      Value: article
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260904T192151Z
    - ID: "fabc61b3-0ca1-4f7d-8af7-a74a7a1c52f2"
      Hint: IncludeInSitemap
      Value: 1
