---
ID: "81bd4a3f-9c32-4126-8170-e4af68e2d325"
Parent: "3c2d1bf7-fb8e-4a50-b597-4ce25f2df873"
Template: "3c2d1bf7-fb8e-4a50-b597-4ce25f2df873"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/ui/Presentation Parameters/recipe-spec Parameters/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "eaef39b8-3263-41b7-b987-1acd0c6e440e"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T222010Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5801fbea-83ed-4030-af77-e4f432a024d9"
      Hint: ColorScheme
      Value: "{6AB8EC05-6217-4470-A67C-46F1770D0F89}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcc60eec-32d4-4aa3-90bf-3ed67ffd333b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T222010Z
    - ID: "f2987910-b565-4291-b9ae-a2f6bfc05390"
      Hint: PaddingY
      Value: "{295A5038-66A8-4D33-BDDF-B7CDA0AD0B71}"
