---
ID: "22f90aec-45bf-438a-85f8-87c75994e906"
Parent: "0e426177-af70-4f66-ac4f-f1918630b1a7"
Template: "0e426177-af70-4f66-ac4f-f1918630b1a7"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/Component Folders/media-wall Data Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{2E8740F2-22EF-4BA0-A307-D2A1DE267AD6}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1a622903-123d-4e5c-a547-273e2c6b50aa"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T015452Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e5ef1140-00ad-4e4e-bb16-5ad31052cae9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T015452Z
