---
ID: "38432319-e4b0-4a71-8552-a8e660746870"
Parent: "db6f7dae-1127-497a-b5c3-57813f2b7fdb"
Template: "db6f7dae-1127-497a-b5c3-57813f2b7fdb"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/layout/Presentation Parameters/scroll-scene Parameters/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a516a343-15b1-4cbc-83db-cec76cf26f02"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "020ce171-7a56-4647-bb79-2363671155a4"
      Hint: StickyBackground
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T020448Z
    - ID: "4e1ca2f0-a920-4327-814f-daf20306f31b"
      Hint: BackgroundScrim
      Value: "{A08DA44E-01A3-424D-ADBE-9339B24B69F0}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8a418275-3849-4246-be18-3a09310ff4bd"
      Hint: BackgroundPosition
      Value: "{337A3A3A-0BEE-4148-90D3-9ADB0955BEF2}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac9e5c55-a0c3-4d75-8fea-b8462d3dbcc6"
    - ID: "b4730174-1712-4970-a5b0-445388b0c74a"
      Hint: TransitionMs
      Value: 600
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T020448Z
    - ID: "e454b29e-21e4-46b1-8d34-7a546a5c5a54"
      Hint: ColorStops
      Value: neutral,primary,accent
