---
ID: "0a68d36d-6550-45e1-ae37-38782c1385e3"
Parent: "03d65600-0287-4ca4-b34b-fa9bcc30ccf6"
Template: "03d65600-0287-4ca4-b34b-fa9bcc30ccf6"
Path: "/sitecore/templates/Project/starter-collection/prospera/Content Models/matrix-column-icon/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{FF63BE90-6E90-48F5-8172-91104EF62D6F}"
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "matrix-column-icon@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "fffcca92-c96e-4a87-bbf2-38839aeb09a8"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T015251Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0c5bfe51-7f59-450f-b087-6d1a8def7a85"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T015251Z
    - ID: "ef8a22a4-e1ad-40e9-8013-311699eed94b"
      Hint: Heading
      Value: Included
