---
ID: "4555b256-cb98-4579-b74b-80972c325533"
Parent: "2e7de4db-9677-4c2f-a338-9207d2318d10"
Template: "2e7de4db-9677-4c2f-a338-9207d2318d10"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/destination-card/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8ccfd143-3112-4b4b-8167-9723595faf0c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T014232Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a29551c8-1318-4778-90cb-e03e93108443"
    - ID: "9cd34f93-208a-422a-be59-dfc359172362"
      Hint: Title
      Value: Bali, Indonesia
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T014233Z
