---
ID: "48263f89-7971-416c-a7a2-5af9c85b7090"
Parent: "c05f14ed-5493-43e1-8128-c9e9f1e8ad5b"
Template: "c05f14ed-5493-43e1-8128-c9e9f1e8ad5b"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/forms/Presentation Parameters/form-fieldset Parameters/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "form-fieldset@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "b1a64e6b-29da-41b4-85b7-b58548bd01d6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260916T021230Z
    - ID: 4ffda9c0-fdf3-48e0-b3fd-7c9d1a7648ab
      Hint: Gap
      Value: "{404B14BD-C15A-4DD1-98DF-E03E723C86BC}"
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "f5b8be50-761a-4a99-adea-8d3d99d79fb4"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260916T021230Z
    - ID: db207a7c-884a-4a2a-b5ea-f804a1c4ad6d
      Hint: Variant
      Value: "{C450F252-D2C7-4C5D-9BC1-B0094D1C6BA7}"
DB: master
