---
ID: "1c1f70c8-6dca-47f8-9ded-61e4312629ca"
Parent: "00ef0592-8051-4b28-9a85-0838bb8d5041"
Template: "00ef0592-8051-4b28-9a85-0838bb8d5041"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/cards-and-lists/Component Folders/media-carousel Data Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4B78580C-6303-4805-855F-399F6CBB56D6}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "03e86805-08be-4f07-bbe9-2834eb4ac34b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T220952Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7183631d-ab01-433f-8b63-aa9ba21958ae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T220952Z
