"use client";

// SLICER SOURCE — NOT IMPORTED AT RUNTIME.
//
// This file is the input to `scripts/registry/slice-library-icon.ts`.
// The slicer's TS-AST traversal expects this exact top-level shape
// (statically imported icon libraries, `iconSets` / `iconSetsSolid`
// object literals, `FALLBACK_SET` const, helper wrappers) so it can
// extract a per-set slice for each downstream variant under
// `library-icon-variants/<set>/library-icon.tsx`.
//
// Because every icon library is imported statically here, this file
// would balloon the showcase bundle if it were on the runtime path.
// It is NOT — the runtime entry is `library-icon.tsx`, which loads
// lucide statically and dynamically imports the five non-default sets
// from `library-icon-sets/<set>.tsx`. Keep the structure here in sync
// with the per-set modules; if a new icon name is added below, add it
// to the matching per-set module too.

import {
  faArchive,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowsRotate,
  faArrowsUpDown,
  faArrowUp,
  faBagShopping,
  faBars,
  faBell,
  faBolt,
  faBookmark,
  faBox,
  faCalendar,
  faCalendarDays,
  faCamera,
  faChartBar,
  faChartLine,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCircleQuestion,
  faClipboard,
  faClock,
  faCloud,
  faCreditCard,
  faDownload,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFile,
  faFilter,
  faFlag,
  faFolder,
  faGear,
  faGift,
  faGlobe,
  faGrip,
  faHeart,
  faHouse,
  faImage,
  faKey,
  faLink,
  faList,
  faLocationDot,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMap,
  faMinus,
  faMoon,
  faPause,
  faPenToSquare,
  faPhone,
  faPlay,
  faPlus,
  faRocket,
  faSave,
  faShare,
  faShield,
  faShoppingCart,
  faStar,
  faStop,
  faSun,
  faTag,
  faThumbsDown,
  faThumbsUp,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUser,
  faUserMinus,
  faUserPlus,
  faUsers,
  faVideo,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  FontAwesomeIcon,
  type FontAwesomeIconProps,
} from "@fortawesome/react-fontawesome";
import {
  PresentationChartLineIcon as HeroActivity,
  ExclamationCircleIcon as HeroAlert,
  ArchiveBoxIcon as HeroArchive,
  ArrowDownIcon as HeroArrowDown,
  ArrowLeftIcon as HeroArrowLeft,
  ArrowRightIcon as HeroArrowRight,
  ArrowUpIcon as HeroArrowUp,
  BellIcon as HeroBell,
  BookmarkIcon as HeroBookmark,
  CalendarIcon as HeroCalendar,
  CalendarDaysIcon as HeroCalendarDays,
  CameraIcon as HeroCamera,
  ChartBarIcon as HeroChartBar,
  ChartPieIcon as HeroChartPie,
  CheckIcon as HeroCheck,
  ChevronDownIcon as HeroChevronDown,
  ChevronLeftIcon as HeroChevronLeft,
  ChevronRightIcon as HeroChevronRight,
  ChevronUpDownIcon as HeroChevronsUpDown,
  ChevronUpIcon as HeroChevronUp,
  ClipboardDocumentIcon as HeroClipboard,
  ClockIcon as HeroClock,
  CloudIcon as HeroCloud,
  CreditCardIcon as HeroCreditCard,
  DocumentTextIcon as HeroDocumentText,
  ArrowDownTrayIcon as HeroDownload,
  PencilSquareIcon as HeroEdit,
  EyeIcon as HeroEye,
  EyeSlashIcon as HeroEyeOff,
  DocumentIcon as HeroFile,
  FunnelIcon as HeroFilter,
  FlagIcon as HeroFlag,
  FolderIcon as HeroFolder,
  GiftIcon as HeroGift,
  GlobeAltIcon as HeroGlobe,
  Squares2X2Icon as HeroGrid,
  HeartIcon as HeroHeart,
  QuestionMarkCircleIcon as HeroHelp,
  HomeIcon as HeroHome,
  PhotoIcon as HeroImage,
  InformationCircleIcon as HeroInfo,
  KeyIcon as HeroKey,
  BoltIcon as HeroLightning,
  LinkIcon as HeroLink,
  ListBulletIcon as HeroList,
  LockClosedIcon as HeroLock,
  EnvelopeIcon as HeroMail,
  MapIcon as HeroMap,
  MapPinIcon as HeroMapPin,
  Bars3Icon as HeroMenu,
  MinusIcon as HeroMinus,
  MoonIcon as HeroMoon,
  CubeIcon as HeroPackage,
  PauseIcon as HeroPause,
  PhoneIcon as HeroPhone,
  PlayIcon as HeroPlay,
  PlusIcon as HeroPlus,
  ArrowPathIcon as HeroRefresh,
  RocketLaunchIcon as HeroRocket,
  MagnifyingGlassIcon as HeroSearch,
  Cog6ToothIcon as HeroSettings,
  ShareIcon as HeroShare,
  ShieldCheckIcon as HeroShield,
  ShoppingBagIcon as HeroShoppingBag,
  ShoppingCartIcon as HeroShoppingCart,
  StarIcon as HeroStar,
  StopIcon as HeroStop,
  SunIcon as HeroSun,
  TagIcon as HeroTag,
  HandThumbDownIcon as HeroThumbsDown,
  HandThumbUpIcon as HeroThumbsUp,
  TrashIcon as HeroTrash,
  LockOpenIcon as HeroUnlock,
  ArrowUpTrayIcon as HeroUpload,
  UserIcon as HeroUser,
  UserMinusIcon as HeroUserMinus,
  UserPlusIcon as HeroUserPlus,
  UsersIcon as HeroUsers,
  VideoCameraIcon as HeroVideo,
  ExclamationTriangleIcon as HeroWarning,
  XMarkIcon as HeroX,
} from "@heroicons/react/24/outline";
import {
  PresentationChartLineIcon as HeroSolidActivity,
  ExclamationCircleIcon as HeroSolidAlert,
  ArchiveBoxIcon as HeroSolidArchive,
  ArrowDownIcon as HeroSolidArrowDown,
  ArrowLeftIcon as HeroSolidArrowLeft,
  ArrowRightIcon as HeroSolidArrowRight,
  ArrowUpIcon as HeroSolidArrowUp,
  BellIcon as HeroSolidBell,
  BookmarkIcon as HeroSolidBookmark,
  CalendarIcon as HeroSolidCalendar,
  CalendarDaysIcon as HeroSolidCalendarDays,
  CameraIcon as HeroSolidCamera,
  ChartBarIcon as HeroSolidChartBar,
  ChartPieIcon as HeroSolidChartPie,
  CheckIcon as HeroSolidCheck,
  ChevronDownIcon as HeroSolidChevronDown,
  ChevronLeftIcon as HeroSolidChevronLeft,
  ChevronRightIcon as HeroSolidChevronRight,
  ChevronUpDownIcon as HeroSolidChevronsUpDown,
  ChevronUpIcon as HeroSolidChevronUp,
  ClipboardDocumentIcon as HeroSolidClipboard,
  ClockIcon as HeroSolidClock,
  CloudIcon as HeroSolidCloud,
  CreditCardIcon as HeroSolidCreditCard,
  DocumentTextIcon as HeroSolidDocumentText,
  ArrowDownTrayIcon as HeroSolidDownload,
  PencilSquareIcon as HeroSolidEdit,
  EyeIcon as HeroSolidEye,
  EyeSlashIcon as HeroSolidEyeOff,
  DocumentIcon as HeroSolidFile,
  FunnelIcon as HeroSolidFilter,
  FlagIcon as HeroSolidFlag,
  FolderIcon as HeroSolidFolder,
  GiftIcon as HeroSolidGift,
  GlobeAltIcon as HeroSolidGlobe,
  Squares2X2Icon as HeroSolidGrid,
  HeartIcon as HeroSolidHeart,
  QuestionMarkCircleIcon as HeroSolidHelp,
  HomeIcon as HeroSolidHome,
  PhotoIcon as HeroSolidImage,
  InformationCircleIcon as HeroSolidInfo,
  KeyIcon as HeroSolidKey,
  BoltIcon as HeroSolidLightning,
  LinkIcon as HeroSolidLink,
  ListBulletIcon as HeroSolidList,
  LockClosedIcon as HeroSolidLock,
  EnvelopeIcon as HeroSolidMail,
  MapIcon as HeroSolidMap,
  MapPinIcon as HeroSolidMapPin,
  Bars3Icon as HeroSolidMenu,
  MinusIcon as HeroSolidMinus,
  MoonIcon as HeroSolidMoon,
  CubeIcon as HeroSolidPackage,
  PauseIcon as HeroSolidPause,
  PhoneIcon as HeroSolidPhone,
  PlayIcon as HeroSolidPlay,
  PlusIcon as HeroSolidPlus,
  ArrowPathIcon as HeroSolidRefresh,
  RocketLaunchIcon as HeroSolidRocket,
  MagnifyingGlassIcon as HeroSolidSearch,
  Cog6ToothIcon as HeroSolidSettings,
  ShareIcon as HeroSolidShare,
  ShieldCheckIcon as HeroSolidShield,
  ShoppingBagIcon as HeroSolidShoppingBag,
  ShoppingCartIcon as HeroSolidShoppingCart,
  StarIcon as HeroSolidStar,
  StopIcon as HeroSolidStop,
  SunIcon as HeroSolidSun,
  TagIcon as HeroSolidTag,
  HandThumbDownIcon as HeroSolidThumbsDown,
  HandThumbUpIcon as HeroSolidThumbsUp,
  TrashIcon as HeroSolidTrash,
  LockOpenIcon as HeroSolidUnlock,
  ArrowUpTrayIcon as HeroSolidUpload,
  UserIcon as HeroSolidUser,
  UserMinusIcon as HeroSolidUserMinus,
  UserPlusIcon as HeroSolidUserPlus,
  UsersIcon as HeroSolidUsers,
  VideoCameraIcon as HeroSolidVideo,
  ExclamationTriangleIcon as HeroSolidWarning,
  XMarkIcon as HeroSolidX,
} from "@heroicons/react/24/solid";
import {
  ShowChart as MuiActivity,
  Error as MuiAlert,
  Archive as MuiArchive,
  ArrowDownward as MuiArrowDown,
  ArrowBack as MuiArrowLeft,
  ArrowForward as MuiArrowRight,
  ArrowUpward as MuiArrowUp,
  Notifications as MuiBell,
  Bookmark as MuiBookmark,
  Event as MuiCalendar,
  CalendarMonth as MuiCalendarDays,
  PhotoCamera as MuiCamera,
  BarChart as MuiChartBar,
  PieChart as MuiChartPie,
  Check as MuiCheck,
  ExpandMore as MuiChevronDown,
  ChevronLeft as MuiChevronLeft,
  ChevronRight as MuiChevronRight,
  UnfoldMore as MuiChevronsUpDown,
  ExpandLess as MuiChevronUp,
  ContentPaste as MuiClipboard,
  AccessTime as MuiClock,
  Cloud as MuiCloud,
  CreditCard as MuiCreditCard,
  FileDownload as MuiDownload,
  Edit as MuiEdit,
  Visibility as MuiEye,
  VisibilityOff as MuiEyeOff,
  Description as MuiFile,
  FilterList as MuiFilter,
  Flag as MuiFlag,
  Folder as MuiFolder,
  CardGiftcard as MuiGift,
  Public as MuiGlobe,
  GridView as MuiGrid,
  Favorite as MuiHeart,
  Help as MuiHelp,
  Home as MuiHome,
  Image as MuiImage,
  Info as MuiInfo,
  Key as MuiKey,
  Bolt as MuiLightning,
  Link as MuiLink,
  List as MuiList,
  Lock as MuiLock,
  Email as MuiMail,
  Map as MuiMap,
  Place as MuiMapPin,
  Menu as MuiMenu,
  Remove as MuiMinus,
  DarkMode as MuiMoon,
  Inventory2 as MuiPackage,
  Pause as MuiPause,
  Phone as MuiPhone,
  PlayArrow as MuiPlay,
  Add as MuiPlus,
  Refresh as MuiRefresh,
  RocketLaunch as MuiRocket,
  Save as MuiSave,
  Search as MuiSearch,
  Settings as MuiSettings,
  Share as MuiShare,
  Shield as MuiShield,
  ShoppingBag as MuiShoppingBag,
  ShoppingCart as MuiShoppingCart,
  Star as MuiStar,
  Stop as MuiStop,
  LightMode as MuiSun,
  LocalOffer as MuiTag,
  ThumbDown as MuiThumbsDown,
  ThumbUp as MuiThumbsUp,
  Delete as MuiTrash,
  LockOpen as MuiUnlock,
  FileUpload as MuiUpload,
  Person as MuiUser,
  PersonRemove as MuiUserMinus,
  PersonAdd as MuiUserPlus,
  People as MuiUsers,
  Videocam as MuiVideo,
  WarningAmber as MuiWarning,
  Close as MuiX,
} from "@mui/icons-material";
import {
  Pulse as PhosphorActivity,
  WarningCircle as PhosphorAlert,
  Archive as PhosphorArchive,
  ArrowDown as PhosphorArrowDown,
  ArrowLeft as PhosphorArrowLeft,
  ArrowRight as PhosphorArrowRight,
  ArrowUp as PhosphorArrowUp,
  Bell as PhosphorBell,
  BookmarkSimple as PhosphorBookmark,
  Calendar as PhosphorCalendar,
  CalendarDots as PhosphorCalendarDays,
  Camera as PhosphorCamera,
  ChartBar as PhosphorChartBar,
  ChartPie as PhosphorChartPie,
  Check as PhosphorCheck,
  CaretDown as PhosphorChevronDown,
  CaretLeft as PhosphorChevronLeft,
  CaretRight as PhosphorChevronRight,
  CaretUpDown as PhosphorChevronsUpDown,
  CaretUp as PhosphorChevronUp,
  ClipboardText as PhosphorClipboard,
  Clock as PhosphorClock,
  Cloud as PhosphorCloud,
  CreditCard as PhosphorCreditCard,
  Download as PhosphorDownload,
  PencilSimple as PhosphorEdit,
  Eye as PhosphorEye,
  EyeSlash as PhosphorEyeOff,
  File as PhosphorFile,
  Funnel as PhosphorFilter,
  Flag as PhosphorFlag,
  Folder as PhosphorFolder,
  Gift as PhosphorGift,
  Globe as PhosphorGlobe,
  SquaresFour as PhosphorGrid,
  Heart as PhosphorHeart,
  Question as PhosphorHelp,
  House as PhosphorHome,
  Image as PhosphorImage,
  Info as PhosphorInfo,
  Key as PhosphorKey,
  Lightning as PhosphorLightning,
  Link as PhosphorLink,
  List as PhosphorList,
  Lock as PhosphorLock,
  Envelope as PhosphorMail,
  MapTrifold as PhosphorMap,
  MapPin as PhosphorMapPin,
  Minus as PhosphorMinus,
  Moon as PhosphorMoon,
  Package as PhosphorPackage,
  Pause as PhosphorPause,
  Phone as PhosphorPhone,
  Play as PhosphorPlay,
  Plus as PhosphorPlus,
  ArrowClockwise as PhosphorRefresh,
  RocketLaunch as PhosphorRocket,
  FloppyDisk as PhosphorSave,
  MagnifyingGlass as PhosphorSearch,
  Gear as PhosphorSettings,
  Share as PhosphorShare,
  ShieldCheck as PhosphorShield,
  ShoppingBag as PhosphorShoppingBag,
  ShoppingCart as PhosphorShoppingCart,
  Star as PhosphorStar,
  Stop as PhosphorStop,
  Sun as PhosphorSun,
  Tag as PhosphorTag,
  ThumbsDown as PhosphorThumbsDown,
  ThumbsUp as PhosphorThumbsUp,
  Trash as PhosphorTrash,
  LockOpen as PhosphorUnlock,
  Upload as PhosphorUpload,
  User as PhosphorUser,
  UserMinus as PhosphorUserMinus,
  UserPlus as PhosphorUserPlus,
  Users as PhosphorUsers,
  VideoCamera as PhosphorVideo,
  Warning as PhosphorWarning,
  X as PhosphorX,
} from "@phosphor-icons/react";
import {
  IconActivity as TablerActivity,
  IconAlertCircle as TablerAlert,
  IconArchive as TablerArchive,
  IconArrowDown as TablerArrowDown,
  IconArrowLeft as TablerArrowLeft,
  IconArrowRight as TablerArrowRight,
  IconArrowUp as TablerArrowUp,
  IconBell as TablerBell,
  IconBookmark as TablerBookmark,
  IconCalendar as TablerCalendar,
  IconCamera as TablerCamera,
  IconChartBar as TablerChartBar,
  IconChartPie as TablerChartPie,
  IconCheck as TablerCheck,
  IconChevronDown as TablerChevronDown,
  IconChevronLeft as TablerChevronLeft,
  IconChevronRight as TablerChevronRight,
  IconCaretUpDown as TablerChevronsUpDown,
  IconChevronUp as TablerChevronUp,
  IconClipboard as TablerClipboard,
  IconClock as TablerClock,
  IconCloud as TablerCloud,
  IconCreditCard as TablerCreditCard,
  IconDownload as TablerDownload,
  IconEdit as TablerEdit,
  IconEye as TablerEye,
  IconEyeOff as TablerEyeOff,
  IconFile as TablerFile,
  IconFilter as TablerFilter,
  IconFlag as TablerFlag,
  IconFolder as TablerFolder,
  IconGift as TablerGift,
  IconGlobe as TablerGlobe,
  IconLayoutGrid as TablerGrid,
  IconHeart as TablerHeart,
  IconHelpCircle as TablerHelp,
  IconHome as TablerHome,
  IconPhoto as TablerImage,
  IconInfoCircle as TablerInfo,
  IconKey as TablerKey,
  IconLink as TablerLink,
  IconList as TablerList,
  IconLock as TablerLock,
  IconMail as TablerMail,
  IconMap as TablerMap,
  IconMapPin as TablerMapPin,
  IconMenu2 as TablerMenu,
  IconMinus as TablerMinus,
  IconMoon as TablerMoon,
  IconPackage as TablerPackage,
  IconPlayerPause as TablerPause,
  IconPhone as TablerPhone,
  IconPlayerPlay as TablerPlay,
  IconPlus as TablerPlus,
  IconRefresh as TablerRefresh,
  IconRocket as TablerRocket,
  IconDeviceFloppy as TablerSave,
  IconSearch as TablerSearch,
  IconSettings as TablerSettings,
  IconShare as TablerShare,
  IconShieldCheck as TablerShield,
  IconShoppingBag as TablerShoppingBag,
  IconShoppingCart as TablerShoppingCart,
  IconStar as TablerStar,
  IconPlayerStop as TablerStop,
  IconSun as TablerSun,
  IconTag as TablerTag,
  IconThumbDown as TablerThumbsDown,
  IconThumbUp as TablerThumbsUp,
  IconTrash as TablerTrash,
  IconLockOpen as TablerUnlock,
  IconUpload as TablerUpload,
  IconUser as TablerUser,
  IconUserMinus as TablerUserMinus,
  IconUserPlus as TablerUserPlus,
  IconUsers as TablerUsers,
  IconVideo as TablerVideo,
  IconAlertTriangle as TablerWarning,
  IconX as TablerX,
} from "@tabler/icons-react";
import {
  Activity as LucideActivity,
  AlertCircle as LucideAlert,
  Archive as LucideArchive,
  ArrowDown as LucideArrowDown,
  ArrowLeft as LucideArrowLeft,
  ArrowRight as LucideArrowRight,
  ArrowUp as LucideArrowUp,
  Bed as LucideBed,
  Bell as LucideBell,
  Bookmark as LucideBookmark,
  Bot as LucideBot,
  Calendar as LucideCalendar,
  CalendarDays as LucideCalendarDays,
  Camera as LucideCamera,
  BarChart3 as LucideChartBar,
  PieChart as LucideChartPie,
  Check as LucideCheck,
  ChevronDown as LucideChevronDown,
  ChevronLeft as LucideChevronLeft,
  ChevronRight as LucideChevronRight,
  ChevronsUpDown as LucideChevronsUpDown,
  ChevronUp as LucideChevronUp,
  Circle as LucideCircle,
  Clipboard as LucideClipboard,
  Clock as LucideClock,
  Cloud as LucideCloud,
  CreditCard as LucideCreditCard,
  Download as LucideDownload,
  Edit as LucideEdit,
  Ellipsis as LucideEllipsis,
  Eye as LucideEye,
  EyeOff as LucideEyeOff,
  File as LucideFile,
  Filter as LucideFilter,
  Flag as LucideFlag,
  Folder as LucideFolder,
  Gift as LucideGift,
  Globe as LucideGithub,
  Globe as LucideGlobe,
  Grid2X2 as LucideGrid,
  Heart as LucideHeart,
  HelpCircle as LucideHelp,
  Home as LucideHome,
  Image as LucideImage,
  Info as LucideInfo,
  Key as LucideKey,
  Laptop as LucideLaptop,
  Zap as LucideLightning,
  Link as LucideLink,
  List as LucideList,
  Loader2 as LucideLoader,
  Lock as LucideLock,
  Mail as LucideMail,
  Map as LucideMap,
  MapPin as LucideMapPin,
  Menu as LucideMenu,
  Minus as LucideMinus,
  Monitor as LucideMonitor,
  Moon as LucideMoon,
  Navigation as LucideNavigation,
  Package as LucidePackage,
  PanelLeft as LucidePanelLeft,
  PanelRight as LucidePanelRight,
  Pause as LucidePause,
  Phone as LucidePhone,
  Plane as LucidePlane,
  Play as LucidePlay,
  Plus as LucidePlus,
  RefreshCw as LucideRefresh,
  Rocket as LucideRocket,
  Save as LucideSave,
  Search as LucideSearch,
  Settings as LucideSettings,
  Share2 as LucideShare,
  ShieldCheck as LucideShield,
  ShoppingBag as LucideShoppingBag,
  ShoppingCart as LucideShoppingCart,
  Smartphone as LucideSmartphone,
  Star as LucideStar,
  StopCircle as LucideStop,
  Sun as LucideSun,
  Tablet as LucideTablet,
  Tag as LucideTag,
  Thermometer as LucideThermometer,
  ThumbsDown as LucideThumbsDown,
  ThumbsUp as LucideThumbsUp,
  Trash as LucideTrash,
  Unlock as LucideUnlock,
  Upload as LucideUpload,
  User as LucideUser,
  UserMinus as LucideUserMinus,
  UserPlus as LucideUserPlus,
  Users as LucideUsers,
  Video as LucideVideo,
  AlertTriangle as LucideWarning,
  X as LucideX,
} from "lucide-react";
import * as React from "react";

type IconSetId =
  | "lucide"
  | "heroicons"
  | "tabler"
  | "phosphor"
  | "mui"
  | "fontawesome";
type IconStyle = "outline" | "solid";

type LibraryIconComponent = React.ComponentType<{
  className?: string;
  style?: React.CSSProperties;
  title?: string;
  "aria-label"?: string;
  "aria-hidden"?: React.AriaAttributes["aria-hidden"];
  "aria-busy"?: boolean;
}>;

const fontAwesome = (
  icon: Parameters<typeof FontAwesomeIcon>[0]["icon"],
): LibraryIconComponent => {
  const FontAwesomeWrappedIcon: LibraryIconComponent = ({ style, ...rest }) => (
    <FontAwesomeIcon
      icon={icon}
      {...(rest as Omit<FontAwesomeIconProps, "icon" | "ref">)}
      style={style as FontAwesomeIconProps["style"]}
    />
  );
  FontAwesomeWrappedIcon.displayName = "FontAwesomeWrappedIcon";
  return FontAwesomeWrappedIcon;
};

const phosphorIcon = (
  IconComponent: React.ComponentType<
    { weight?: "regular" | "fill" } & Record<string, unknown>
  >,
  weight: "regular" | "fill",
): LibraryIconComponent => {
  const PhosphorWrappedIcon: LibraryIconComponent = (props) => (
    <IconComponent weight={weight} {...props} />
  );
  PhosphorWrappedIcon.displayName = "PhosphorWrappedIcon";
  return PhosphorWrappedIcon;
};

// Constant the slicer rewrites per variant. Determines which set the
// component falls back to when the active set has no entry for an icon.
const FALLBACK_SET: IconSetId = "lucide";

const iconSets: Partial<
  Record<IconSetId, Record<string, LibraryIconComponent>>
> = {
  lucide: {
    activity: LucideActivity,
    x: LucideX,
    alert: LucideAlert,
    "arrow-left": LucideArrowLeft,
    "arrow-right": LucideArrowRight,
    "arrow-up": LucideArrowUp,
    "arrow-down": LucideArrowDown,
    bookmark: LucideBookmark,
    "calendar-days": LucideCalendarDays,
    camera: LucideCamera,
    "chart-bar": LucideChartBar,
    "chart-pie": LucideChartPie,
    "chevron-left": LucideChevronLeft,
    "chevron-right": LucideChevronRight,
    "chevron-up": LucideChevronUp,
    "chevron-down": LucideChevronDown,
    "chevrons-up-down": LucideChevronsUpDown,
    clipboard: LucideClipboard,
    cloud: LucideCloud,
    home: LucideHome,
    "credit-card": LucideCreditCard,
    search: LucideSearch,
    user: LucideUser,
    users: LucideUsers,
    "user-plus": LucideUserPlus,
    "user-minus": LucideUserMinus,
    settings: LucideSettings,
    bell: LucideBell,
    mail: LucideMail,
    calendar: LucideCalendar,
    clock: LucideClock,
    check: LucideCheck,
    plus: LucidePlus,
    minus: LucideMinus,
    menu: LucideMenu,
    map: LucideMap,
    "panel-left": LucidePanelLeft,
    "panel-right": LucidePanelRight,
    info: LucideInfo,
    help: LucideHelp,
    warning: LucideWarning,
    star: LucideStar,
    heart: LucideHeart,
    lock: LucideLock,
    unlock: LucideUnlock,
    eye: LucideEye,
    "eye-off": LucideEyeOff,
    trash: LucideTrash,
    edit: LucideEdit,
    ellipsis: LucideEllipsis,
    download: LucideDownload,
    upload: LucideUpload,
    share: LucideShare,
    link: LucideLink,
    filter: LucideFilter,
    folder: LucideFolder,
    file: LucideFile,
    image: LucideImage,
    archive: LucideArchive,
    circle: LucideCircle,
    loader: LucideLoader,
    globe: LucideGlobe,
    github: LucideGithub,
    bed: LucideBed,
    bot: LucideBot,
    flag: LucideFlag,
    gift: LucideGift,
    grid: LucideGrid,
    key: LucideKey,
    laptop: LucideLaptop,
    lightning: LucideLightning,
    list: LucideList,
    monitor: LucideMonitor,
    moon: LucideMoon,
    navigation: LucideNavigation,
    "map-pin": LucideMapPin,
    package: LucidePackage,
    pause: LucidePause,
    play: LucidePlay,
    refresh: LucideRefresh,
    rocket: LucideRocket,
    save: LucideSave,
    shield: LucideShield,
    "shopping-bag": LucideShoppingBag,
    smartphone: LucideSmartphone,
    thermometer: LucideThermometer,
    "shopping-cart": LucideShoppingCart,
    phone: LucidePhone,
    plane: LucidePlane,
    stop: LucideStop,
    sun: LucideSun,
    tablet: LucideTablet,
    tag: LucideTag,
    "thumbs-down": LucideThumbsDown,
    "thumbs-up": LucideThumbsUp,
    video: LucideVideo,
  },
  heroicons: {
    activity: HeroActivity,
    x: HeroX,
    "arrow-left": HeroArrowLeft,
    "arrow-right": HeroArrowRight,
    "arrow-up": HeroArrowUp,
    "arrow-down": HeroArrowDown,
    bookmark: HeroBookmark,
    "calendar-days": HeroCalendarDays,
    camera: HeroCamera,
    "chart-bar": HeroChartBar,
    "chart-pie": HeroChartPie,
    "chevron-left": HeroChevronLeft,
    "chevron-right": HeroChevronRight,
    "chevron-up": HeroChevronUp,
    "chevron-down": HeroChevronDown,
    "chevrons-up-down": HeroChevronsUpDown,
    clipboard: HeroClipboard,
    cloud: HeroCloud,
    home: HeroHome,
    "credit-card": HeroCreditCard,
    search: HeroSearch,
    user: HeroUser,
    users: HeroUsers,
    "user-plus": HeroUserPlus,
    "user-minus": HeroUserMinus,
    settings: HeroSettings,
    bell: HeroBell,
    mail: HeroMail,
    calendar: HeroCalendar,
    clock: HeroClock,
    check: HeroCheck,
    plus: HeroPlus,
    minus: HeroMinus,
    menu: HeroMenu,
    map: HeroMap,
    info: HeroInfo,
    help: HeroHelp,
    alert: HeroAlert,
    warning: HeroWarning,
    star: HeroStar,
    heart: HeroHeart,
    lock: HeroLock,
    unlock: HeroUnlock,
    eye: HeroEye,
    "eye-off": HeroEyeOff,
    trash: HeroTrash,
    edit: HeroEdit,
    download: HeroDownload,
    upload: HeroUpload,
    share: HeroShare,
    link: HeroLink,
    filter: HeroFilter,
    folder: HeroFolder,
    file: HeroFile,
    flag: HeroFlag,
    gift: HeroGift,
    globe: HeroGlobe,
    grid: HeroGrid,
    image: HeroImage,
    archive: HeroArchive,
    key: HeroKey,
    list: HeroList,
    moon: HeroMoon,
    "map-pin": HeroMapPin,
    package: HeroPackage,
    pause: HeroPause,
    phone: HeroPhone,
    play: HeroPlay,
    refresh: HeroRefresh,
    rocket: HeroRocket,
    save: HeroDocumentText,
    shield: HeroShield,
    "shopping-cart": HeroShoppingCart,
    "shopping-bag": HeroShoppingBag,
    stop: HeroStop,
    sun: HeroSun,
    tag: HeroTag,
    "thumbs-down": HeroThumbsDown,
    "thumbs-up": HeroThumbsUp,
    lightning: HeroLightning,
    video: HeroVideo,
  },
  tabler: {
    activity: TablerActivity,
    x: TablerX,
    "arrow-left": TablerArrowLeft,
    "arrow-right": TablerArrowRight,
    "arrow-up": TablerArrowUp,
    "arrow-down": TablerArrowDown,
    bookmark: TablerBookmark,
    "calendar-days": TablerCalendar,
    camera: TablerCamera,
    "chart-bar": TablerChartBar,
    "chart-pie": TablerChartPie,
    "chevron-left": TablerChevronLeft,
    "chevron-right": TablerChevronRight,
    "chevron-up": TablerChevronUp,
    "chevron-down": TablerChevronDown,
    "chevrons-up-down": TablerChevronsUpDown,
    clipboard: TablerClipboard,
    cloud: TablerCloud,
    home: TablerHome,
    "credit-card": TablerCreditCard,
    search: TablerSearch,
    user: TablerUser,
    users: TablerUsers,
    "user-plus": TablerUserPlus,
    "user-minus": TablerUserMinus,
    settings: TablerSettings,
    bell: TablerBell,
    mail: TablerMail,
    calendar: TablerCalendar,
    clock: TablerClock,
    check: TablerCheck,
    plus: TablerPlus,
    minus: TablerMinus,
    menu: TablerMenu,
    map: TablerMap,
    info: TablerInfo,
    help: TablerHelp,
    alert: TablerAlert,
    warning: TablerWarning,
    star: TablerStar,
    heart: TablerHeart,
    lock: TablerLock,
    unlock: TablerUnlock,
    eye: TablerEye,
    "eye-off": TablerEyeOff,
    trash: TablerTrash,
    edit: TablerEdit,
    download: TablerDownload,
    upload: TablerUpload,
    share: TablerShare,
    link: TablerLink,
    filter: TablerFilter,
    folder: TablerFolder,
    file: TablerFile,
    flag: TablerFlag,
    gift: TablerGift,
    globe: TablerGlobe,
    grid: TablerGrid,
    image: TablerImage,
    archive: TablerArchive,
    key: TablerKey,
    list: TablerList,
    moon: TablerMoon,
    "map-pin": TablerMapPin,
    package: TablerPackage,
    pause: TablerPause,
    phone: TablerPhone,
    play: TablerPlay,
    refresh: TablerRefresh,
    rocket: TablerRocket,
    save: TablerSave,
    shield: TablerShield,
    "shopping-cart": TablerShoppingCart,
    "shopping-bag": TablerShoppingBag,
    stop: TablerStop,
    sun: TablerSun,
    tag: TablerTag,
    "thumbs-down": TablerThumbsDown,
    "thumbs-up": TablerThumbsUp,
    video: TablerVideo,
  },
  phosphor: {
    activity: PhosphorActivity,
    x: PhosphorX,
    "arrow-left": PhosphorArrowLeft,
    "arrow-right": PhosphorArrowRight,
    "arrow-up": PhosphorArrowUp,
    "arrow-down": PhosphorArrowDown,
    bookmark: PhosphorBookmark,
    "calendar-days": PhosphorCalendarDays,
    camera: PhosphorCamera,
    "chart-bar": PhosphorChartBar,
    "chart-pie": PhosphorChartPie,
    "chevron-left": PhosphorChevronLeft,
    "chevron-right": PhosphorChevronRight,
    "chevron-up": PhosphorChevronUp,
    "chevron-down": PhosphorChevronDown,
    clipboard: PhosphorClipboard,
    cloud: PhosphorCloud,
    home: PhosphorHome,
    "credit-card": PhosphorCreditCard,
    search: PhosphorSearch,
    user: PhosphorUser,
    users: PhosphorUsers,
    "user-plus": PhosphorUserPlus,
    "user-minus": PhosphorUserMinus,
    settings: PhosphorSettings,
    bell: PhosphorBell,
    mail: PhosphorMail,
    calendar: PhosphorCalendar,
    clock: PhosphorClock,
    check: PhosphorCheck,
    plus: PhosphorPlus,
    minus: PhosphorMinus,
    menu: PhosphorList,
    map: PhosphorMap,
    info: PhosphorInfo,
    help: PhosphorHelp,
    alert: PhosphorAlert,
    warning: PhosphorWarning,
    star: PhosphorStar,
    heart: PhosphorHeart,
    lock: PhosphorLock,
    unlock: PhosphorUnlock,
    eye: PhosphorEye,
    "eye-off": PhosphorEyeOff,
    trash: PhosphorTrash,
    edit: PhosphorEdit,
    download: PhosphorDownload,
    upload: PhosphorUpload,
    share: PhosphorShare,
    link: PhosphorLink,
    filter: PhosphorFilter,
    folder: PhosphorFolder,
    file: PhosphorFile,
    flag: PhosphorFlag,
    gift: PhosphorGift,
    globe: PhosphorGlobe,
    grid: PhosphorGrid,
    image: PhosphorImage,
    archive: PhosphorArchive,
    key: PhosphorKey,
    lightning: PhosphorLightning,
    list: PhosphorList,
    moon: PhosphorMoon,
    "map-pin": PhosphorMapPin,
    package: PhosphorPackage,
    pause: PhosphorPause,
    phone: PhosphorPhone,
    play: PhosphorPlay,
    refresh: PhosphorRefresh,
    rocket: PhosphorRocket,
    save: PhosphorSave,
    shield: PhosphorShield,
    "shopping-cart": PhosphorShoppingCart,
    "shopping-bag": PhosphorShoppingBag,
    stop: PhosphorStop,
    sun: PhosphorSun,
    tag: PhosphorTag,
    "thumbs-down": PhosphorThumbsDown,
    "thumbs-up": PhosphorThumbsUp,
    video: PhosphorVideo,
  },
  mui: {
    activity: MuiActivity,
    x: MuiX,
    "arrow-left": MuiArrowLeft,
    "arrow-right": MuiArrowRight,
    "arrow-up": MuiArrowUp,
    "arrow-down": MuiArrowDown,
    bookmark: MuiBookmark,
    "calendar-days": MuiCalendarDays,
    camera: MuiCamera,
    "chart-bar": MuiChartBar,
    "chart-pie": MuiChartPie,
    "chevron-left": MuiChevronLeft,
    "chevron-right": MuiChevronRight,
    "chevron-up": MuiChevronUp,
    "chevron-down": MuiChevronDown,
    "chevrons-up-down": MuiChevronsUpDown,
    clipboard: MuiClipboard,
    cloud: MuiCloud,
    home: MuiHome,
    "credit-card": MuiCreditCard,
    search: MuiSearch,
    user: MuiUser,
    users: MuiUsers,
    "user-plus": MuiUserPlus,
    "user-minus": MuiUserMinus,
    settings: MuiSettings,
    bell: MuiBell,
    mail: MuiMail,
    calendar: MuiCalendar,
    clock: MuiClock,
    check: MuiCheck,
    plus: MuiPlus,
    minus: MuiMinus,
    menu: MuiMenu,
    map: MuiMap,
    info: MuiInfo,
    help: MuiHelp,
    alert: MuiAlert,
    warning: MuiWarning,
    star: MuiStar,
    heart: MuiHeart,
    lock: MuiLock,
    unlock: MuiUnlock,
    eye: MuiEye,
    "eye-off": MuiEyeOff,
    trash: MuiTrash,
    edit: MuiEdit,
    download: MuiDownload,
    upload: MuiUpload,
    share: MuiShare,
    link: MuiLink,
    filter: MuiFilter,
    folder: MuiFolder,
    file: MuiFile,
    flag: MuiFlag,
    gift: MuiGift,
    globe: MuiGlobe,
    grid: MuiGrid,
    image: MuiImage,
    archive: MuiArchive,
    key: MuiKey,
    lightning: MuiLightning,
    list: MuiList,
    moon: MuiMoon,
    "map-pin": MuiMapPin,
    package: MuiPackage,
    pause: MuiPause,
    phone: MuiPhone,
    play: MuiPlay,
    refresh: MuiRefresh,
    rocket: MuiRocket,
    save: MuiSave,
    shield: MuiShield,
    "shopping-cart": MuiShoppingCart,
    "shopping-bag": MuiShoppingBag,
    stop: MuiStop,
    sun: MuiSun,
    tag: MuiTag,
    "thumbs-down": MuiThumbsDown,
    "thumbs-up": MuiThumbsUp,
    video: MuiVideo,
  },
  fontawesome: {
    activity: fontAwesome(faChartLine),
    x: fontAwesome(faXmark),
    "arrow-left": fontAwesome(faArrowLeft),
    "arrow-right": fontAwesome(faArrowRight),
    "arrow-up": fontAwesome(faArrowUp),
    "arrow-down": fontAwesome(faArrowDown),
    bookmark: fontAwesome(faBookmark),
    "calendar-days": fontAwesome(faCalendarDays),
    camera: fontAwesome(faCamera),
    "chart-bar": fontAwesome(faChartBar),
    "chart-pie": fontAwesome(faChartPie),
    "chevron-left": fontAwesome(faChevronLeft),
    "chevron-right": fontAwesome(faChevronRight),
    "chevron-up": fontAwesome(faChevronUp),
    "chevron-down": fontAwesome(faChevronDown),
    "chevrons-up-down": fontAwesome(faArrowsUpDown),
    clipboard: fontAwesome(faClipboard),
    cloud: fontAwesome(faCloud),
    home: fontAwesome(faHouse),
    "credit-card": fontAwesome(faCreditCard),
    search: fontAwesome(faMagnifyingGlass),
    user: fontAwesome(faUser),
    users: fontAwesome(faUsers),
    "user-plus": fontAwesome(faUserPlus),
    "user-minus": fontAwesome(faUserMinus),
    settings: fontAwesome(faGear),
    bell: fontAwesome(faBell),
    mail: fontAwesome(faEnvelope),
    calendar: fontAwesome(faCalendar),
    clock: fontAwesome(faClock),
    check: fontAwesome(faCheck),
    plus: fontAwesome(faPlus),
    minus: fontAwesome(faMinus),
    menu: fontAwesome(faBars),
    map: fontAwesome(faMap),
    info: fontAwesome(faCircleInfo),
    help: fontAwesome(faCircleQuestion),
    alert: fontAwesome(faCircleExclamation),
    warning: fontAwesome(faTriangleExclamation),
    star: fontAwesome(faStar),
    heart: fontAwesome(faHeart),
    lock: fontAwesome(faLock),
    unlock: fontAwesome(faLockOpen),
    eye: fontAwesome(faEye),
    "eye-off": fontAwesome(faEyeSlash),
    trash: fontAwesome(faTrash),
    edit: fontAwesome(faPenToSquare),
    download: fontAwesome(faDownload),
    upload: fontAwesome(faUpload),
    share: fontAwesome(faShare),
    link: fontAwesome(faLink),
    filter: fontAwesome(faFilter),
    folder: fontAwesome(faFolder),
    file: fontAwesome(faFile),
    flag: fontAwesome(faFlag),
    gift: fontAwesome(faGift),
    globe: fontAwesome(faGlobe),
    grid: fontAwesome(faGrip),
    image: fontAwesome(faImage),
    archive: fontAwesome(faArchive),
    key: fontAwesome(faKey),
    lightning: fontAwesome(faBolt),
    list: fontAwesome(faList),
    "map-pin": fontAwesome(faLocationDot),
    moon: fontAwesome(faMoon),
    package: fontAwesome(faBox),
    pause: fontAwesome(faPause),
    phone: fontAwesome(faPhone),
    play: fontAwesome(faPlay),
    refresh: fontAwesome(faArrowsRotate),
    rocket: fontAwesome(faRocket),
    save: fontAwesome(faSave),
    shield: fontAwesome(faShield),
    "shopping-cart": fontAwesome(faShoppingCart),
    "shopping-bag": fontAwesome(faBagShopping),
    stop: fontAwesome(faStop),
    sun: fontAwesome(faSun),
    tag: fontAwesome(faTag),
    "thumbs-down": fontAwesome(faThumbsDown),
    "thumbs-up": fontAwesome(faThumbsUp),
    video: fontAwesome(faVideo),
  },
};

const iconSetsSolid: Partial<
  Record<IconSetId, Record<string, LibraryIconComponent>>
> = {
  heroicons: {
    activity: HeroSolidActivity,
    x: HeroSolidX,
    "arrow-left": HeroSolidArrowLeft,
    "arrow-right": HeroSolidArrowRight,
    "arrow-up": HeroSolidArrowUp,
    "arrow-down": HeroSolidArrowDown,
    bookmark: HeroSolidBookmark,
    "calendar-days": HeroSolidCalendarDays,
    camera: HeroSolidCamera,
    "chart-bar": HeroSolidChartBar,
    "chart-pie": HeroSolidChartPie,
    "chevron-left": HeroSolidChevronLeft,
    "chevron-right": HeroSolidChevronRight,
    "chevron-up": HeroSolidChevronUp,
    "chevron-down": HeroSolidChevronDown,
    "chevrons-up-down": HeroSolidChevronsUpDown,
    clipboard: HeroSolidClipboard,
    cloud: HeroSolidCloud,
    home: HeroSolidHome,
    "credit-card": HeroSolidCreditCard,
    search: HeroSolidSearch,
    user: HeroSolidUser,
    users: HeroSolidUsers,
    "user-plus": HeroSolidUserPlus,
    "user-minus": HeroSolidUserMinus,
    settings: HeroSolidSettings,
    bell: HeroSolidBell,
    mail: HeroSolidMail,
    calendar: HeroSolidCalendar,
    clock: HeroSolidClock,
    check: HeroSolidCheck,
    plus: HeroSolidPlus,
    minus: HeroSolidMinus,
    menu: HeroSolidMenu,
    map: HeroSolidMap,
    info: HeroSolidInfo,
    help: HeroSolidHelp,
    alert: HeroSolidAlert,
    warning: HeroSolidWarning,
    star: HeroSolidStar,
    heart: HeroSolidHeart,
    lock: HeroSolidLock,
    unlock: HeroSolidUnlock,
    eye: HeroSolidEye,
    "eye-off": HeroSolidEyeOff,
    trash: HeroSolidTrash,
    edit: HeroSolidEdit,
    download: HeroSolidDownload,
    upload: HeroSolidUpload,
    share: HeroSolidShare,
    link: HeroSolidLink,
    filter: HeroSolidFilter,
    folder: HeroSolidFolder,
    file: HeroSolidFile,
    flag: HeroSolidFlag,
    gift: HeroSolidGift,
    globe: HeroSolidGlobe,
    grid: HeroSolidGrid,
    image: HeroSolidImage,
    archive: HeroSolidArchive,
    key: HeroSolidKey,
    list: HeroSolidList,
    moon: HeroSolidMoon,
    "map-pin": HeroSolidMapPin,
    package: HeroSolidPackage,
    pause: HeroSolidPause,
    phone: HeroSolidPhone,
    play: HeroSolidPlay,
    refresh: HeroSolidRefresh,
    rocket: HeroSolidRocket,
    save: HeroSolidDocumentText,
    shield: HeroSolidShield,
    "shopping-cart": HeroSolidShoppingCart,
    "shopping-bag": HeroSolidShoppingBag,
    stop: HeroSolidStop,
    sun: HeroSolidSun,
    tag: HeroSolidTag,
    "thumbs-down": HeroSolidThumbsDown,
    "thumbs-up": HeroSolidThumbsUp,
    lightning: HeroSolidLightning,
    video: HeroSolidVideo,
  },
  phosphor: {
    x: phosphorIcon(PhosphorX, "fill"),
    "arrow-left": phosphorIcon(PhosphorArrowLeft, "fill"),
    "arrow-right": phosphorIcon(PhosphorArrowRight, "fill"),
    "arrow-up": phosphorIcon(PhosphorArrowUp, "fill"),
    "arrow-down": phosphorIcon(PhosphorArrowDown, "fill"),
    "chevron-left": phosphorIcon(PhosphorChevronLeft, "fill"),
    "chevron-right": phosphorIcon(PhosphorChevronRight, "fill"),
    "chevron-up": phosphorIcon(PhosphorChevronUp, "fill"),
    "chevron-down": phosphorIcon(PhosphorChevronDown, "fill"),
    "chevrons-up-down": phosphorIcon(PhosphorChevronsUpDown, "fill"),
    home: phosphorIcon(PhosphorHome, "fill"),
    search: phosphorIcon(PhosphorSearch, "fill"),
    user: phosphorIcon(PhosphorUser, "fill"),
    settings: phosphorIcon(PhosphorSettings, "fill"),
    bell: phosphorIcon(PhosphorBell, "fill"),
    mail: phosphorIcon(PhosphorMail, "fill"),
    calendar: phosphorIcon(PhosphorCalendar, "fill"),
    clock: phosphorIcon(PhosphorClock, "fill"),
    check: phosphorIcon(PhosphorCheck, "fill"),
    plus: phosphorIcon(PhosphorPlus, "fill"),
    minus: phosphorIcon(PhosphorMinus, "fill"),
    menu: phosphorIcon(PhosphorList, "fill"),
    info: phosphorIcon(PhosphorInfo, "fill"),
    help: phosphorIcon(PhosphorHelp, "fill"),
    alert: phosphorIcon(PhosphorAlert, "fill"),
    star: phosphorIcon(PhosphorStar, "fill"),
    heart: phosphorIcon(PhosphorHeart, "fill"),
    lock: phosphorIcon(PhosphorLock, "fill"),
    unlock: phosphorIcon(PhosphorUnlock, "fill"),
    eye: phosphorIcon(PhosphorEye, "fill"),
    trash: phosphorIcon(PhosphorTrash, "fill"),
    edit: phosphorIcon(PhosphorEdit, "fill"),
    download: phosphorIcon(PhosphorDownload, "fill"),
    upload: phosphorIcon(PhosphorUpload, "fill"),
    share: phosphorIcon(PhosphorShare, "fill"),
    link: phosphorIcon(PhosphorLink, "fill"),
    filter: phosphorIcon(PhosphorFilter, "fill"),
    folder: phosphorIcon(PhosphorFolder, "fill"),
    file: phosphorIcon(PhosphorFile, "fill"),
    image: phosphorIcon(PhosphorImage, "fill"),
    archive: phosphorIcon(PhosphorArchive, "fill"),
    activity: phosphorIcon(PhosphorActivity, "fill"),
    bookmark: phosphorIcon(PhosphorBookmark, "fill"),
    "calendar-days": phosphorIcon(PhosphorCalendarDays, "fill"),
    camera: phosphorIcon(PhosphorCamera, "fill"),
    "chart-bar": phosphorIcon(PhosphorChartBar, "fill"),
    "chart-pie": phosphorIcon(PhosphorChartPie, "fill"),
    clipboard: phosphorIcon(PhosphorClipboard, "fill"),
    cloud: phosphorIcon(PhosphorCloud, "fill"),
    "credit-card": phosphorIcon(PhosphorCreditCard, "fill"),
    "eye-off": phosphorIcon(PhosphorEyeOff, "fill"),
    flag: phosphorIcon(PhosphorFlag, "fill"),
    gift: phosphorIcon(PhosphorGift, "fill"),
    globe: phosphorIcon(PhosphorGlobe, "fill"),
    grid: phosphorIcon(PhosphorGrid, "fill"),
    key: phosphorIcon(PhosphorKey, "fill"),
    lightning: phosphorIcon(PhosphorLightning, "fill"),
    list: phosphorIcon(PhosphorList, "fill"),
    map: phosphorIcon(PhosphorMap, "fill"),
    "map-pin": phosphorIcon(PhosphorMapPin, "fill"),
    moon: phosphorIcon(PhosphorMoon, "fill"),
    package: phosphorIcon(PhosphorPackage, "fill"),
    pause: phosphorIcon(PhosphorPause, "fill"),
    phone: phosphorIcon(PhosphorPhone, "fill"),
    play: phosphorIcon(PhosphorPlay, "fill"),
    refresh: phosphorIcon(PhosphorRefresh, "fill"),
    rocket: phosphorIcon(PhosphorRocket, "fill"),
    save: phosphorIcon(PhosphorSave, "fill"),
    shield: phosphorIcon(PhosphorShield, "fill"),
    "shopping-cart": phosphorIcon(PhosphorShoppingCart, "fill"),
    "shopping-bag": phosphorIcon(PhosphorShoppingBag, "fill"),
    stop: phosphorIcon(PhosphorStop, "fill"),
    sun: phosphorIcon(PhosphorSun, "fill"),
    tag: phosphorIcon(PhosphorTag, "fill"),
    "thumbs-down": phosphorIcon(PhosphorThumbsDown, "fill"),
    "thumbs-up": phosphorIcon(PhosphorThumbsUp, "fill"),
    users: phosphorIcon(PhosphorUsers, "fill"),
    "user-plus": phosphorIcon(PhosphorUserPlus, "fill"),
    "user-minus": phosphorIcon(PhosphorUserMinus, "fill"),
    video: phosphorIcon(PhosphorVideo, "fill"),
    warning: phosphorIcon(PhosphorWarning, "fill"),
  },
};

const IconSetContext = React.createContext<IconSetId>(FALLBACK_SET);
const IconStyleContext = React.createContext<IconStyle>("outline");

type IconSetProviderProps = {
  value: IconSetId;
  children: React.ReactNode;
};

type IconStyleProviderProps = {
  value: IconStyle;
  children: React.ReactNode;
};

type LibraryIconProps = {
  name: string;
  set?: IconSetId;
  variant?: IconStyle;
  size?: number;
  className?: string;
  title?: string;
  "aria-label"?: string;
  "aria-hidden"?: React.AriaAttributes["aria-hidden"];
  "aria-busy"?: boolean;
};

function IconSetProvider({ value, children }: IconSetProviderProps) {
  return (
    <IconSetContext.Provider value={value}>{children}</IconSetContext.Provider>
  );
}

function IconStyleProvider({ value, children }: IconStyleProviderProps) {
  return (
    <IconStyleContext.Provider value={value}>
      {children}
    </IconStyleContext.Provider>
  );
}

function LibraryIcon({
  name,
  set,
  variant,
  size,
  className,
  title,
  "aria-label": ariaLabel,
  "aria-hidden": ariaHidden,
  "aria-busy": ariaBusy,
}: LibraryIconProps) {
  const contextSet = React.useContext(IconSetContext);
  const contextVariant = React.useContext(IconStyleContext);
  const fallbackSet = iconSets[FALLBACK_SET];
  const activeSet = set ?? contextSet;
  const activeVariant = variant ?? contextVariant;
  const baseIcons = iconSets[activeSet] ?? fallbackSet;
  const solidIcons = iconSetsSolid[activeSet];
  const activeIcons =
    activeVariant === "solid" ? (solidIcons ?? baseIcons) : baseIcons;
  const IconComponent =
    activeIcons?.[name] ?? baseIcons?.[name] ?? fallbackSet?.[name];

  if (!IconComponent) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(
        `LibraryIcon: missing icon "${name}" in set "${activeSet}".`,
      );
    }
    return null;
  }

  const label = ariaLabel ?? title;
  const style = size ? { width: size, height: size } : undefined;
  const resolvedAriaHidden = ariaHidden ?? (label ? undefined : true);

  return (
    <IconComponent
      className={className}
      style={style}
      title={title}
      aria-label={label}
      aria-hidden={resolvedAriaHidden}
      aria-busy={ariaBusy}
    />
  );
}

export { IconSetProvider, IconStyleProvider, LibraryIcon };
