---
ID: "d03fa10c-9e58-4daa-a51d-0ff2e68ab44c"
Parent: "ea81c995-9bfb-46cb-a0c4-5bd3c1a73f6e"
Template: "ea81c995-9bfb-46cb-a0c4-5bd3c1a73f6e"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/search/search-booking-segment/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "search-booking-segment@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "dadfdd76-f890-48c9-84c2-8408ddfba3f6"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "2221c38a-3ae4-4eca-8735-3514fd9904e8"
      Hint: Label
      Value: From
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T020504Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c7f08b3d-377f-4f52-a1bf-720ab3519e76"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d76a6dde-f45f-441c-a249-21d875749746"
      Hint: SegmentType
      Value: text
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T020504Z
