---
ID: "f2239697-3c59-4e2f-8052-8374bc6a507a"
Parent: "fa326c91-01ad-4418-a527-133ee191394b"
Template: "fa326c91-01ad-4418-a527-133ee191394b"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/cards-and-lists/pricing-card/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c8fc6fb4-06db-472f-adb3-e69ee3d09dea"
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: ابدأ الآن
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60f1e4d2-4e05-4169-b698-5823f36524e0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: الباقة الأساسية
- Language: "ar-SA"
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: ابدأ الآن
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a68497de-b27f-4784-9431-e9122c49d320"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151923Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: الباقة الأساسية
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Kom i gang
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "17284473-f3a5-4f72-8b0c-6995ec6236e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Starter
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Loslegen
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "894fd783-dcdc-4d49-9f3e-0102e59003e5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Starter
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Loslegen
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bca21f37-cb84-4ec4-ac42-5a9056796e10"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151922Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Get started
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221547Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5968e55b-3142-446b-b75c-6d6164147b23"
      Hint: HighlightLabel
      Value: Most popular
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "130ea002-89fa-4edc-b4c2-0225614447d2"
    - ID: "b951586a-e2ad-4f41-af25-801312e37ec9"
      Hint: Price
      Value: $29
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "cc3f679d-4557-480e-87ab-664adf0fa89c"
      Hint: Currency
      Value: USD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260904T222709Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Starter
    - ID: "f9e48def-5ad7-45c2-b977-19473c35bbf1"
      Hint: PricePeriod
      Value: /month
- Language: es
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Comenzar
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb65c12d-9f81-4d0a-8de2-745a05251e3a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Inicial
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Comenzar
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "843c324f-b914-4829-a3a5-a6b31c395d07"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151923Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Inicial
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Commencer
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1864455b-d618-4fe2-9cb5-7a10e1c46531"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Essentiel
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Commencer
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1c4e48ae-bb67-40bb-b748-e4d4113aeefa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151923Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Essentiel
- Language: it
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: Inizia
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ab1c746-2dfa-4ab9-a068-ea544ba9a7c9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: Base
- Language: ja
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: 始める
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "143e4595-1192-4b13-ac93-512fba7cdc73"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: スターター
- Language: "zh-CN"
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: 开始使用
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c40427ea-db1c-4dee-bb97-a235003927a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: 入门版
- Language: "zh-TW"
  Versions:
  - Version: 1
    Fields:
    - ID: "239e44d1-ba83-4e0f-b085-f2140e51e338"
      Hint: CtaLabel
      Value: 開始使用
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T221548Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8ddb86d6-d6f8-49d0-a256-19e14bed4ec2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T221549Z
    - ID: "f2fb3620-7eee-414a-bb8b-e2bc4e95cbc7"
      Hint: Name
      Value: 入門版
