import type { DictionaryRecipe } from "@sitecoreai-labs/sitecoreai-cli/recipe";

/**
 * AI Chat UI Labels — Message Actions — a shard of the AI Chat UI Labels phrase library, split so no
 * single Dictionary recipe pushes more item versions than one sandbox can
 * apply. Phrase keys are unchanged; only which recipe authors them differs.
 */
export const aiChatUiLabelsActionsRecipe = {
  kind: "dictionary",
  schemaVersion: "1",
  handle: "ai-chat-ui-labels-actions@1",
  name: "AiChatUiLabelsActions",
  displayName: "AI Chat UI Labels — Message Actions",
  description:
    "AI Chat dictionary shard — per-message action tooltips and response-structure phrases (copy, regenerate, feedback, variants, step divider, source/file fallbacks).",
  primaryLocale: "en",
  phrases: {
    "ai-chat-copy": {
      defaultValue: "Copy",
      translations: {
        "ar-AE": "نسخ",
        "ar-BH": "نسخ",
        "ar-DZ": "نسخ",
        "ar-EG": "نسخ",
        "ar-IQ": "نسخ",
        "ar-JO": "نسخ",
        "ar-KW": "نسخ",
        "ar-LB": "نسخ",
        "ar-LY": "نسخ",
        "ar-MA": "نسخ",
        "ar-OM": "نسخ",
        "ar-QA": "نسخ",
        "ar-SA": "نسخ",
        "ar-SY": "نسخ",
        "ar-TN": "نسخ",
        "ar-YE": "نسخ",
        "cs-CZ": "Kopírovat",
        da: "Kopiér",
        "de-AT": "Kopieren",
        "de-CH": "Kopieren",
        "de-DE": "Kopieren",
        "de-LI": "Kopieren",
        "de-LU": "Kopieren",
        "el-GR": "Αντιγραφή",
        "en-AU": "Copy",
        "en-BZ": "Copy",
        "en-CA": "Copy",
        "en-GB": "Copy",
        "en-IE": "Copy",
        "en-JM": "Copy",
        "en-NZ": "Copy",
        "en-PH": "Copy",
        "en-TT": "Copy",
        "en-US": "Copy",
        "en-ZA": "Copy",
        "en-ZW": "Copy",
        "es-AR": "Copiar",
        "es-BO": "Copiar",
        "es-CL": "Copiar",
        "es-CO": "Copiar",
        "es-CR": "Copiar",
        "es-DO": "Copiar",
        "es-EC": "Copiar",
        "es-ES": "Copiar",
        "es-GT": "Copiar",
        "es-HN": "Copiar",
        "es-MX": "Copiar",
        "es-NI": "Copiar",
        "es-PA": "Copiar",
        "es-PE": "Copiar",
        "es-PR": "Copiar",
        "es-PY": "Copiar",
        "es-SV": "Copiar",
        "es-UY": "Copiar",
        "es-VE": "Copiar",
        "fi-FI": "Kopioi",
        "fr-BE": "Copier",
        "fr-CA": "Copier",
        "fr-CH": "Copier",
        "fr-FR": "Copier",
        "fr-LU": "Copier",
        "fr-MC": "Copier",
        "he-IL": "העתקה",
        "hi-IN": "कॉपी करें",
        "hu-HU": "Másolás",
        "id-ID": "Salin",
        "it-CH": "Copia",
        "it-IT": "Copia",
        "ja-JP": "コピー",
        "ko-KR": "복사",
        "nb-NO": "Kopier",
        "nl-BE": "Kopiëren",
        "nl-NL": "Kopiëren",
        "pl-PL": "Kopiuj",
        "pt-BR": "Copiar",
        "pt-PT": "Copiar",
        "ro-RO": "Copiază",
        "ru-RU": "Копировать",
        "sk-SK": "Kopírovať",
        "sv-FI": "Kopiera",
        "sv-SE": "Kopiera",
        "th-TH": "คัดลอก",
        "tr-TR": "Kopyala",
        "uk-UA": "Копіювати",
        "vi-VN": "Sao chép",
        "zh-CN": "复制",
        "zh-SG": "复制",
        "zh-TW": "複製",
      },
      description: "Copy-message action tooltip.",
    },
    "ai-chat-copied": {
      defaultValue: "Copied",
      translations: {
        "ar-AE": "تم النسخ",
        "ar-BH": "تم النسخ",
        "ar-DZ": "تم النسخ",
        "ar-EG": "تم النسخ",
        "ar-IQ": "تم النسخ",
        "ar-JO": "تم النسخ",
        "ar-KW": "تم النسخ",
        "ar-LB": "تم النسخ",
        "ar-LY": "تم النسخ",
        "ar-MA": "تم النسخ",
        "ar-OM": "تم النسخ",
        "ar-QA": "تم النسخ",
        "ar-SA": "تم النسخ",
        "ar-SY": "تم النسخ",
        "ar-TN": "تم النسخ",
        "ar-YE": "تم النسخ",
        "cs-CZ": "Zkopírováno",
        da: "Kopieret",
        "de-AT": "Kopiert",
        "de-CH": "Kopiert",
        "de-DE": "Kopiert",
        "de-LI": "Kopiert",
        "de-LU": "Kopiert",
        "el-GR": "Αντιγράφηκε",
        "en-AU": "Copied",
        "en-BZ": "Copied",
        "en-CA": "Copied",
        "en-GB": "Copied",
        "en-IE": "Copied",
        "en-JM": "Copied",
        "en-NZ": "Copied",
        "en-PH": "Copied",
        "en-TT": "Copied",
        "en-US": "Copied",
        "en-ZA": "Copied",
        "en-ZW": "Copied",
        "es-AR": "Copiado",
        "es-BO": "Copiado",
        "es-CL": "Copiado",
        "es-CO": "Copiado",
        "es-CR": "Copiado",
        "es-DO": "Copiado",
        "es-EC": "Copiado",
        "es-ES": "Copiado",
        "es-GT": "Copiado",
        "es-HN": "Copiado",
        "es-MX": "Copiado",
        "es-NI": "Copiado",
        "es-PA": "Copiado",
        "es-PE": "Copiado",
        "es-PR": "Copiado",
        "es-PY": "Copiado",
        "es-SV": "Copiado",
        "es-UY": "Copiado",
        "es-VE": "Copiado",
        "fi-FI": "Kopioitu",
        "fr-BE": "Copié",
        "fr-CA": "Copié",
        "fr-CH": "Copié",
        "fr-FR": "Copié",
        "fr-LU": "Copié",
        "fr-MC": "Copié",
        "he-IL": "הועתק",
        "hi-IN": "कॉपी किया गया",
        "hu-HU": "Másolva",
        "id-ID": "Disalin",
        "it-CH": "Copiato",
        "it-IT": "Copiato",
        "ja-JP": "コピーしました",
        "ko-KR": "복사됨",
        "nb-NO": "Kopiert",
        "nl-BE": "Gekopieerd",
        "nl-NL": "Gekopieerd",
        "pl-PL": "Skopiowano",
        "pt-BR": "Copiado",
        "pt-PT": "Copiado",
        "ro-RO": "Copiat",
        "ru-RU": "Скопировано",
        "sk-SK": "Skopírované",
        "sv-FI": "Kopierat",
        "sv-SE": "Kopierat",
        "th-TH": "คัดลอกแล้ว",
        "tr-TR": "Kopyalandı",
        "uk-UA": "Скопійовано",
        "vi-VN": "Đã sao chép",
        "zh-CN": "已复制",
        "zh-SG": "已复制",
        "zh-TW": "已複製",
      },
      description: "Copy action tooltip after a successful copy.",
    },
    "ai-chat-regenerate": {
      defaultValue: "Regenerate",
      translations: {
        "ar-AE": "إعادة التوليد",
        "ar-BH": "إعادة التوليد",
        "ar-DZ": "إعادة التوليد",
        "ar-EG": "إعادة التوليد",
        "ar-IQ": "إعادة التوليد",
        "ar-JO": "إعادة التوليد",
        "ar-KW": "إعادة التوليد",
        "ar-LB": "إعادة التوليد",
        "ar-LY": "إعادة التوليد",
        "ar-MA": "إعادة التوليد",
        "ar-OM": "إعادة التوليد",
        "ar-QA": "إعادة التوليد",
        "ar-SA": "إعادة التوليد",
        "ar-SY": "إعادة التوليد",
        "ar-TN": "إعادة التوليد",
        "ar-YE": "إعادة التوليد",
        "cs-CZ": "Vygenerovat znovu",
        da: "Generér igen",
        "de-AT": "Neu generieren",
        "de-CH": "Neu generieren",
        "de-DE": "Neu generieren",
        "de-LI": "Neu generieren",
        "de-LU": "Neu generieren",
        "el-GR": "Αναδημιουργία",
        "en-AU": "Regenerate",
        "en-BZ": "Regenerate",
        "en-CA": "Regenerate",
        "en-GB": "Regenerate",
        "en-IE": "Regenerate",
        "en-JM": "Regenerate",
        "en-NZ": "Regenerate",
        "en-PH": "Regenerate",
        "en-TT": "Regenerate",
        "en-US": "Regenerate",
        "en-ZA": "Regenerate",
        "en-ZW": "Regenerate",
        "es-AR": "Regenerar",
        "es-BO": "Regenerar",
        "es-CL": "Regenerar",
        "es-CO": "Regenerar",
        "es-CR": "Regenerar",
        "es-DO": "Regenerar",
        "es-EC": "Regenerar",
        "es-ES": "Regenerar",
        "es-GT": "Regenerar",
        "es-HN": "Regenerar",
        "es-MX": "Regenerar",
        "es-NI": "Regenerar",
        "es-PA": "Regenerar",
        "es-PE": "Regenerar",
        "es-PR": "Regenerar",
        "es-PY": "Regenerar",
        "es-SV": "Regenerar",
        "es-UY": "Regenerar",
        "es-VE": "Regenerar",
        "fi-FI": "Luo uudelleen",
        "fr-BE": "Régénérer",
        "fr-CA": "Régénérer",
        "fr-CH": "Régénérer",
        "fr-FR": "Régénérer",
        "fr-LU": "Régénérer",
        "fr-MC": "Régénérer",
        "he-IL": "יצירה מחדש",
        "hi-IN": "पुनः जनरेट करें",
        "hu-HU": "Újragenerálás",
        "id-ID": "Buat ulang",
        "it-CH": "Rigenera",
        "it-IT": "Rigenera",
        "ja-JP": "再生成",
        "ko-KR": "다시 생성",
        "nb-NO": "Generer på nytt",
        "nl-BE": "Opnieuw genereren",
        "nl-NL": "Opnieuw genereren",
        "pl-PL": "Wygeneruj ponownie",
        "pt-BR": "Regenerar",
        "pt-PT": "Regenerar",
        "ro-RO": "Regenerează",
        "ru-RU": "Сгенерировать заново",
        "sk-SK": "Vygenerovať znova",
        "sv-FI": "Generera igen",
        "sv-SE": "Generera igen",
        "th-TH": "สร้างใหม่",
        "tr-TR": "Yeniden oluştur",
        "uk-UA": "Згенерувати знову",
        "vi-VN": "Tạo lại",
        "zh-CN": "重新生成",
        "zh-SG": "重新生成",
        "zh-TW": "重新產生",
      },
      description: "Regenerate-response action tooltip.",
    },
    "ai-chat-helpful": {
      defaultValue: "Helpful",
      translations: {
        "ar-AE": "مفيد",
        "ar-BH": "مفيد",
        "ar-DZ": "مفيد",
        "ar-EG": "مفيد",
        "ar-IQ": "مفيد",
        "ar-JO": "مفيد",
        "ar-KW": "مفيد",
        "ar-LB": "مفيد",
        "ar-LY": "مفيد",
        "ar-MA": "مفيد",
        "ar-OM": "مفيد",
        "ar-QA": "مفيد",
        "ar-SA": "مفيد",
        "ar-SY": "مفيد",
        "ar-TN": "مفيد",
        "ar-YE": "مفيد",
        "cs-CZ": "Užitečné",
        da: "Nyttigt",
        "de-AT": "Hilfreich",
        "de-CH": "Hilfreich",
        "de-DE": "Hilfreich",
        "de-LI": "Hilfreich",
        "de-LU": "Hilfreich",
        "el-GR": "Χρήσιμο",
        "en-AU": "Helpful",
        "en-BZ": "Helpful",
        "en-CA": "Helpful",
        "en-GB": "Helpful",
        "en-IE": "Helpful",
        "en-JM": "Helpful",
        "en-NZ": "Helpful",
        "en-PH": "Helpful",
        "en-TT": "Helpful",
        "en-US": "Helpful",
        "en-ZA": "Helpful",
        "en-ZW": "Helpful",
        "es-AR": "Útil",
        "es-BO": "Útil",
        "es-CL": "Útil",
        "es-CO": "Útil",
        "es-CR": "Útil",
        "es-DO": "Útil",
        "es-EC": "Útil",
        "es-ES": "Útil",
        "es-GT": "Útil",
        "es-HN": "Útil",
        "es-MX": "Útil",
        "es-NI": "Útil",
        "es-PA": "Útil",
        "es-PE": "Útil",
        "es-PR": "Útil",
        "es-PY": "Útil",
        "es-SV": "Útil",
        "es-UY": "Útil",
        "es-VE": "Útil",
        "fi-FI": "Hyödyllinen",
        "fr-BE": "Utile",
        "fr-CA": "Utile",
        "fr-CH": "Utile",
        "fr-FR": "Utile",
        "fr-LU": "Utile",
        "fr-MC": "Utile",
        "he-IL": "מועיל",
        "hi-IN": "उपयोगी",
        "hu-HU": "Hasznos",
        "id-ID": "Bermanfaat",
        "it-CH": "Utile",
        "it-IT": "Utile",
        "ja-JP": "役に立った",
        "ko-KR": "도움됨",
        "nb-NO": "Nyttig",
        "nl-BE": "Nuttig",
        "nl-NL": "Nuttig",
        "pl-PL": "Pomocne",
        "pt-BR": "Útil",
        "pt-PT": "Útil",
        "ro-RO": "Util",
        "ru-RU": "Полезно",
        "sk-SK": "Užitočné",
        "sv-FI": "Användbart",
        "sv-SE": "Användbart",
        "th-TH": "มีประโยชน์",
        "tr-TR": "Yararlı",
        "uk-UA": "Корисно",
        "vi-VN": "Hữu ích",
        "zh-CN": "有帮助",
        "zh-SG": "有帮助",
        "zh-TW": "有幫助",
      },
      description: "Thumbs-up action tooltip.",
    },
    "ai-chat-not-helpful": {
      defaultValue: "Not helpful",
      translations: {
        "ar-AE": "غير مفيد",
        "ar-BH": "غير مفيد",
        "ar-DZ": "غير مفيد",
        "ar-EG": "غير مفيد",
        "ar-IQ": "غير مفيد",
        "ar-JO": "غير مفيد",
        "ar-KW": "غير مفيد",
        "ar-LB": "غير مفيد",
        "ar-LY": "غير مفيد",
        "ar-MA": "غير مفيد",
        "ar-OM": "غير مفيد",
        "ar-QA": "غير مفيد",
        "ar-SA": "غير مفيد",
        "ar-SY": "غير مفيد",
        "ar-TN": "غير مفيد",
        "ar-YE": "غير مفيد",
        "cs-CZ": "Neužitečné",
        da: "Ikke nyttigt",
        "de-AT": "Nicht hilfreich",
        "de-CH": "Nicht hilfreich",
        "de-DE": "Nicht hilfreich",
        "de-LI": "Nicht hilfreich",
        "de-LU": "Nicht hilfreich",
        "el-GR": "Μη χρήσιμο",
        "en-AU": "Not helpful",
        "en-BZ": "Not helpful",
        "en-CA": "Not helpful",
        "en-GB": "Not helpful",
        "en-IE": "Not helpful",
        "en-JM": "Not helpful",
        "en-NZ": "Not helpful",
        "en-PH": "Not helpful",
        "en-TT": "Not helpful",
        "en-US": "Not helpful",
        "en-ZA": "Not helpful",
        "en-ZW": "Not helpful",
        "es-AR": "No útil",
        "es-BO": "No útil",
        "es-CL": "No útil",
        "es-CO": "No útil",
        "es-CR": "No útil",
        "es-DO": "No útil",
        "es-EC": "No útil",
        "es-ES": "No útil",
        "es-GT": "No útil",
        "es-HN": "No útil",
        "es-MX": "No útil",
        "es-NI": "No útil",
        "es-PA": "No útil",
        "es-PE": "No útil",
        "es-PR": "No útil",
        "es-PY": "No útil",
        "es-SV": "No útil",
        "es-UY": "No útil",
        "es-VE": "No útil",
        "fi-FI": "Ei hyödyllinen",
        "fr-BE": "Pas utile",
        "fr-CA": "Pas utile",
        "fr-CH": "Pas utile",
        "fr-FR": "Pas utile",
        "fr-LU": "Pas utile",
        "fr-MC": "Pas utile",
        "he-IL": "לא מועיל",
        "hi-IN": "उपयोगी नहीं",
        "hu-HU": "Nem hasznos",
        "id-ID": "Tidak bermanfaat",
        "it-CH": "Non utile",
        "it-IT": "Non utile",
        "ja-JP": "役に立たなかった",
        "ko-KR": "도움 안 됨",
        "nb-NO": "Ikke nyttig",
        "nl-BE": "Niet nuttig",
        "nl-NL": "Niet nuttig",
        "pl-PL": "Niepomocne",
        "pt-BR": "Não útil",
        "pt-PT": "Não útil",
        "ro-RO": "Neutil",
        "ru-RU": "Бесполезно",
        "sk-SK": "Neužitočné",
        "sv-FI": "Inte användbart",
        "sv-SE": "Inte användbart",
        "th-TH": "ไม่มีประโยชน์",
        "tr-TR": "Yararsız",
        "uk-UA": "Не корисно",
        "vi-VN": "Không hữu ích",
        "zh-CN": "没帮助",
        "zh-SG": "没帮助",
        "zh-TW": "沒幫助",
      },
      description: "Thumbs-down action tooltip.",
    },
    "ai-chat-response-variants": {
      defaultValue: "Response variants",
      translations: {
        "ar-AE": "أشكال الاستجابة",
        "ar-BH": "أشكال الاستجابة",
        "ar-DZ": "أشكال الاستجابة",
        "ar-EG": "أشكال الاستجابة",
        "ar-IQ": "أشكال الاستجابة",
        "ar-JO": "أشكال الاستجابة",
        "ar-KW": "أشكال الاستجابة",
        "ar-LB": "أشكال الاستجابة",
        "ar-LY": "أشكال الاستجابة",
        "ar-MA": "أشكال الاستجابة",
        "ar-OM": "أشكال الاستجابة",
        "ar-QA": "أشكال الاستجابة",
        "ar-SA": "أشكال الاستجابة",
        "ar-SY": "أشكال الاستجابة",
        "ar-TN": "أشكال الاستجابة",
        "ar-YE": "أشكال الاستجابة",
        "cs-CZ": "Varianty odpovědi",
        da: "Svarvarianter",
        "de-AT": "Antwortvarianten",
        "de-CH": "Antwortvarianten",
        "de-DE": "Antwortvarianten",
        "de-LI": "Antwortvarianten",
        "de-LU": "Antwortvarianten",
        "el-GR": "Παραλλαγές απάντησης",
        "en-AU": "Response variants",
        "en-BZ": "Response variants",
        "en-CA": "Response variants",
        "en-GB": "Response variants",
        "en-IE": "Response variants",
        "en-JM": "Response variants",
        "en-NZ": "Response variants",
        "en-PH": "Response variants",
        "en-TT": "Response variants",
        "en-US": "Response variants",
        "en-ZA": "Response variants",
        "en-ZW": "Response variants",
        "es-AR": "Variantes de respuesta",
        "es-BO": "Variantes de respuesta",
        "es-CL": "Variantes de respuesta",
        "es-CO": "Variantes de respuesta",
        "es-CR": "Variantes de respuesta",
        "es-DO": "Variantes de respuesta",
        "es-EC": "Variantes de respuesta",
        "es-ES": "Variantes de respuesta",
        "es-GT": "Variantes de respuesta",
        "es-HN": "Variantes de respuesta",
        "es-MX": "Variantes de respuesta",
        "es-NI": "Variantes de respuesta",
        "es-PA": "Variantes de respuesta",
        "es-PE": "Variantes de respuesta",
        "es-PR": "Variantes de respuesta",
        "es-PY": "Variantes de respuesta",
        "es-SV": "Variantes de respuesta",
        "es-UY": "Variantes de respuesta",
        "es-VE": "Variantes de respuesta",
        "fi-FI": "Vastausvaihtoehdot",
        "fr-BE": "Variantes de réponse",
        "fr-CA": "Variantes de réponse",
        "fr-CH": "Variantes de réponse",
        "fr-FR": "Variantes de réponse",
        "fr-LU": "Variantes de réponse",
        "fr-MC": "Variantes de réponse",
        "he-IL": "וריאציות תגובה",
        "hi-IN": "प्रतिक्रिया के प्रकार",
        "hu-HU": "Válaszváltozatok",
        "id-ID": "Varian respons",
        "it-CH": "Varianti di risposta",
        "it-IT": "Varianti di risposta",
        "ja-JP": "応答のバリエーション",
        "ko-KR": "응답 변형",
        "nb-NO": "Svarvarianter",
        "nl-BE": "Antwoordvarianten",
        "nl-NL": "Antwoordvarianten",
        "pl-PL": "Warianty odpowiedzi",
        "pt-BR": "Variantes de resposta",
        "pt-PT": "Variantes de resposta",
        "ro-RO": "Variante de răspuns",
        "ru-RU": "Варианты ответа",
        "sk-SK": "Varianty odpovede",
        "sv-FI": "Svarsvarianter",
        "sv-SE": "Svarsvarianter",
        "th-TH": "ตัวเลือกการตอบกลับ",
        "tr-TR": "Yanıt çeşitleri",
        "uk-UA": "Варіанти відповіді",
        "vi-VN": "Các phiên bản phản hồi",
        "zh-CN": "回复变体",
        "zh-SG": "回复变体",
        "zh-TW": "回覆變體",
      },
      description: "Aria-label for the regenerate branch selector.",
    },
    "ai-chat-step": {
      defaultValue: "Step",
      translations: {
        "ar-AE": "الخطوة",
        "ar-BH": "الخطوة",
        "ar-DZ": "الخطوة",
        "ar-EG": "الخطوة",
        "ar-IQ": "الخطوة",
        "ar-JO": "الخطوة",
        "ar-KW": "الخطوة",
        "ar-LB": "الخطوة",
        "ar-LY": "الخطوة",
        "ar-MA": "الخطوة",
        "ar-OM": "الخطوة",
        "ar-QA": "الخطوة",
        "ar-SA": "الخطوة",
        "ar-SY": "الخطوة",
        "ar-TN": "الخطوة",
        "ar-YE": "الخطوة",
        "cs-CZ": "Krok",
        da: "Trin",
        "de-AT": "Schritt",
        "de-CH": "Schritt",
        "de-DE": "Schritt",
        "de-LI": "Schritt",
        "de-LU": "Schritt",
        "el-GR": "Βήμα",
        "en-AU": "Step",
        "en-BZ": "Step",
        "en-CA": "Step",
        "en-GB": "Step",
        "en-IE": "Step",
        "en-JM": "Step",
        "en-NZ": "Step",
        "en-PH": "Step",
        "en-TT": "Step",
        "en-US": "Step",
        "en-ZA": "Step",
        "en-ZW": "Step",
        "es-AR": "Paso",
        "es-BO": "Paso",
        "es-CL": "Paso",
        "es-CO": "Paso",
        "es-CR": "Paso",
        "es-DO": "Paso",
        "es-EC": "Paso",
        "es-ES": "Paso",
        "es-GT": "Paso",
        "es-HN": "Paso",
        "es-MX": "Paso",
        "es-NI": "Paso",
        "es-PA": "Paso",
        "es-PE": "Paso",
        "es-PR": "Paso",
        "es-PY": "Paso",
        "es-SV": "Paso",
        "es-UY": "Paso",
        "es-VE": "Paso",
        "fi-FI": "Vaihe",
        "fr-BE": "Étape",
        "fr-CA": "Étape",
        "fr-CH": "Étape",
        "fr-FR": "Étape",
        "fr-LU": "Étape",
        "fr-MC": "Étape",
        "he-IL": "שלב",
        "hi-IN": "चरण",
        "hu-HU": "Lépés",
        "id-ID": "Langkah",
        "it-CH": "Passaggio",
        "it-IT": "Passaggio",
        "ja-JP": "ステップ",
        "ko-KR": "단계",
        "nb-NO": "Trinn",
        "nl-BE": "Stap",
        "nl-NL": "Stap",
        "pl-PL": "Krok",
        "pt-BR": "Etapa",
        "pt-PT": "Passo",
        "ro-RO": "Pas",
        "ru-RU": "Шаг",
        "sk-SK": "Krok",
        "sv-FI": "Steg",
        "sv-SE": "Steg",
        "th-TH": "ขั้นตอน",
        "tr-TR": "Adım",
        "uk-UA": "Крок",
        "vi-VN": "Bước",
        "zh-CN": "步骤",
        "zh-SG": "步骤",
        "zh-TW": "步驟",
      },
      description: "Divider label between agent steps in a response.",
    },
    "ai-chat-source": {
      defaultValue: "Source",
      translations: {
        "ar-AE": "المصدر",
        "ar-BH": "المصدر",
        "ar-DZ": "المصدر",
        "ar-EG": "المصدر",
        "ar-IQ": "المصدر",
        "ar-JO": "المصدر",
        "ar-KW": "المصدر",
        "ar-LB": "المصدر",
        "ar-LY": "المصدر",
        "ar-MA": "المصدر",
        "ar-OM": "المصدر",
        "ar-QA": "المصدر",
        "ar-SA": "المصدر",
        "ar-SY": "المصدر",
        "ar-TN": "المصدر",
        "ar-YE": "المصدر",
        "cs-CZ": "Zdroj",
        da: "Kilde",
        "de-AT": "Quelle",
        "de-CH": "Quelle",
        "de-DE": "Quelle",
        "de-LI": "Quelle",
        "de-LU": "Quelle",
        "el-GR": "Πηγή",
        "en-AU": "Source",
        "en-BZ": "Source",
        "en-CA": "Source",
        "en-GB": "Source",
        "en-IE": "Source",
        "en-JM": "Source",
        "en-NZ": "Source",
        "en-PH": "Source",
        "en-TT": "Source",
        "en-US": "Source",
        "en-ZA": "Source",
        "en-ZW": "Source",
        "es-AR": "Fuente",
        "es-BO": "Fuente",
        "es-CL": "Fuente",
        "es-CO": "Fuente",
        "es-CR": "Fuente",
        "es-DO": "Fuente",
        "es-EC": "Fuente",
        "es-ES": "Fuente",
        "es-GT": "Fuente",
        "es-HN": "Fuente",
        "es-MX": "Fuente",
        "es-NI": "Fuente",
        "es-PA": "Fuente",
        "es-PE": "Fuente",
        "es-PR": "Fuente",
        "es-PY": "Fuente",
        "es-SV": "Fuente",
        "es-UY": "Fuente",
        "es-VE": "Fuente",
        "fi-FI": "Lähde",
        "fr-BE": "Source",
        "fr-CA": "Source",
        "fr-CH": "Source",
        "fr-FR": "Source",
        "fr-LU": "Source",
        "fr-MC": "Source",
        "he-IL": "מקור",
        "hi-IN": "स्रोत",
        "hu-HU": "Forrás",
        "id-ID": "Sumber",
        "it-CH": "Fonte",
        "it-IT": "Fonte",
        "ja-JP": "ソース",
        "ko-KR": "출처",
        "nb-NO": "Kilde",
        "nl-BE": "Bron",
        "nl-NL": "Bron",
        "pl-PL": "Źródło",
        "pt-BR": "Fonte",
        "pt-PT": "Fonte",
        "ro-RO": "Sursă",
        "ru-RU": "Источник",
        "sk-SK": "Zdroj",
        "sv-FI": "Källa",
        "sv-SE": "Källa",
        "th-TH": "แหล่งที่มา",
        "tr-TR": "Kaynak",
        "uk-UA": "Джерело",
        "vi-VN": "Nguồn",
        "zh-CN": "来源",
        "zh-SG": "来源",
        "zh-TW": "來源",
      },
      description: "Fallback title for a cited source with no title/URL.",
    },
    "ai-chat-file": {
      defaultValue: "File",
      translations: {
        "ar-AE": "ملف",
        "ar-BH": "ملف",
        "ar-DZ": "ملف",
        "ar-EG": "ملف",
        "ar-IQ": "ملف",
        "ar-JO": "ملف",
        "ar-KW": "ملف",
        "ar-LB": "ملف",
        "ar-LY": "ملف",
        "ar-MA": "ملف",
        "ar-OM": "ملف",
        "ar-QA": "ملف",
        "ar-SA": "ملف",
        "ar-SY": "ملف",
        "ar-TN": "ملف",
        "ar-YE": "ملف",
        "cs-CZ": "Soubor",
        da: "Fil",
        "de-AT": "Datei",
        "de-CH": "Datei",
        "de-DE": "Datei",
        "de-LI": "Datei",
        "de-LU": "Datei",
        "el-GR": "Αρχείο",
        "en-AU": "File",
        "en-BZ": "File",
        "en-CA": "File",
        "en-GB": "File",
        "en-IE": "File",
        "en-JM": "File",
        "en-NZ": "File",
        "en-PH": "File",
        "en-TT": "File",
        "en-US": "File",
        "en-ZA": "File",
        "en-ZW": "File",
        "es-AR": "Archivo",
        "es-BO": "Archivo",
        "es-CL": "Archivo",
        "es-CO": "Archivo",
        "es-CR": "Archivo",
        "es-DO": "Archivo",
        "es-EC": "Archivo",
        "es-ES": "Archivo",
        "es-GT": "Archivo",
        "es-HN": "Archivo",
        "es-MX": "Archivo",
        "es-NI": "Archivo",
        "es-PA": "Archivo",
        "es-PE": "Archivo",
        "es-PR": "Archivo",
        "es-PY": "Archivo",
        "es-SV": "Archivo",
        "es-UY": "Archivo",
        "es-VE": "Archivo",
        "fi-FI": "Tiedosto",
        "fr-BE": "Fichier",
        "fr-CA": "Fichier",
        "fr-CH": "Fichier",
        "fr-FR": "Fichier",
        "fr-LU": "Fichier",
        "fr-MC": "Fichier",
        "he-IL": "קובץ",
        "hi-IN": "फ़ाइल",
        "hu-HU": "Fájl",
        "id-ID": "File",
        "it-CH": "File",
        "it-IT": "File",
        "ja-JP": "ファイル",
        "ko-KR": "파일",
        "nb-NO": "Fil",
        "nl-BE": "Bestand",
        "nl-NL": "Bestand",
        "pl-PL": "Plik",
        "pt-BR": "Arquivo",
        "pt-PT": "Ficheiro",
        "ro-RO": "Fișier",
        "ru-RU": "Файл",
        "sk-SK": "Súbor",
        "sv-FI": "Fil",
        "sv-SE": "Fil",
        "th-TH": "ไฟล์",
        "tr-TR": "Dosya",
        "uk-UA": "Файл",
        "vi-VN": "Tệp",
        "zh-CN": "文件",
        "zh-SG": "文件",
        "zh-TW": "檔案",
      },
      description: "Fallback name for a file part with no filename/URL.",
    },
  },
} satisfies DictionaryRecipe;

export default aiChatUiLabelsActionsRecipe;
