import type { DictionaryRecipe } from "@sitecoreai-labs/sitecoreai-cli/recipe";

/**
 * AI Chat UI Labels — Overlays — a shard of the AI Chat UI Labels phrase library, split so no
 * single Dictionary recipe pushes more item versions than one sandbox can
 * apply. Phrase keys are unchanged; only which recipe authors them differs.
 */
export const aiChatUiLabelsOverlaysRecipe = {
  kind: "dictionary",
  schemaVersion: "1",
  handle: "ai-chat-ui-labels-overlays@1",
  name: "AiChatUiLabelsOverlays",
  displayName: "AI Chat UI Labels — Overlays",
  description:
    "AI Chat dictionary shard — drag-and-drop attach overlay and the new-chat confirm dialog (titles, descriptions, cancel/confirm).",
  primaryLocale: "en",
  phrases: {
    "ai-chat-drop-title": {
      defaultValue: "Drop files to attach",
      translations: {
        "ar-AE": "أفلت الملفات لإرفاقها",
        "ar-BH": "أفلت الملفات لإرفاقها",
        "ar-DZ": "أفلت الملفات لإرفاقها",
        "ar-EG": "أفلت الملفات لإرفاقها",
        "ar-IQ": "أفلت الملفات لإرفاقها",
        "ar-JO": "أفلت الملفات لإرفاقها",
        "ar-KW": "أفلت الملفات لإرفاقها",
        "ar-LB": "أفلت الملفات لإرفاقها",
        "ar-LY": "أفلت الملفات لإرفاقها",
        "ar-MA": "أفلت الملفات لإرفاقها",
        "ar-OM": "أفلت الملفات لإرفاقها",
        "ar-QA": "أفلت الملفات لإرفاقها",
        "ar-SA": "أفلت الملفات لإرفاقها",
        "ar-SY": "أفلت الملفات لإرفاقها",
        "ar-TN": "أفلت الملفات لإرفاقها",
        "ar-YE": "أفلت الملفات لإرفاقها",
        "cs-CZ": "Přetažením připojíte soubory",
        da: "Slip filer for at vedhæfte",
        "de-AT": "Dateien zum Anhängen ablegen",
        "de-CH": "Dateien zum Anhängen ablegen",
        "de-DE": "Dateien zum Anhängen ablegen",
        "de-LI": "Dateien zum Anhängen ablegen",
        "de-LU": "Dateien zum Anhängen ablegen",
        "el-GR": "Αποθέστε αρχεία για επισύναψη",
        "en-AU": "Drop files to attach",
        "en-BZ": "Drop files to attach",
        "en-CA": "Drop files to attach",
        "en-GB": "Drop files to attach",
        "en-IE": "Drop files to attach",
        "en-JM": "Drop files to attach",
        "en-NZ": "Drop files to attach",
        "en-PH": "Drop files to attach",
        "en-TT": "Drop files to attach",
        "en-US": "Drop files to attach",
        "en-ZA": "Drop files to attach",
        "en-ZW": "Drop files to attach",
        "es-AR": "Suelta archivos para adjuntar",
        "es-BO": "Suelta archivos para adjuntar",
        "es-CL": "Suelta archivos para adjuntar",
        "es-CO": "Suelta archivos para adjuntar",
        "es-CR": "Suelta archivos para adjuntar",
        "es-DO": "Suelta archivos para adjuntar",
        "es-EC": "Suelta archivos para adjuntar",
        "es-ES": "Suelta archivos para adjuntar",
        "es-GT": "Suelta archivos para adjuntar",
        "es-HN": "Suelta archivos para adjuntar",
        "es-MX": "Suelta archivos para adjuntar",
        "es-NI": "Suelta archivos para adjuntar",
        "es-PA": "Suelta archivos para adjuntar",
        "es-PE": "Suelta archivos para adjuntar",
        "es-PR": "Suelta archivos para adjuntar",
        "es-PY": "Suelta archivos para adjuntar",
        "es-SV": "Suelta archivos para adjuntar",
        "es-UY": "Suelta archivos para adjuntar",
        "es-VE": "Suelta archivos para adjuntar",
        "fi-FI": "Pudota tiedostot liittääksesi",
        "fr-BE": "Déposez des fichiers à joindre",
        "fr-CA": "Déposez des fichiers à joindre",
        "fr-CH": "Déposez des fichiers à joindre",
        "fr-FR": "Déposez des fichiers à joindre",
        "fr-LU": "Déposez des fichiers à joindre",
        "fr-MC": "Déposez des fichiers à joindre",
        "he-IL": "שחרר קבצים כדי לצרף",
        "hi-IN": "अटैच करने के लिए फ़ाइलें छोड़ें",
        "hu-HU": "Húzd ide a fájlokat a csatoláshoz",
        "id-ID": "Jatuhkan file untuk melampirkan",
        "it-CH": "Trascina i file da allegare",
        "it-IT": "Trascina i file da allegare",
        "ja-JP": "添付するファイルをドロップ",
        "ko-KR": "첨부할 파일을 놓으세요",
        "nb-NO": "Slipp filer for å legge ved",
        "nl-BE": "Sleep bestanden om bij te voegen",
        "nl-NL": "Sleep bestanden om bij te voegen",
        "pl-PL": "Upuść pliki, aby załączyć",
        "pt-BR": "Solte arquivos para anexar",
        "pt-PT": "Largue ficheiros para anexar",
        "ro-RO": "Plasează fișiere pentru a le atașa",
        "ru-RU": "Перетащите файлы для прикрепления",
        "sk-SK": "Presuňte súbory na priloženie",
        "sv-FI": "Släpp filer för att bifoga",
        "sv-SE": "Släpp filer för att bifoga",
        "th-TH": "วางไฟล์เพื่อแนบ",
        "tr-TR": "Eklemek için dosyaları bırakın",
        "uk-UA": "Перетягніть файли, щоб прикріпити",
        "vi-VN": "Thả tệp để đính kèm",
        "zh-CN": "拖放文件以附加",
        "zh-SG": "拖放文件以附加",
        "zh-TW": "拖放檔案以附加",
      },
      description: "Drag-over overlay title.",
    },
    "ai-chat-drop-description": {
      defaultValue: "They'll be added as context for the next turn.",
      translations: {
        "ar-AE": "ستُضاف كسياق للدور التالي.",
        "ar-BH": "ستُضاف كسياق للدور التالي.",
        "ar-DZ": "ستُضاف كسياق للدور التالي.",
        "ar-EG": "ستُضاف كسياق للدور التالي.",
        "ar-IQ": "ستُضاف كسياق للدور التالي.",
        "ar-JO": "ستُضاف كسياق للدور التالي.",
        "ar-KW": "ستُضاف كسياق للدور التالي.",
        "ar-LB": "ستُضاف كسياق للدور التالي.",
        "ar-LY": "ستُضاف كسياق للدور التالي.",
        "ar-MA": "ستُضاف كسياق للدور التالي.",
        "ar-OM": "ستُضاف كسياق للدور التالي.",
        "ar-QA": "ستُضاف كسياق للدور التالي.",
        "ar-SA": "ستُضاف كسياق للدور التالي.",
        "ar-SY": "ستُضاف كسياق للدور التالي.",
        "ar-TN": "ستُضاف كسياق للدور التالي.",
        "ar-YE": "ستُضاف كسياق للدور التالي.",
        "cs-CZ": "Budou přidány jako kontext pro další zprávu.",
        da: "De tilføjes som kontekst til næste tur.",
        "de-AT": "Sie werden als Kontext für die nächste Runde hinzugefügt.",
        "de-CH": "Sie werden als Kontext für die nächste Runde hinzugefügt.",
        "de-DE": "Sie werden als Kontext für die nächste Runde hinzugefügt.",
        "de-LI": "Sie werden als Kontext für die nächste Runde hinzugefügt.",
        "de-LU": "Sie werden als Kontext für die nächste Runde hinzugefügt.",
        "el-GR": "Θα προστεθούν ως πλαίσιο για τον επόμενο γύρο.",
        "en-AU": "They'll be added as context for the next turn.",
        "en-BZ": "They'll be added as context for the next turn.",
        "en-CA": "They'll be added as context for the next turn.",
        "en-GB": "They'll be added as context for the next turn.",
        "en-IE": "They'll be added as context for the next turn.",
        "en-JM": "They'll be added as context for the next turn.",
        "en-NZ": "They'll be added as context for the next turn.",
        "en-PH": "They'll be added as context for the next turn.",
        "en-TT": "They'll be added as context for the next turn.",
        "en-US": "They'll be added as context for the next turn.",
        "en-ZA": "They'll be added as context for the next turn.",
        "en-ZW": "They'll be added as context for the next turn.",
        "es-AR": "Se añadirán como contexto para el siguiente turno.",
        "es-BO": "Se añadirán como contexto para el siguiente turno.",
        "es-CL": "Se añadirán como contexto para el siguiente turno.",
        "es-CO": "Se añadirán como contexto para el siguiente turno.",
        "es-CR": "Se añadirán como contexto para el siguiente turno.",
        "es-DO": "Se añadirán como contexto para el siguiente turno.",
        "es-EC": "Se añadirán como contexto para el siguiente turno.",
        "es-ES": "Se añadirán como contexto para el siguiente turno.",
        "es-GT": "Se añadirán como contexto para el siguiente turno.",
        "es-HN": "Se añadirán como contexto para el siguiente turno.",
        "es-MX": "Se añadirán como contexto para el siguiente turno.",
        "es-NI": "Se añadirán como contexto para el siguiente turno.",
        "es-PA": "Se añadirán como contexto para el siguiente turno.",
        "es-PE": "Se añadirán como contexto para el siguiente turno.",
        "es-PR": "Se añadirán como contexto para el siguiente turno.",
        "es-PY": "Se añadirán como contexto para el siguiente turno.",
        "es-SV": "Se añadirán como contexto para el siguiente turno.",
        "es-UY": "Se añadirán como contexto para el siguiente turno.",
        "es-VE": "Se añadirán como contexto para el siguiente turno.",
        "fi-FI": "Ne lisätään kontekstiksi seuraavaa vuoroa varten.",
        "fr-BE": "Ils seront ajoutés comme contexte pour le prochain tour.",
        "fr-CA": "Ils seront ajoutés comme contexte pour le prochain tour.",
        "fr-CH": "Ils seront ajoutés comme contexte pour le prochain tour.",
        "fr-FR": "Ils seront ajoutés comme contexte pour le prochain tour.",
        "fr-LU": "Ils seront ajoutés comme contexte pour le prochain tour.",
        "fr-MC": "Ils seront ajoutés comme contexte pour le prochain tour.",
        "he-IL": "הם יתווספו כהקשר לתור הבא.",
        "hi-IN": "इन्हें अगली बातचीत के लिए संदर्भ के रूप में जोड़ा जाएगा.",
        "hu-HU": "A következő körhöz kontextusként lesznek hozzáadva.",
        "id-ID":
          "Mereka akan ditambahkan sebagai konteks untuk giliran berikutnya.",
        "it-CH": "Verranno aggiunti come contesto per il turno successivo.",
        "it-IT": "Verranno aggiunti come contesto per il turno successivo.",
        "ja-JP": "次のやり取りのコンテキストとして追加されます。",
        "ko-KR": "다음 대화의 컨텍스트로 추가됩니다.",
        "nb-NO": "De legges til som kontekst for neste tur.",
        "nl-BE": "Ze worden toegevoegd als context voor de volgende beurt.",
        "nl-NL": "Ze worden toegevoegd als context voor de volgende beurt.",
        "pl-PL": "Zostaną dodane jako kontekst do następnej wiadomości.",
        "pt-BR": "Eles serão adicionados como contexto para o próximo turno.",
        "pt-PT": "Serão adicionados como contexto para o próximo turno.",
        "ro-RO": "Vor fi adăugate ca context pentru următoarea interacțiune.",
        "ru-RU": "Они будут добавлены как контекст для следующего хода.",
        "sk-SK": "Pridajú sa ako kontext pre ďalšiu správu.",
        "sv-FI": "De läggs till som kontext för nästa tur.",
        "sv-SE": "De läggs till som kontext för nästa tur.",
        "th-TH": "จะถูกเพิ่มเป็นบริบทสำหรับการสนทนาครั้งถัดไป",
        "tr-TR": "Sonraki tur için bağlam olarak eklenecekler.",
        "uk-UA": "Їх буде додано як контекст для наступного ходу.",
        "vi-VN": "Chúng sẽ được thêm làm ngữ cảnh cho lượt tiếp theo.",
        "zh-CN": "它们将作为下一轮的上下文添加。",
        "zh-SG": "它们将作为下一轮的上下文添加。",
        "zh-TW": "它們將作為下一輪的上下文加入。",
      },
      description: "Drag-over overlay subtitle.",
    },
    "ai-chat-discard-title": {
      defaultValue: "Discard this conversation?",
      translations: {
        "ar-AE": "تجاهل هذه المحادثة؟",
        "ar-BH": "تجاهل هذه المحادثة؟",
        "ar-DZ": "تجاهل هذه المحادثة؟",
        "ar-EG": "تجاهل هذه المحادثة؟",
        "ar-IQ": "تجاهل هذه المحادثة؟",
        "ar-JO": "تجاهل هذه المحادثة؟",
        "ar-KW": "تجاهل هذه المحادثة؟",
        "ar-LB": "تجاهل هذه المحادثة؟",
        "ar-LY": "تجاهل هذه المحادثة؟",
        "ar-MA": "تجاهل هذه المحادثة؟",
        "ar-OM": "تجاهل هذه المحادثة؟",
        "ar-QA": "تجاهل هذه المحادثة؟",
        "ar-SA": "تجاهل هذه المحادثة؟",
        "ar-SY": "تجاهل هذه المحادثة؟",
        "ar-TN": "تجاهل هذه المحادثة؟",
        "ar-YE": "تجاهل هذه المحادثة؟",
        "cs-CZ": "Zahodit tuto konverzaci?",
        da: "Kassér denne samtale?",
        "de-AT": "Diese Unterhaltung verwerfen?",
        "de-CH": "Diese Unterhaltung verwerfen?",
        "de-DE": "Diese Unterhaltung verwerfen?",
        "de-LI": "Diese Unterhaltung verwerfen?",
        "de-LU": "Diese Unterhaltung verwerfen?",
        "el-GR": "Απόρριψη αυτής της συνομιλίας;",
        "en-AU": "Discard this conversation?",
        "en-BZ": "Discard this conversation?",
        "en-CA": "Discard this conversation?",
        "en-GB": "Discard this conversation?",
        "en-IE": "Discard this conversation?",
        "en-JM": "Discard this conversation?",
        "en-NZ": "Discard this conversation?",
        "en-PH": "Discard this conversation?",
        "en-TT": "Discard this conversation?",
        "en-US": "Discard this conversation?",
        "en-ZA": "Discard this conversation?",
        "en-ZW": "Discard this conversation?",
        "es-AR": "¿Descartar esta conversación?",
        "es-BO": "¿Descartar esta conversación?",
        "es-CL": "¿Descartar esta conversación?",
        "es-CO": "¿Descartar esta conversación?",
        "es-CR": "¿Descartar esta conversación?",
        "es-DO": "¿Descartar esta conversación?",
        "es-EC": "¿Descartar esta conversación?",
        "es-ES": "¿Descartar esta conversación?",
        "es-GT": "¿Descartar esta conversación?",
        "es-HN": "¿Descartar esta conversación?",
        "es-MX": "¿Descartar esta conversación?",
        "es-NI": "¿Descartar esta conversación?",
        "es-PA": "¿Descartar esta conversación?",
        "es-PE": "¿Descartar esta conversación?",
        "es-PR": "¿Descartar esta conversación?",
        "es-PY": "¿Descartar esta conversación?",
        "es-SV": "¿Descartar esta conversación?",
        "es-UY": "¿Descartar esta conversación?",
        "es-VE": "¿Descartar esta conversación?",
        "fi-FI": "Hylätäänkö tämä keskustelu?",
        "fr-BE": "Abandonner cette conversation ?",
        "fr-CA": "Abandonner cette conversation ?",
        "fr-CH": "Abandonner cette conversation ?",
        "fr-FR": "Abandonner cette conversation ?",
        "fr-LU": "Abandonner cette conversation ?",
        "fr-MC": "Abandonner cette conversation ?",
        "he-IL": "לבטל את השיחה הזו?",
        "hi-IN": "इस बातचीत को छोड़ें?",
        "hu-HU": "Elveti ezt a beszélgetést?",
        "id-ID": "Buang percakapan ini?",
        "it-CH": "Eliminare questa conversazione?",
        "it-IT": "Eliminare questa conversazione?",
        "ja-JP": "この会話を破棄しますか？",
        "ko-KR": "이 대화를 삭제할까요?",
        "nb-NO": "Forkaste denne samtalen?",
        "nl-BE": "Dit gesprek verwijderen?",
        "nl-NL": "Dit gesprek verwijderen?",
        "pl-PL": "Odrzucić tę rozmowę?",
        "pt-BR": "Descartar esta conversa?",
        "pt-PT": "Descartar esta conversa?",
        "ro-RO": "Renunți la această conversație?",
        "ru-RU": "Удалить этот разговор?",
        "sk-SK": "Zahodiť túto konverzáciu?",
        "sv-FI": "Kassera den här konversationen?",
        "sv-SE": "Kassera den här konversationen?",
        "th-TH": "ละทิ้งการสนทนานี้หรือไม่?",
        "tr-TR": "Bu konuşma silinsin mi?",
        "uk-UA": "Відхилити цю розмову?",
        "vi-VN": "Bỏ cuộc trò chuyện này?",
        "zh-CN": "放弃此对话？",
        "zh-SG": "放弃此对话？",
        "zh-TW": "放棄此對話？",
      },
      description: "New-chat confirm dialog title.",
    },
    "ai-chat-discard-description": {
      defaultValue:
        "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
      translations: {
        "ar-AE":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-BH":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-DZ":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-EG":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-IQ":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-JO":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-KW":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-LB":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-LY":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-MA":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-OM":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-QA":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-SA":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-SY":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-TN":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "ar-YE":
          "سيؤدي هذا إلى مسح كل رسالة في الدردشة الحالية. لن يُعاد تحميل الصفحة، لكن كل ما ناقشته هنا سيختفي.",
        "cs-CZ":
          "Tím se vymažou všechny zprávy v aktuálním chatu. Stránka se nenačte znovu, ale vše, co jste zde probrali, zmizí.",
        da: "Dette rydder alle beskeder i den aktuelle chat. Siden genindlæses ikke, men alt, du har drøftet her, forsvinder.",
        "de-AT":
          "Dadurch werden alle Nachrichten im aktuellen Chat gelöscht. Die Seite wird nicht neu geladen, aber alles, was Sie hier besprochen haben, geht verloren.",
        "de-CH":
          "Dadurch werden alle Nachrichten im aktuellen Chat gelöscht. Die Seite wird nicht neu geladen, aber alles, was Sie hier besprochen haben, geht verloren.",
        "de-DE":
          "Dadurch werden alle Nachrichten im aktuellen Chat gelöscht. Die Seite wird nicht neu geladen, aber alles, was Sie hier besprochen haben, geht verloren.",
        "de-LI":
          "Dadurch werden alle Nachrichten im aktuellen Chat gelöscht. Die Seite wird nicht neu geladen, aber alles, was Sie hier besprochen haben, geht verloren.",
        "de-LU":
          "Dadurch werden alle Nachrichten im aktuellen Chat gelöscht. Die Seite wird nicht neu geladen, aber alles, was Sie hier besprochen haben, geht verloren.",
        "el-GR":
          "Αυτό θα διαγράψει κάθε μήνυμα στην τρέχουσα συνομιλία. Η σελίδα δεν θα φορτωθεί ξανά, αλλά ό,τι συζητήσατε εδώ θα χαθεί.",
        "en-AU":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-BZ":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-CA":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-GB":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-IE":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-JM":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-NZ":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-PH":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-TT":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-US":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-ZA":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "en-ZW":
          "This will clear every message in the current chat. The page won't reload, but anything you've discussed here will be gone.",
        "es-AR":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-BO":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-CL":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-CO":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-CR":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-DO":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-EC":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-ES":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-GT":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-HN":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-MX":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-NI":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-PA":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-PE":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-PR":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-PY":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-SV":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-UY":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "es-VE":
          "Esto borrará todos los mensajes del chat actual. La página no se recargará, pero se perderá todo lo que hayas hablado aquí.",
        "fi-FI":
          "Tämä tyhjentää kaikki nykyisen keskustelun viestit. Sivua ei ladata uudelleen, mutta kaikki tässä käsitelty katoaa.",
        "fr-BE":
          "Cela effacera tous les messages de la conversation en cours. La page ne sera pas rechargée, mais tout ce dont vous avez discuté ici sera perdu.",
        "fr-CA":
          "Cela effacera tous les messages de la conversation en cours. La page ne sera pas rechargée, mais tout ce dont vous avez discuté ici sera perdu.",
        "fr-CH":
          "Cela effacera tous les messages de la conversation en cours. La page ne sera pas rechargée, mais tout ce dont vous avez discuté ici sera perdu.",
        "fr-FR":
          "Cela effacera tous les messages de la conversation en cours. La page ne sera pas rechargée, mais tout ce dont vous avez discuté ici sera perdu.",
        "fr-LU":
          "Cela effacera tous les messages de la conversation en cours. La page ne sera pas rechargée, mais tout ce dont vous avez discuté ici sera perdu.",
        "fr-MC":
          "Cela effacera tous les messages de la conversation en cours. La page ne sera pas rechargée, mais tout ce dont vous avez discuté ici sera perdu.",
        "he-IL":
          "פעולה זו תמחק כל הודעה בצ'אט הנוכחי. הדף לא ייטען מחדש, אך כל מה שדנתם בו כאן ייעלם.",
        "hi-IN":
          "इससे मौजूदा चैट के सभी संदेश साफ़ हो जाएँगे. पेज रीलोड नहीं होगा, लेकिन यहाँ आपने जो चर्चा की है वह चली जाएगी.",
        "hu-HU":
          "Ez törli az aktuális csevegés összes üzenetét. Az oldal nem töltődik újra, de minden, amit itt megbeszélt, elveszik.",
        "id-ID":
          "Ini akan menghapus setiap pesan di obrolan saat ini. Halaman tidak akan dimuat ulang, tetapi apa pun yang Anda bahas di sini akan hilang.",
        "it-CH":
          "Questa operazione cancellerà tutti i messaggi della chat corrente. La pagina non verrà ricaricata, ma tutto ciò di cui hai discusso qui andrà perso.",
        "it-IT":
          "Questa operazione cancellerà tutti i messaggi della chat corrente. La pagina non verrà ricaricata, ma tutto ciò di cui hai discusso qui andrà perso.",
        "ja-JP":
          "現在のチャットのすべてのメッセージが消去されます。ページは再読み込みされませんが、ここで話した内容はすべて失われます。",
        "ko-KR":
          "현재 채팅의 모든 메시지가 지워집니다. 페이지는 새로 고쳐지지 않지만, 여기서 나눈 내용은 사라집니다.",
        "nb-NO":
          "Dette fjerner alle meldinger i den gjeldende chatten. Siden lastes ikke på nytt, men alt du har diskutert her, forsvinner.",
        "nl-BE":
          "Hiermee worden alle berichten in de huidige chat gewist. De pagina wordt niet opnieuw geladen, maar alles wat je hier hebt besproken, is weg.",
        "nl-NL":
          "Hiermee worden alle berichten in de huidige chat gewist. De pagina wordt niet opnieuw geladen, maar alles wat je hier hebt besproken, is weg.",
        "pl-PL":
          "Spowoduje to wyczyszczenie wszystkich wiadomości w bieżącym czacie. Strona nie zostanie przeładowana, ale wszystko, co tu omówiłeś, zniknie.",
        "pt-BR":
          "Isso apagará todas as mensagens do chat atual. A página não será recarregada, mas tudo o que você discutiu aqui será perdido.",
        "pt-PT":
          "Isto irá apagar todas as mensagens do chat atual. A página não será recarregada, mas tudo o que discutiu aqui será perdido.",
        "ro-RO":
          "Aceasta va șterge fiecare mesaj din chatul curent. Pagina nu se va reîncărca, dar tot ce ai discutat aici se va pierde.",
        "ru-RU":
          "Это удалит все сообщения в текущем чате. Страница не перезагрузится, но всё, что вы здесь обсуждали, будет потеряно.",
        "sk-SK":
          "Týmto sa vymažú všetky správy v aktuálnom chate. Stránka sa znova nenačíta, ale všetko, čo ste tu prebrali, zmizne.",
        "sv-FI":
          "Detta rensar alla meddelanden i den aktuella chatten. Sidan laddas inte om, men allt du har diskuterat här försvinner.",
        "sv-SE":
          "Detta rensar alla meddelanden i den aktuella chatten. Sidan laddas inte om, men allt du har diskuterat här försvinner.",
        "th-TH":
          "การดำเนินการนี้จะล้างข้อความทั้งหมดในแชทปัจจุบัน หน้าจะไม่โหลดใหม่ แต่ทุกสิ่งที่คุณพูดคุยที่นี่จะหายไป",
        "tr-TR":
          "Bu, mevcut sohbetteki tüm mesajları temizler. Sayfa yeniden yüklenmez, ancak burada konuştuğunuz her şey kaybolur.",
        "uk-UA":
          "Це очистить усі повідомлення в поточному чаті. Сторінка не перезавантажиться, але все, що ви тут обговорювали, буде втрачено.",
        "vi-VN":
          "Thao tác này sẽ xóa mọi tin nhắn trong cuộc trò chuyện hiện tại. Trang sẽ không tải lại, nhưng mọi thứ bạn đã trao đổi ở đây sẽ mất.",
        "zh-CN":
          "这将清除当前聊天中的所有消息。页面不会重新加载，但你在此讨论的所有内容都将消失。",
        "zh-SG":
          "这将清除当前聊天中的所有消息。页面不会重新加载，但你在此讨论的所有内容都将消失。",
        "zh-TW":
          "這將清除目前聊天中的所有訊息。頁面不會重新載入，但你在此討論的所有內容都將消失。",
      },
      description: "New-chat confirm dialog body.",
    },
    "ai-chat-discard-cancel": {
      defaultValue: "Keep chatting",
      translations: {
        "ar-AE": "متابعة المحادثة",
        "ar-BH": "متابعة المحادثة",
        "ar-DZ": "متابعة المحادثة",
        "ar-EG": "متابعة المحادثة",
        "ar-IQ": "متابعة المحادثة",
        "ar-JO": "متابعة المحادثة",
        "ar-KW": "متابعة المحادثة",
        "ar-LB": "متابعة المحادثة",
        "ar-LY": "متابعة المحادثة",
        "ar-MA": "متابعة المحادثة",
        "ar-OM": "متابعة المحادثة",
        "ar-QA": "متابعة المحادثة",
        "ar-SA": "متابعة المحادثة",
        "ar-SY": "متابعة المحادثة",
        "ar-TN": "متابعة المحادثة",
        "ar-YE": "متابعة المحادثة",
        "cs-CZ": "Pokračovat v chatu",
        da: "Fortsæt med at chatte",
        "de-AT": "Weiter chatten",
        "de-CH": "Weiter chatten",
        "de-DE": "Weiter chatten",
        "de-LI": "Weiter chatten",
        "de-LU": "Weiter chatten",
        "el-GR": "Συνέχεια συνομιλίας",
        "en-AU": "Keep chatting",
        "en-BZ": "Keep chatting",
        "en-CA": "Keep chatting",
        "en-GB": "Keep chatting",
        "en-IE": "Keep chatting",
        "en-JM": "Keep chatting",
        "en-NZ": "Keep chatting",
        "en-PH": "Keep chatting",
        "en-TT": "Keep chatting",
        "en-US": "Keep chatting",
        "en-ZA": "Keep chatting",
        "en-ZW": "Keep chatting",
        "es-AR": "Seguir chateando",
        "es-BO": "Seguir chateando",
        "es-CL": "Seguir chateando",
        "es-CO": "Seguir chateando",
        "es-CR": "Seguir chateando",
        "es-DO": "Seguir chateando",
        "es-EC": "Seguir chateando",
        "es-ES": "Seguir chateando",
        "es-GT": "Seguir chateando",
        "es-HN": "Seguir chateando",
        "es-MX": "Seguir chateando",
        "es-NI": "Seguir chateando",
        "es-PA": "Seguir chateando",
        "es-PE": "Seguir chateando",
        "es-PR": "Seguir chateando",
        "es-PY": "Seguir chateando",
        "es-SV": "Seguir chateando",
        "es-UY": "Seguir chateando",
        "es-VE": "Seguir chateando",
        "fi-FI": "Jatka keskustelua",
        "fr-BE": "Continuer la conversation",
        "fr-CA": "Continuer la conversation",
        "fr-CH": "Continuer la conversation",
        "fr-FR": "Continuer la conversation",
        "fr-LU": "Continuer la conversation",
        "fr-MC": "Continuer la conversation",
        "he-IL": "להמשיך לשוחח",
        "hi-IN": "चैट जारी रखें",
        "hu-HU": "Csevegés folytatása",
        "id-ID": "Lanjutkan mengobrol",
        "it-CH": "Continua a chattare",
        "it-IT": "Continua a chattare",
        "ja-JP": "チャットを続ける",
        "ko-KR": "계속 채팅하기",
        "nb-NO": "Fortsett å chatte",
        "nl-BE": "Blijf chatten",
        "nl-NL": "Blijf chatten",
        "pl-PL": "Kontynuuj czat",
        "pt-BR": "Continuar conversando",
        "pt-PT": "Continuar a conversar",
        "ro-RO": "Continuă conversația",
        "ru-RU": "Продолжить чат",
        "sk-SK": "Pokračovať v chate",
        "sv-FI": "Fortsätt chatta",
        "sv-SE": "Fortsätt chatta",
        "th-TH": "แชทต่อ",
        "tr-TR": "Sohbete devam et",
        "uk-UA": "Продовжити чат",
        "vi-VN": "Tiếp tục trò chuyện",
        "zh-CN": "继续聊天",
        "zh-SG": "继续聊天",
        "zh-TW": "繼續聊天",
      },
      description: "New-chat confirm dialog cancel button.",
    },
    "ai-chat-discard-confirm": {
      defaultValue: "Start a new chat",
      translations: {
        "ar-AE": "بدء محادثة جديدة",
        "ar-BH": "بدء محادثة جديدة",
        "ar-DZ": "بدء محادثة جديدة",
        "ar-EG": "بدء محادثة جديدة",
        "ar-IQ": "بدء محادثة جديدة",
        "ar-JO": "بدء محادثة جديدة",
        "ar-KW": "بدء محادثة جديدة",
        "ar-LB": "بدء محادثة جديدة",
        "ar-LY": "بدء محادثة جديدة",
        "ar-MA": "بدء محادثة جديدة",
        "ar-OM": "بدء محادثة جديدة",
        "ar-QA": "بدء محادثة جديدة",
        "ar-SA": "بدء محادثة جديدة",
        "ar-SY": "بدء محادثة جديدة",
        "ar-TN": "بدء محادثة جديدة",
        "ar-YE": "بدء محادثة جديدة",
        "cs-CZ": "Zahájit nový chat",
        da: "Start en ny chat",
        "de-AT": "Neuen Chat starten",
        "de-CH": "Neuen Chat starten",
        "de-DE": "Neuen Chat starten",
        "de-LI": "Neuen Chat starten",
        "de-LU": "Neuen Chat starten",
        "el-GR": "Έναρξη νέας συνομιλίας",
        "en-AU": "Start a new chat",
        "en-BZ": "Start a new chat",
        "en-CA": "Start a new chat",
        "en-GB": "Start a new chat",
        "en-IE": "Start a new chat",
        "en-JM": "Start a new chat",
        "en-NZ": "Start a new chat",
        "en-PH": "Start a new chat",
        "en-TT": "Start a new chat",
        "en-US": "Start a new chat",
        "en-ZA": "Start a new chat",
        "en-ZW": "Start a new chat",
        "es-AR": "Iniciar una nueva conversación",
        "es-BO": "Iniciar una nueva conversación",
        "es-CL": "Iniciar una nueva conversación",
        "es-CO": "Iniciar una nueva conversación",
        "es-CR": "Iniciar una nueva conversación",
        "es-DO": "Iniciar una nueva conversación",
        "es-EC": "Iniciar una nueva conversación",
        "es-ES": "Iniciar una nueva conversación",
        "es-GT": "Iniciar una nueva conversación",
        "es-HN": "Iniciar una nueva conversación",
        "es-MX": "Iniciar una nueva conversación",
        "es-NI": "Iniciar una nueva conversación",
        "es-PA": "Iniciar una nueva conversación",
        "es-PE": "Iniciar una nueva conversación",
        "es-PR": "Iniciar una nueva conversación",
        "es-PY": "Iniciar una nueva conversación",
        "es-SV": "Iniciar una nueva conversación",
        "es-UY": "Iniciar una nueva conversación",
        "es-VE": "Iniciar una nueva conversación",
        "fi-FI": "Aloita uusi keskustelu",
        "fr-BE": "Démarrer une nouvelle conversation",
        "fr-CA": "Démarrer une nouvelle conversation",
        "fr-CH": "Démarrer une nouvelle conversation",
        "fr-FR": "Démarrer une nouvelle conversation",
        "fr-LU": "Démarrer une nouvelle conversation",
        "fr-MC": "Démarrer une nouvelle conversation",
        "he-IL": "התחלת צ'אט חדש",
        "hi-IN": "नई चैट शुरू करें",
        "hu-HU": "Új csevegés indítása",
        "id-ID": "Mulai obrolan baru",
        "it-CH": "Avvia una nuova chat",
        "it-IT": "Avvia una nuova chat",
        "ja-JP": "新しいチャットを開始",
        "ko-KR": "새 채팅 시작",
        "nb-NO": "Start en ny chat",
        "nl-BE": "Een nieuwe chat starten",
        "nl-NL": "Een nieuwe chat starten",
        "pl-PL": "Rozpocznij nowy czat",
        "pt-BR": "Iniciar uma nova conversa",
        "pt-PT": "Iniciar uma nova conversa",
        "ro-RO": "Începe un chat nou",
        "ru-RU": "Начать новый чат",
        "sk-SK": "Začať nový chat",
        "sv-FI": "Starta en ny chatt",
        "sv-SE": "Starta en ny chatt",
        "th-TH": "เริ่มแชทใหม่",
        "tr-TR": "Yeni bir sohbet başlat",
        "uk-UA": "Почати новий чат",
        "vi-VN": "Bắt đầu cuộc trò chuyện mới",
        "zh-CN": "开始新对话",
        "zh-SG": "开始新对话",
        "zh-TW": "開始新對話",
      },
      description: "New-chat confirm dialog confirm button.",
    },
  },
} satisfies DictionaryRecipe;

export default aiChatUiLabelsOverlaysRecipe;
