import type { DictionaryRecipe } from "@sitecoreai-labs/sitecoreai-cli/recipe";

/**
 * AI Chat UI Labels — Conversation — a shard of the AI Chat UI Labels phrase library, split so no
 * single Dictionary recipe pushes more item versions than one sandbox can
 * apply. Phrase keys are unchanged; only which recipe authors them differs.
 */
export const aiChatUiLabelsConversationRecipe = {
  kind: "dictionary",
  schemaVersion: "1",
  handle: "ai-chat-ui-labels-conversation@1",
  name: "AiChatUiLabelsConversation",
  displayName: "AI Chat UI Labels — Conversation",
  description:
    "AI Chat dictionary shard — frame & chrome: header new-chat/close buttons, floating launcher, message author labels, and the hero history toggle. Keep the single-brace {title} token in ai-chat-open-launcher intact in every translation.",
  primaryLocale: "en",
  phrases: {
    "ai-chat-new-chat": {
      defaultValue: "New chat",
      translations: {
        "ar-AE": "محادثة جديدة",
        "ar-BH": "محادثة جديدة",
        "ar-DZ": "محادثة جديدة",
        "ar-EG": "محادثة جديدة",
        "ar-IQ": "محادثة جديدة",
        "ar-JO": "محادثة جديدة",
        "ar-KW": "محادثة جديدة",
        "ar-LB": "محادثة جديدة",
        "ar-LY": "محادثة جديدة",
        "ar-MA": "محادثة جديدة",
        "ar-OM": "محادثة جديدة",
        "ar-QA": "محادثة جديدة",
        "ar-SA": "محادثة جديدة",
        "ar-SY": "محادثة جديدة",
        "ar-TN": "محادثة جديدة",
        "ar-YE": "محادثة جديدة",
        "cs-CZ": "Nový chat",
        da: "Ny chat",
        "de-AT": "Neuer Chat",
        "de-CH": "Neuer Chat",
        "de-DE": "Neuer Chat",
        "de-LI": "Neuer Chat",
        "de-LU": "Neuer Chat",
        "el-GR": "Νέα συνομιλία",
        "en-AU": "New chat",
        "en-BZ": "New chat",
        "en-CA": "New chat",
        "en-GB": "New chat",
        "en-IE": "New chat",
        "en-JM": "New chat",
        "en-NZ": "New chat",
        "en-PH": "New chat",
        "en-TT": "New chat",
        "en-US": "New chat",
        "en-ZA": "New chat",
        "en-ZW": "New chat",
        "es-AR": "Nueva conversación",
        "es-BO": "Nueva conversación",
        "es-CL": "Nueva conversación",
        "es-CO": "Nueva conversación",
        "es-CR": "Nueva conversación",
        "es-DO": "Nueva conversación",
        "es-EC": "Nueva conversación",
        "es-ES": "Nueva conversación",
        "es-GT": "Nueva conversación",
        "es-HN": "Nueva conversación",
        "es-MX": "Nueva conversación",
        "es-NI": "Nueva conversación",
        "es-PA": "Nueva conversación",
        "es-PE": "Nueva conversación",
        "es-PR": "Nueva conversación",
        "es-PY": "Nueva conversación",
        "es-SV": "Nueva conversación",
        "es-UY": "Nueva conversación",
        "es-VE": "Nueva conversación",
        "fi-FI": "Uusi keskustelu",
        "fr-BE": "Nouvelle conversation",
        "fr-CA": "Nouvelle conversation",
        "fr-CH": "Nouvelle conversation",
        "fr-FR": "Nouvelle conversation",
        "fr-LU": "Nouvelle conversation",
        "fr-MC": "Nouvelle conversation",
        "he-IL": "צ'אט חדש",
        "hi-IN": "नई चैट",
        "hu-HU": "Új csevegés",
        "id-ID": "Obrolan baru",
        "it-CH": "Nuova chat",
        "it-IT": "Nuova chat",
        "ja-JP": "新しいチャット",
        "ko-KR": "새 채팅",
        "nb-NO": "Ny chat",
        "nl-BE": "Nieuwe chat",
        "nl-NL": "Nieuwe chat",
        "pl-PL": "Nowy czat",
        "pt-BR": "Nova conversa",
        "pt-PT": "Nova conversa",
        "ro-RO": "Chat nou",
        "ru-RU": "Новый чат",
        "sk-SK": "Nový chat",
        "sv-FI": "Ny chatt",
        "sv-SE": "Ny chatt",
        "th-TH": "แชทใหม่",
        "tr-TR": "Yeni sohbet",
        "uk-UA": "Новий чат",
        "vi-VN": "Trò chuyện mới",
        "zh-CN": "新对话",
        "zh-SG": "新对话",
        "zh-TW": "新對話",
      },
      description: "Tooltip for the header new-chat button.",
    },
    "ai-chat-new-chat-aria": {
      defaultValue: "Start a new chat",
      translations: {
        "ar-AE": "بدء محادثة جديدة",
        "ar-BH": "بدء محادثة جديدة",
        "ar-DZ": "بدء محادثة جديدة",
        "ar-EG": "بدء محادثة جديدة",
        "ar-IQ": "بدء محادثة جديدة",
        "ar-JO": "بدء محادثة جديدة",
        "ar-KW": "بدء محادثة جديدة",
        "ar-LB": "بدء محادثة جديدة",
        "ar-LY": "بدء محادثة جديدة",
        "ar-MA": "بدء محادثة جديدة",
        "ar-OM": "بدء محادثة جديدة",
        "ar-QA": "بدء محادثة جديدة",
        "ar-SA": "بدء محادثة جديدة",
        "ar-SY": "بدء محادثة جديدة",
        "ar-TN": "بدء محادثة جديدة",
        "ar-YE": "بدء محادثة جديدة",
        "cs-CZ": "Zahájit nový chat",
        da: "Start en ny chat",
        "de-AT": "Neuen Chat starten",
        "de-CH": "Neuen Chat starten",
        "de-DE": "Neuen Chat starten",
        "de-LI": "Neuen Chat starten",
        "de-LU": "Neuen Chat starten",
        "el-GR": "Έναρξη νέας συνομιλίας",
        "en-AU": "Start a new chat",
        "en-BZ": "Start a new chat",
        "en-CA": "Start a new chat",
        "en-GB": "Start a new chat",
        "en-IE": "Start a new chat",
        "en-JM": "Start a new chat",
        "en-NZ": "Start a new chat",
        "en-PH": "Start a new chat",
        "en-TT": "Start a new chat",
        "en-US": "Start a new chat",
        "en-ZA": "Start a new chat",
        "en-ZW": "Start a new chat",
        "es-AR": "Iniciar una nueva conversación",
        "es-BO": "Iniciar una nueva conversación",
        "es-CL": "Iniciar una nueva conversación",
        "es-CO": "Iniciar una nueva conversación",
        "es-CR": "Iniciar una nueva conversación",
        "es-DO": "Iniciar una nueva conversación",
        "es-EC": "Iniciar una nueva conversación",
        "es-ES": "Iniciar una nueva conversación",
        "es-GT": "Iniciar una nueva conversación",
        "es-HN": "Iniciar una nueva conversación",
        "es-MX": "Iniciar una nueva conversación",
        "es-NI": "Iniciar una nueva conversación",
        "es-PA": "Iniciar una nueva conversación",
        "es-PE": "Iniciar una nueva conversación",
        "es-PR": "Iniciar una nueva conversación",
        "es-PY": "Iniciar una nueva conversación",
        "es-SV": "Iniciar una nueva conversación",
        "es-UY": "Iniciar una nueva conversación",
        "es-VE": "Iniciar una nueva conversación",
        "fi-FI": "Aloita uusi keskustelu",
        "fr-BE": "Démarrer une nouvelle conversation",
        "fr-CA": "Démarrer une nouvelle conversation",
        "fr-CH": "Démarrer une nouvelle conversation",
        "fr-FR": "Démarrer une nouvelle conversation",
        "fr-LU": "Démarrer une nouvelle conversation",
        "fr-MC": "Démarrer une nouvelle conversation",
        "he-IL": "התחלת צ'אט חדש",
        "hi-IN": "नई चैट शुरू करें",
        "hu-HU": "Új csevegés indítása",
        "id-ID": "Mulai obrolan baru",
        "it-CH": "Avvia una nuova chat",
        "it-IT": "Avvia una nuova chat",
        "ja-JP": "新しいチャットを開始",
        "ko-KR": "새 채팅 시작",
        "nb-NO": "Start en ny chat",
        "nl-BE": "Een nieuwe chat starten",
        "nl-NL": "Een nieuwe chat starten",
        "pl-PL": "Rozpocznij nowy czat",
        "pt-BR": "Iniciar uma nova conversa",
        "pt-PT": "Iniciar uma nova conversa",
        "ro-RO": "Începe un chat nou",
        "ru-RU": "Начать новый чат",
        "sk-SK": "Začať nový chat",
        "sv-FI": "Starta en ny chatt",
        "sv-SE": "Starta en ny chatt",
        "th-TH": "เริ่มแชทใหม่",
        "tr-TR": "Yeni bir sohbet başlat",
        "uk-UA": "Почати новий чат",
        "vi-VN": "Bắt đầu cuộc trò chuyện mới",
        "zh-CN": "开始新对话",
        "zh-SG": "开始新对话",
        "zh-TW": "開始新對話",
      },
      description: "Aria-label for the header new-chat button.",
    },
    "ai-chat-close": {
      defaultValue: "Close AI chat",
      translations: {
        "ar-AE": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-BH": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-DZ": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-EG": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-IQ": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-JO": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-KW": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-LB": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-LY": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-MA": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-OM": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-QA": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-SA": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-SY": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-TN": "إغلاق دردشة الذكاء الاصطناعي",
        "ar-YE": "إغلاق دردشة الذكاء الاصطناعي",
        "cs-CZ": "Zavřít AI chat",
        da: "Luk AI-chat",
        "de-AT": "KI-Chat schließen",
        "de-CH": "KI-Chat schließen",
        "de-DE": "KI-Chat schließen",
        "de-LI": "KI-Chat schließen",
        "de-LU": "KI-Chat schließen",
        "el-GR": "Κλείσιμο συνομιλίας AI",
        "en-AU": "Close AI chat",
        "en-BZ": "Close AI chat",
        "en-CA": "Close AI chat",
        "en-GB": "Close AI chat",
        "en-IE": "Close AI chat",
        "en-JM": "Close AI chat",
        "en-NZ": "Close AI chat",
        "en-PH": "Close AI chat",
        "en-TT": "Close AI chat",
        "en-US": "Close AI chat",
        "en-ZA": "Close AI chat",
        "en-ZW": "Close AI chat",
        "es-AR": "Cerrar el chat de IA",
        "es-BO": "Cerrar el chat de IA",
        "es-CL": "Cerrar el chat de IA",
        "es-CO": "Cerrar el chat de IA",
        "es-CR": "Cerrar el chat de IA",
        "es-DO": "Cerrar el chat de IA",
        "es-EC": "Cerrar el chat de IA",
        "es-ES": "Cerrar el chat de IA",
        "es-GT": "Cerrar el chat de IA",
        "es-HN": "Cerrar el chat de IA",
        "es-MX": "Cerrar el chat de IA",
        "es-NI": "Cerrar el chat de IA",
        "es-PA": "Cerrar el chat de IA",
        "es-PE": "Cerrar el chat de IA",
        "es-PR": "Cerrar el chat de IA",
        "es-PY": "Cerrar el chat de IA",
        "es-SV": "Cerrar el chat de IA",
        "es-UY": "Cerrar el chat de IA",
        "es-VE": "Cerrar el chat de IA",
        "fi-FI": "Sulje tekoälychat",
        "fr-BE": "Fermer le chat IA",
        "fr-CA": "Fermer le chat IA",
        "fr-CH": "Fermer le chat IA",
        "fr-FR": "Fermer le chat IA",
        "fr-LU": "Fermer le chat IA",
        "fr-MC": "Fermer le chat IA",
        "he-IL": "סגירת צ'אט ה-AI",
        "hi-IN": "AI चैट बंद करें",
        "hu-HU": "AI-csevegés bezárása",
        "id-ID": "Tutup obrolan AI",
        "it-CH": "Chiudi la chat IA",
        "it-IT": "Chiudi la chat IA",
        "ja-JP": "AIチャットを閉じる",
        "ko-KR": "AI 채팅 닫기",
        "nb-NO": "Lukk AI-chat",
        "nl-BE": "AI-chat sluiten",
        "nl-NL": "AI-chat sluiten",
        "pl-PL": "Zamknij czat AI",
        "pt-BR": "Fechar o chat de IA",
        "pt-PT": "Fechar o chat de IA",
        "ro-RO": "Închide chatul AI",
        "ru-RU": "Закрыть ИИ-чат",
        "sk-SK": "Zavrieť AI chat",
        "sv-FI": "Stäng AI-chatten",
        "sv-SE": "Stäng AI-chatten",
        "th-TH": "ปิดแชท AI",
        "tr-TR": "Yapay zeka sohbetini kapat",
        "uk-UA": "Закрити ШІ-чат",
        "vi-VN": "Đóng trò chuyện AI",
        "zh-CN": "关闭 AI 聊天",
        "zh-SG": "关闭 AI 聊天",
        "zh-TW": "關閉 AI 聊天",
      },
      description: "Aria-label for the floating-widget close button.",
    },
    "ai-chat-user": {
      defaultValue: "You",
      translations: {
        "ar-AE": "أنت",
        "ar-BH": "أنت",
        "ar-DZ": "أنت",
        "ar-EG": "أنت",
        "ar-IQ": "أنت",
        "ar-JO": "أنت",
        "ar-KW": "أنت",
        "ar-LB": "أنت",
        "ar-LY": "أنت",
        "ar-MA": "أنت",
        "ar-OM": "أنت",
        "ar-QA": "أنت",
        "ar-SA": "أنت",
        "ar-SY": "أنت",
        "ar-TN": "أنت",
        "ar-YE": "أنت",
        "cs-CZ": "Vy",
        da: "Dig",
        "de-AT": "Sie",
        "de-CH": "Sie",
        "de-DE": "Sie",
        "de-LI": "Sie",
        "de-LU": "Sie",
        "el-GR": "Εσείς",
        "en-AU": "You",
        "en-BZ": "You",
        "en-CA": "You",
        "en-GB": "You",
        "en-IE": "You",
        "en-JM": "You",
        "en-NZ": "You",
        "en-PH": "You",
        "en-TT": "You",
        "en-US": "You",
        "en-ZA": "You",
        "en-ZW": "You",
        "es-AR": "Tú",
        "es-BO": "Tú",
        "es-CL": "Tú",
        "es-CO": "Tú",
        "es-CR": "Tú",
        "es-DO": "Tú",
        "es-EC": "Tú",
        "es-ES": "Tú",
        "es-GT": "Tú",
        "es-HN": "Tú",
        "es-MX": "Tú",
        "es-NI": "Tú",
        "es-PA": "Tú",
        "es-PE": "Tú",
        "es-PR": "Tú",
        "es-PY": "Tú",
        "es-SV": "Tú",
        "es-UY": "Tú",
        "es-VE": "Tú",
        "fi-FI": "Sinä",
        "fr-BE": "Vous",
        "fr-CA": "Vous",
        "fr-CH": "Vous",
        "fr-FR": "Vous",
        "fr-LU": "Vous",
        "fr-MC": "Vous",
        "he-IL": "אתה",
        "hi-IN": "आप",
        "hu-HU": "Ön",
        "id-ID": "Anda",
        "it-CH": "Tu",
        "it-IT": "Tu",
        "ja-JP": "あなた",
        "ko-KR": "나",
        "nb-NO": "Deg",
        "nl-BE": "Jij",
        "nl-NL": "Jij",
        "pl-PL": "Ty",
        "pt-BR": "Você",
        "pt-PT": "Você",
        "ro-RO": "Tu",
        "ru-RU": "Вы",
        "sk-SK": "Vy",
        "sv-FI": "Du",
        "sv-SE": "Du",
        "th-TH": "คุณ",
        "tr-TR": "Siz",
        "uk-UA": "Ви",
        "vi-VN": "Bạn",
        "zh-CN": "你",
        "zh-SG": "你",
        "zh-TW": "你",
      },
      description: "Label above the user's own messages.",
    },
    "ai-chat-assistant": {
      defaultValue: "Assistant",
      translations: {
        "ar-AE": "المساعد",
        "ar-BH": "المساعد",
        "ar-DZ": "المساعد",
        "ar-EG": "المساعد",
        "ar-IQ": "المساعد",
        "ar-JO": "المساعد",
        "ar-KW": "المساعد",
        "ar-LB": "المساعد",
        "ar-LY": "المساعد",
        "ar-MA": "المساعد",
        "ar-OM": "المساعد",
        "ar-QA": "المساعد",
        "ar-SA": "المساعد",
        "ar-SY": "المساعد",
        "ar-TN": "المساعد",
        "ar-YE": "المساعد",
        "cs-CZ": "Asistent",
        da: "Assistent",
        "de-AT": "Assistent",
        "de-CH": "Assistent",
        "de-DE": "Assistent",
        "de-LI": "Assistent",
        "de-LU": "Assistent",
        "el-GR": "Βοηθός",
        "en-AU": "Assistant",
        "en-BZ": "Assistant",
        "en-CA": "Assistant",
        "en-GB": "Assistant",
        "en-IE": "Assistant",
        "en-JM": "Assistant",
        "en-NZ": "Assistant",
        "en-PH": "Assistant",
        "en-TT": "Assistant",
        "en-US": "Assistant",
        "en-ZA": "Assistant",
        "en-ZW": "Assistant",
        "es-AR": "Asistente",
        "es-BO": "Asistente",
        "es-CL": "Asistente",
        "es-CO": "Asistente",
        "es-CR": "Asistente",
        "es-DO": "Asistente",
        "es-EC": "Asistente",
        "es-ES": "Asistente",
        "es-GT": "Asistente",
        "es-HN": "Asistente",
        "es-MX": "Asistente",
        "es-NI": "Asistente",
        "es-PA": "Asistente",
        "es-PE": "Asistente",
        "es-PR": "Asistente",
        "es-PY": "Asistente",
        "es-SV": "Asistente",
        "es-UY": "Asistente",
        "es-VE": "Asistente",
        "fi-FI": "Avustaja",
        "fr-BE": "Assistant",
        "fr-CA": "Assistant",
        "fr-CH": "Assistant",
        "fr-FR": "Assistant",
        "fr-LU": "Assistant",
        "fr-MC": "Assistant",
        "he-IL": "עוזר",
        "hi-IN": "सहायक",
        "hu-HU": "Asszisztens",
        "id-ID": "Asisten",
        "it-CH": "Assistente",
        "it-IT": "Assistente",
        "ja-JP": "アシスタント",
        "ko-KR": "어시스턴트",
        "nb-NO": "Assistent",
        "nl-BE": "Assistent",
        "nl-NL": "Assistent",
        "pl-PL": "Asystent",
        "pt-BR": "Assistente",
        "pt-PT": "Assistente",
        "ro-RO": "Asistent",
        "ru-RU": "Ассистент",
        "sk-SK": "Asistent",
        "sv-FI": "Assistent",
        "sv-SE": "Assistent",
        "th-TH": "ผู้ช่วย",
        "tr-TR": "Asistan",
        "uk-UA": "Асистент",
        "vi-VN": "Trợ lý",
        "zh-CN": "助手",
        "zh-SG": "助手",
        "zh-TW": "助手",
      },
      description:
        "Fallback label beside assistant messages when no AssistantName field is set.",
    },
    "ai-chat-show-history": {
      defaultValue: "Show history",
      translations: {
        "ar-AE": "إظهار السجل",
        "ar-BH": "إظهار السجل",
        "ar-DZ": "إظهار السجل",
        "ar-EG": "إظهار السجل",
        "ar-IQ": "إظهار السجل",
        "ar-JO": "إظهار السجل",
        "ar-KW": "إظهار السجل",
        "ar-LB": "إظهار السجل",
        "ar-LY": "إظهار السجل",
        "ar-MA": "إظهار السجل",
        "ar-OM": "إظهار السجل",
        "ar-QA": "إظهار السجل",
        "ar-SA": "إظهار السجل",
        "ar-SY": "إظهار السجل",
        "ar-TN": "إظهار السجل",
        "ar-YE": "إظهار السجل",
        "cs-CZ": "Zobrazit historii",
        da: "Vis historik",
        "de-AT": "Verlauf anzeigen",
        "de-CH": "Verlauf anzeigen",
        "de-DE": "Verlauf anzeigen",
        "de-LI": "Verlauf anzeigen",
        "de-LU": "Verlauf anzeigen",
        "el-GR": "Εμφάνιση ιστορικού",
        "en-AU": "Show history",
        "en-BZ": "Show history",
        "en-CA": "Show history",
        "en-GB": "Show history",
        "en-IE": "Show history",
        "en-JM": "Show history",
        "en-NZ": "Show history",
        "en-PH": "Show history",
        "en-TT": "Show history",
        "en-US": "Show history",
        "en-ZA": "Show history",
        "en-ZW": "Show history",
        "es-AR": "Mostrar historial",
        "es-BO": "Mostrar historial",
        "es-CL": "Mostrar historial",
        "es-CO": "Mostrar historial",
        "es-CR": "Mostrar historial",
        "es-DO": "Mostrar historial",
        "es-EC": "Mostrar historial",
        "es-ES": "Mostrar historial",
        "es-GT": "Mostrar historial",
        "es-HN": "Mostrar historial",
        "es-MX": "Mostrar historial",
        "es-NI": "Mostrar historial",
        "es-PA": "Mostrar historial",
        "es-PE": "Mostrar historial",
        "es-PR": "Mostrar historial",
        "es-PY": "Mostrar historial",
        "es-SV": "Mostrar historial",
        "es-UY": "Mostrar historial",
        "es-VE": "Mostrar historial",
        "fi-FI": "Näytä historia",
        "fr-BE": "Afficher l'historique",
        "fr-CA": "Afficher l'historique",
        "fr-CH": "Afficher l'historique",
        "fr-FR": "Afficher l'historique",
        "fr-LU": "Afficher l'historique",
        "fr-MC": "Afficher l'historique",
        "he-IL": "הצגת היסטוריה",
        "hi-IN": "इतिहास दिखाएँ",
        "hu-HU": "Előzmények megjelenítése",
        "id-ID": "Tampilkan riwayat",
        "it-CH": "Mostra cronologia",
        "it-IT": "Mostra cronologia",
        "ja-JP": "履歴を表示",
        "ko-KR": "기록 보기",
        "nb-NO": "Vis historikk",
        "nl-BE": "Geschiedenis tonen",
        "nl-NL": "Geschiedenis tonen",
        "pl-PL": "Pokaż historię",
        "pt-BR": "Mostrar histórico",
        "pt-PT": "Mostrar histórico",
        "ro-RO": "Afișează istoricul",
        "ru-RU": "Показать историю",
        "sk-SK": "Zobraziť históriu",
        "sv-FI": "Visa historik",
        "sv-SE": "Visa historik",
        "th-TH": "แสดงประวัติ",
        "tr-TR": "Geçmişi göster",
        "uk-UA": "Показати історію",
        "vi-VN": "Hiện lịch sử",
        "zh-CN": "显示历史记录",
        "zh-SG": "显示历史记录",
        "zh-TW": "顯示歷史記錄",
      },
      description: "Hero-collapsible toggle: expand older turns.",
    },
    "ai-chat-hide-history": {
      defaultValue: "Hide history",
      translations: {
        "ar-AE": "إخفاء السجل",
        "ar-BH": "إخفاء السجل",
        "ar-DZ": "إخفاء السجل",
        "ar-EG": "إخفاء السجل",
        "ar-IQ": "إخفاء السجل",
        "ar-JO": "إخفاء السجل",
        "ar-KW": "إخفاء السجل",
        "ar-LB": "إخفاء السجل",
        "ar-LY": "إخفاء السجل",
        "ar-MA": "إخفاء السجل",
        "ar-OM": "إخفاء السجل",
        "ar-QA": "إخفاء السجل",
        "ar-SA": "إخفاء السجل",
        "ar-SY": "إخفاء السجل",
        "ar-TN": "إخفاء السجل",
        "ar-YE": "إخفاء السجل",
        "cs-CZ": "Skrýt historii",
        da: "Skjul historik",
        "de-AT": "Verlauf ausblenden",
        "de-CH": "Verlauf ausblenden",
        "de-DE": "Verlauf ausblenden",
        "de-LI": "Verlauf ausblenden",
        "de-LU": "Verlauf ausblenden",
        "el-GR": "Απόκρυψη ιστορικού",
        "en-AU": "Hide history",
        "en-BZ": "Hide history",
        "en-CA": "Hide history",
        "en-GB": "Hide history",
        "en-IE": "Hide history",
        "en-JM": "Hide history",
        "en-NZ": "Hide history",
        "en-PH": "Hide history",
        "en-TT": "Hide history",
        "en-US": "Hide history",
        "en-ZA": "Hide history",
        "en-ZW": "Hide history",
        "es-AR": "Ocultar historial",
        "es-BO": "Ocultar historial",
        "es-CL": "Ocultar historial",
        "es-CO": "Ocultar historial",
        "es-CR": "Ocultar historial",
        "es-DO": "Ocultar historial",
        "es-EC": "Ocultar historial",
        "es-ES": "Ocultar historial",
        "es-GT": "Ocultar historial",
        "es-HN": "Ocultar historial",
        "es-MX": "Ocultar historial",
        "es-NI": "Ocultar historial",
        "es-PA": "Ocultar historial",
        "es-PE": "Ocultar historial",
        "es-PR": "Ocultar historial",
        "es-PY": "Ocultar historial",
        "es-SV": "Ocultar historial",
        "es-UY": "Ocultar historial",
        "es-VE": "Ocultar historial",
        "fi-FI": "Piilota historia",
        "fr-BE": "Masquer l'historique",
        "fr-CA": "Masquer l'historique",
        "fr-CH": "Masquer l'historique",
        "fr-FR": "Masquer l'historique",
        "fr-LU": "Masquer l'historique",
        "fr-MC": "Masquer l'historique",
        "he-IL": "הסתרת היסטוריה",
        "hi-IN": "इतिहास छिपाएँ",
        "hu-HU": "Előzmények elrejtése",
        "id-ID": "Sembunyikan riwayat",
        "it-CH": "Nascondi cronologia",
        "it-IT": "Nascondi cronologia",
        "ja-JP": "履歴を非表示",
        "ko-KR": "기록 숨기기",
        "nb-NO": "Skjul historikk",
        "nl-BE": "Geschiedenis verbergen",
        "nl-NL": "Geschiedenis verbergen",
        "pl-PL": "Ukryj historię",
        "pt-BR": "Ocultar histórico",
        "pt-PT": "Ocultar histórico",
        "ro-RO": "Ascunde istoricul",
        "ru-RU": "Скрыть историю",
        "sk-SK": "Skryť históriu",
        "sv-FI": "Dölj historik",
        "sv-SE": "Dölj historik",
        "th-TH": "ซ่อนประวัติ",
        "tr-TR": "Geçmişi gizle",
        "uk-UA": "Сховати історію",
        "vi-VN": "Ẩn lịch sử",
        "zh-CN": "隐藏历史记录",
        "zh-SG": "隐藏历史记录",
        "zh-TW": "隱藏歷史記錄",
      },
      description: "Hero-collapsible toggle: collapse to the latest exchange.",
    },
    "ai-chat-widget-title": {
      defaultValue: "AI Assistant",
      translations: {
        "ar-AE": "مساعد الذكاء الاصطناعي",
        "ar-BH": "مساعد الذكاء الاصطناعي",
        "ar-DZ": "مساعد الذكاء الاصطناعي",
        "ar-EG": "مساعد الذكاء الاصطناعي",
        "ar-IQ": "مساعد الذكاء الاصطناعي",
        "ar-JO": "مساعد الذكاء الاصطناعي",
        "ar-KW": "مساعد الذكاء الاصطناعي",
        "ar-LB": "مساعد الذكاء الاصطناعي",
        "ar-LY": "مساعد الذكاء الاصطناعي",
        "ar-MA": "مساعد الذكاء الاصطناعي",
        "ar-OM": "مساعد الذكاء الاصطناعي",
        "ar-QA": "مساعد الذكاء الاصطناعي",
        "ar-SA": "مساعد الذكاء الاصطناعي",
        "ar-SY": "مساعد الذكاء الاصطناعي",
        "ar-TN": "مساعد الذكاء الاصطناعي",
        "ar-YE": "مساعد الذكاء الاصطناعي",
        "cs-CZ": "Asistent AI",
        da: "AI-assistent",
        "de-AT": "KI-Assistent",
        "de-CH": "KI-Assistent",
        "de-DE": "KI-Assistent",
        "de-LI": "KI-Assistent",
        "de-LU": "KI-Assistent",
        "el-GR": "Βοηθός AI",
        "en-AU": "AI Assistant",
        "en-BZ": "AI Assistant",
        "en-CA": "AI Assistant",
        "en-GB": "AI Assistant",
        "en-IE": "AI Assistant",
        "en-JM": "AI Assistant",
        "en-NZ": "AI Assistant",
        "en-PH": "AI Assistant",
        "en-TT": "AI Assistant",
        "en-US": "AI Assistant",
        "en-ZA": "AI Assistant",
        "en-ZW": "AI Assistant",
        "es-AR": "Asistente de IA",
        "es-BO": "Asistente de IA",
        "es-CL": "Asistente de IA",
        "es-CO": "Asistente de IA",
        "es-CR": "Asistente de IA",
        "es-DO": "Asistente de IA",
        "es-EC": "Asistente de IA",
        "es-ES": "Asistente de IA",
        "es-GT": "Asistente de IA",
        "es-HN": "Asistente de IA",
        "es-MX": "Asistente de IA",
        "es-NI": "Asistente de IA",
        "es-PA": "Asistente de IA",
        "es-PE": "Asistente de IA",
        "es-PR": "Asistente de IA",
        "es-PY": "Asistente de IA",
        "es-SV": "Asistente de IA",
        "es-UY": "Asistente de IA",
        "es-VE": "Asistente de IA",
        "fi-FI": "Tekoälyavustaja",
        "fr-BE": "Assistant IA",
        "fr-CA": "Assistant IA",
        "fr-CH": "Assistant IA",
        "fr-FR": "Assistant IA",
        "fr-LU": "Assistant IA",
        "fr-MC": "Assistant IA",
        "he-IL": "עוזר AI",
        "hi-IN": "AI सहायक",
        "hu-HU": "AI-asszisztens",
        "id-ID": "Asisten AI",
        "it-CH": "Assistente IA",
        "it-IT": "Assistente IA",
        "ja-JP": "AIアシスタント",
        "ko-KR": "AI 어시스턴트",
        "nb-NO": "AI-assistent",
        "nl-BE": "AI-assistent",
        "nl-NL": "AI-assistent",
        "pl-PL": "Asystent AI",
        "pt-BR": "Assistente de IA",
        "pt-PT": "Assistente de IA",
        "ro-RO": "Asistent AI",
        "ru-RU": "ИИ-ассистент",
        "sk-SK": "AI asistent",
        "sv-FI": "AI-assistent",
        "sv-SE": "AI-assistent",
        "th-TH": "ผู้ช่วย AI",
        "tr-TR": "Yapay Zeka Asistanı",
        "uk-UA": "ШІ-асистент",
        "vi-VN": "Trợ lý AI",
        "zh-CN": "AI 助手",
        "zh-SG": "AI 助手",
        "zh-TW": "AI 助手",
      },
      description:
        "Fallback title for the floating widget when no Title field is set.",
    },
    "ai-chat-open-launcher": {
      defaultValue: "Open {title}",
      translations: {
        "ar-AE": "فتح {title}",
        "ar-BH": "فتح {title}",
        "ar-DZ": "فتح {title}",
        "ar-EG": "فتح {title}",
        "ar-IQ": "فتح {title}",
        "ar-JO": "فتح {title}",
        "ar-KW": "فتح {title}",
        "ar-LB": "فتح {title}",
        "ar-LY": "فتح {title}",
        "ar-MA": "فتح {title}",
        "ar-OM": "فتح {title}",
        "ar-QA": "فتح {title}",
        "ar-SA": "فتح {title}",
        "ar-SY": "فتح {title}",
        "ar-TN": "فتح {title}",
        "ar-YE": "فتح {title}",
        "cs-CZ": "Otevřít {title}",
        da: "Åbn {title}",
        "de-AT": "{title} öffnen",
        "de-CH": "{title} öffnen",
        "de-DE": "{title} öffnen",
        "de-LI": "{title} öffnen",
        "de-LU": "{title} öffnen",
        "el-GR": "Άνοιγμα {title}",
        "en-AU": "Open {title}",
        "en-BZ": "Open {title}",
        "en-CA": "Open {title}",
        "en-GB": "Open {title}",
        "en-IE": "Open {title}",
        "en-JM": "Open {title}",
        "en-NZ": "Open {title}",
        "en-PH": "Open {title}",
        "en-TT": "Open {title}",
        "en-US": "Open {title}",
        "en-ZA": "Open {title}",
        "en-ZW": "Open {title}",
        "es-AR": "Abrir {title}",
        "es-BO": "Abrir {title}",
        "es-CL": "Abrir {title}",
        "es-CO": "Abrir {title}",
        "es-CR": "Abrir {title}",
        "es-DO": "Abrir {title}",
        "es-EC": "Abrir {title}",
        "es-ES": "Abrir {title}",
        "es-GT": "Abrir {title}",
        "es-HN": "Abrir {title}",
        "es-MX": "Abrir {title}",
        "es-NI": "Abrir {title}",
        "es-PA": "Abrir {title}",
        "es-PE": "Abrir {title}",
        "es-PR": "Abrir {title}",
        "es-PY": "Abrir {title}",
        "es-SV": "Abrir {title}",
        "es-UY": "Abrir {title}",
        "es-VE": "Abrir {title}",
        "fi-FI": "Avaa {title}",
        "fr-BE": "Ouvrir {title}",
        "fr-CA": "Ouvrir {title}",
        "fr-CH": "Ouvrir {title}",
        "fr-FR": "Ouvrir {title}",
        "fr-LU": "Ouvrir {title}",
        "fr-MC": "Ouvrir {title}",
        "he-IL": "פתיחת {title}",
        "hi-IN": "{title} खोलें",
        "hu-HU": "{title} megnyitása",
        "id-ID": "Buka {title}",
        "it-CH": "Apri {title}",
        "it-IT": "Apri {title}",
        "ja-JP": "{title} を開く",
        "ko-KR": "{title} 열기",
        "nb-NO": "Åpne {title}",
        "nl-BE": "{title} openen",
        "nl-NL": "{title} openen",
        "pl-PL": "Otwórz {title}",
        "pt-BR": "Abrir {title}",
        "pt-PT": "Abrir {title}",
        "ro-RO": "Deschide {title}",
        "ru-RU": "Открыть {title}",
        "sk-SK": "Otvoriť {title}",
        "sv-FI": "Öppna {title}",
        "sv-SE": "Öppna {title}",
        "th-TH": "เปิด {title}",
        "tr-TR": "{title} aç",
        "uk-UA": "Відкрити {title}",
        "vi-VN": "Mở {title}",
        "zh-CN": "打开 {title}",
        "zh-SG": "打开 {title}",
        "zh-TW": "開啟 {title}",
      },
      description:
        "Aria-label for the floating launcher button. Keep the `{title}` token — it is replaced with the widget title.",
    },
  },
} satisfies DictionaryRecipe;

export default aiChatUiLabelsConversationRecipe;
