import type { DictionaryRecipe } from "@sitecoreai-labs/sitecoreai-cli/recipe";

/**
 * AI Chat UI Labels — Tool Calls — a shard of the AI Chat UI Labels phrase library, split so no
 * single Dictionary recipe pushes more item versions than one sandbox can
 * apply. Phrase keys are unchanged; only which recipe authors them differs.
 */
export const aiChatUiLabelsToolsRecipe = {
  kind: "dictionary",
  schemaVersion: "1",
  handle: "ai-chat-ui-labels-tools@1",
  name: "AiChatUiLabelsTools",
  displayName: "AI Chat UI Labels — Tool Calls",
  description:
    "AI Chat dictionary shard — tool-call card headings and tool state badges (running, input, output, error, waiting, calling, completed, errored, approval, denied).",
  primaryLocale: "en",
  phrases: {
    "ai-chat-tool-running": {
      defaultValue: "Tool running",
      translations: {
        "ar-AE": "الأداة قيد التشغيل",
        "ar-BH": "الأداة قيد التشغيل",
        "ar-DZ": "الأداة قيد التشغيل",
        "ar-EG": "الأداة قيد التشغيل",
        "ar-IQ": "الأداة قيد التشغيل",
        "ar-JO": "الأداة قيد التشغيل",
        "ar-KW": "الأداة قيد التشغيل",
        "ar-LB": "الأداة قيد التشغيل",
        "ar-LY": "الأداة قيد التشغيل",
        "ar-MA": "الأداة قيد التشغيل",
        "ar-OM": "الأداة قيد التشغيل",
        "ar-QA": "الأداة قيد التشغيل",
        "ar-SA": "الأداة قيد التشغيل",
        "ar-SY": "الأداة قيد التشغيل",
        "ar-TN": "الأداة قيد التشغيل",
        "ar-YE": "الأداة قيد التشغيل",
        "cs-CZ": "Nástroj běží",
        da: "Værktøj kører",
        "de-AT": "Tool wird ausgeführt",
        "de-CH": "Tool wird ausgeführt",
        "de-DE": "Tool wird ausgeführt",
        "de-LI": "Tool wird ausgeführt",
        "de-LU": "Tool wird ausgeführt",
        "el-GR": "Το εργαλείο εκτελείται",
        "en-AU": "Tool running",
        "en-BZ": "Tool running",
        "en-CA": "Tool running",
        "en-GB": "Tool running",
        "en-IE": "Tool running",
        "en-JM": "Tool running",
        "en-NZ": "Tool running",
        "en-PH": "Tool running",
        "en-TT": "Tool running",
        "en-US": "Tool running",
        "en-ZA": "Tool running",
        "en-ZW": "Tool running",
        "es-AR": "Herramienta en ejecución",
        "es-BO": "Herramienta en ejecución",
        "es-CL": "Herramienta en ejecución",
        "es-CO": "Herramienta en ejecución",
        "es-CR": "Herramienta en ejecución",
        "es-DO": "Herramienta en ejecución",
        "es-EC": "Herramienta en ejecución",
        "es-ES": "Herramienta en ejecución",
        "es-GT": "Herramienta en ejecución",
        "es-HN": "Herramienta en ejecución",
        "es-MX": "Herramienta en ejecución",
        "es-NI": "Herramienta en ejecución",
        "es-PA": "Herramienta en ejecución",
        "es-PE": "Herramienta en ejecución",
        "es-PR": "Herramienta en ejecución",
        "es-PY": "Herramienta en ejecución",
        "es-SV": "Herramienta en ejecución",
        "es-UY": "Herramienta en ejecución",
        "es-VE": "Herramienta en ejecución",
        "fi-FI": "Työkalu käynnissä",
        "fr-BE": "Outil en cours d'exécution",
        "fr-CA": "Outil en cours d'exécution",
        "fr-CH": "Outil en cours d'exécution",
        "fr-FR": "Outil en cours d'exécution",
        "fr-LU": "Outil en cours d'exécution",
        "fr-MC": "Outil en cours d'exécution",
        "he-IL": "הכלי פועל",
        "hi-IN": "टूल चल रहा है",
        "hu-HU": "Eszköz fut",
        "id-ID": "Alat berjalan",
        "it-CH": "Strumento in esecuzione",
        "it-IT": "Strumento in esecuzione",
        "ja-JP": "ツール実行中",
        "ko-KR": "도구 실행 중",
        "nb-NO": "Verktøy kjører",
        "nl-BE": "Tool wordt uitgevoerd",
        "nl-NL": "Tool wordt uitgevoerd",
        "pl-PL": "Narzędzie działa",
        "pt-BR": "Ferramenta em execução",
        "pt-PT": "Ferramenta em execução",
        "ro-RO": "Instrument în execuție",
        "ru-RU": "Инструмент выполняется",
        "sk-SK": "Nástroj beží",
        "sv-FI": "Verktyg körs",
        "sv-SE": "Verktyg körs",
        "th-TH": "เครื่องมือกำลังทำงาน",
        "tr-TR": "Araç çalışıyor",
        "uk-UA": "Інструмент виконується",
        "vi-VN": "Công cụ đang chạy",
        "zh-CN": "工具运行中",
        "zh-SG": "工具运行中",
        "zh-TW": "工具執行中",
      },
      description: "Aria-label for the tool-call spinner.",
    },
    "ai-chat-tool-input": {
      defaultValue: "Input",
      translations: {
        "ar-AE": "المدخلات",
        "ar-BH": "المدخلات",
        "ar-DZ": "المدخلات",
        "ar-EG": "المدخلات",
        "ar-IQ": "المدخلات",
        "ar-JO": "المدخلات",
        "ar-KW": "المدخلات",
        "ar-LB": "المدخلات",
        "ar-LY": "المدخلات",
        "ar-MA": "المدخلات",
        "ar-OM": "المدخلات",
        "ar-QA": "المدخلات",
        "ar-SA": "المدخلات",
        "ar-SY": "المدخلات",
        "ar-TN": "المدخلات",
        "ar-YE": "المدخلات",
        "cs-CZ": "Vstup",
        da: "Input",
        "de-AT": "Eingabe",
        "de-CH": "Eingabe",
        "de-DE": "Eingabe",
        "de-LI": "Eingabe",
        "de-LU": "Eingabe",
        "el-GR": "Είσοδος",
        "en-AU": "Input",
        "en-BZ": "Input",
        "en-CA": "Input",
        "en-GB": "Input",
        "en-IE": "Input",
        "en-JM": "Input",
        "en-NZ": "Input",
        "en-PH": "Input",
        "en-TT": "Input",
        "en-US": "Input",
        "en-ZA": "Input",
        "en-ZW": "Input",
        "es-AR": "Entrada",
        "es-BO": "Entrada",
        "es-CL": "Entrada",
        "es-CO": "Entrada",
        "es-CR": "Entrada",
        "es-DO": "Entrada",
        "es-EC": "Entrada",
        "es-ES": "Entrada",
        "es-GT": "Entrada",
        "es-HN": "Entrada",
        "es-MX": "Entrada",
        "es-NI": "Entrada",
        "es-PA": "Entrada",
        "es-PE": "Entrada",
        "es-PR": "Entrada",
        "es-PY": "Entrada",
        "es-SV": "Entrada",
        "es-UY": "Entrada",
        "es-VE": "Entrada",
        "fi-FI": "Syöte",
        "fr-BE": "Entrée",
        "fr-CA": "Entrée",
        "fr-CH": "Entrée",
        "fr-FR": "Entrée",
        "fr-LU": "Entrée",
        "fr-MC": "Entrée",
        "he-IL": "קלט",
        "hi-IN": "इनपुट",
        "hu-HU": "Bemenet",
        "id-ID": "Input",
        "it-CH": "Input",
        "it-IT": "Input",
        "ja-JP": "入力",
        "ko-KR": "입력",
        "nb-NO": "Inndata",
        "nl-BE": "Invoer",
        "nl-NL": "Invoer",
        "pl-PL": "Dane wejściowe",
        "pt-BR": "Entrada",
        "pt-PT": "Entrada",
        "ro-RO": "Intrare",
        "ru-RU": "Ввод",
        "sk-SK": "Vstup",
        "sv-FI": "Indata",
        "sv-SE": "Indata",
        "th-TH": "อินพุต",
        "tr-TR": "Girdi",
        "uk-UA": "Вхідні дані",
        "vi-VN": "Đầu vào",
        "zh-CN": "输入",
        "zh-SG": "输入",
        "zh-TW": "輸入",
      },
      description: "Tool-call card: input section heading.",
    },
    "ai-chat-tool-output": {
      defaultValue: "Output",
      translations: {
        "ar-AE": "المخرجات",
        "ar-BH": "المخرجات",
        "ar-DZ": "المخرجات",
        "ar-EG": "المخرجات",
        "ar-IQ": "المخرجات",
        "ar-JO": "المخرجات",
        "ar-KW": "المخرجات",
        "ar-LB": "المخرجات",
        "ar-LY": "المخرجات",
        "ar-MA": "المخرجات",
        "ar-OM": "المخرجات",
        "ar-QA": "المخرجات",
        "ar-SA": "المخرجات",
        "ar-SY": "المخرجات",
        "ar-TN": "المخرجات",
        "ar-YE": "المخرجات",
        "cs-CZ": "Výstup",
        da: "Output",
        "de-AT": "Ausgabe",
        "de-CH": "Ausgabe",
        "de-DE": "Ausgabe",
        "de-LI": "Ausgabe",
        "de-LU": "Ausgabe",
        "el-GR": "Έξοδος",
        "en-AU": "Output",
        "en-BZ": "Output",
        "en-CA": "Output",
        "en-GB": "Output",
        "en-IE": "Output",
        "en-JM": "Output",
        "en-NZ": "Output",
        "en-PH": "Output",
        "en-TT": "Output",
        "en-US": "Output",
        "en-ZA": "Output",
        "en-ZW": "Output",
        "es-AR": "Salida",
        "es-BO": "Salida",
        "es-CL": "Salida",
        "es-CO": "Salida",
        "es-CR": "Salida",
        "es-DO": "Salida",
        "es-EC": "Salida",
        "es-ES": "Salida",
        "es-GT": "Salida",
        "es-HN": "Salida",
        "es-MX": "Salida",
        "es-NI": "Salida",
        "es-PA": "Salida",
        "es-PE": "Salida",
        "es-PR": "Salida",
        "es-PY": "Salida",
        "es-SV": "Salida",
        "es-UY": "Salida",
        "es-VE": "Salida",
        "fi-FI": "Tuloste",
        "fr-BE": "Sortie",
        "fr-CA": "Sortie",
        "fr-CH": "Sortie",
        "fr-FR": "Sortie",
        "fr-LU": "Sortie",
        "fr-MC": "Sortie",
        "he-IL": "פלט",
        "hi-IN": "आउटपुट",
        "hu-HU": "Kimenet",
        "id-ID": "Output",
        "it-CH": "Output",
        "it-IT": "Output",
        "ja-JP": "出力",
        "ko-KR": "출력",
        "nb-NO": "Utdata",
        "nl-BE": "Uitvoer",
        "nl-NL": "Uitvoer",
        "pl-PL": "Dane wyjściowe",
        "pt-BR": "Saída",
        "pt-PT": "Saída",
        "ro-RO": "Ieșire",
        "ru-RU": "Вывод",
        "sk-SK": "Výstup",
        "sv-FI": "Utdata",
        "sv-SE": "Utdata",
        "th-TH": "เอาต์พุต",
        "tr-TR": "Çıktı",
        "uk-UA": "Вихідні дані",
        "vi-VN": "Đầu ra",
        "zh-CN": "输出",
        "zh-SG": "输出",
        "zh-TW": "輸出",
      },
      description: "Tool-call card: output section heading.",
    },
    "ai-chat-tool-error": {
      defaultValue: "Error",
      translations: {
        "ar-AE": "خطأ",
        "ar-BH": "خطأ",
        "ar-DZ": "خطأ",
        "ar-EG": "خطأ",
        "ar-IQ": "خطأ",
        "ar-JO": "خطأ",
        "ar-KW": "خطأ",
        "ar-LB": "خطأ",
        "ar-LY": "خطأ",
        "ar-MA": "خطأ",
        "ar-OM": "خطأ",
        "ar-QA": "خطأ",
        "ar-SA": "خطأ",
        "ar-SY": "خطأ",
        "ar-TN": "خطأ",
        "ar-YE": "خطأ",
        "cs-CZ": "Chyba",
        da: "Fejl",
        "de-AT": "Fehler",
        "de-CH": "Fehler",
        "de-DE": "Fehler",
        "de-LI": "Fehler",
        "de-LU": "Fehler",
        "el-GR": "Σφάλμα",
        "en-AU": "Error",
        "en-BZ": "Error",
        "en-CA": "Error",
        "en-GB": "Error",
        "en-IE": "Error",
        "en-JM": "Error",
        "en-NZ": "Error",
        "en-PH": "Error",
        "en-TT": "Error",
        "en-US": "Error",
        "en-ZA": "Error",
        "en-ZW": "Error",
        "es-AR": "Error",
        "es-BO": "Error",
        "es-CL": "Error",
        "es-CO": "Error",
        "es-CR": "Error",
        "es-DO": "Error",
        "es-EC": "Error",
        "es-ES": "Error",
        "es-GT": "Error",
        "es-HN": "Error",
        "es-MX": "Error",
        "es-NI": "Error",
        "es-PA": "Error",
        "es-PE": "Error",
        "es-PR": "Error",
        "es-PY": "Error",
        "es-SV": "Error",
        "es-UY": "Error",
        "es-VE": "Error",
        "fi-FI": "Virhe",
        "fr-BE": "Erreur",
        "fr-CA": "Erreur",
        "fr-CH": "Erreur",
        "fr-FR": "Erreur",
        "fr-LU": "Erreur",
        "fr-MC": "Erreur",
        "he-IL": "שגיאה",
        "hi-IN": "त्रुटि",
        "hu-HU": "Hiba",
        "id-ID": "Kesalahan",
        "it-CH": "Errore",
        "it-IT": "Errore",
        "ja-JP": "エラー",
        "ko-KR": "오류",
        "nb-NO": "Feil",
        "nl-BE": "Fout",
        "nl-NL": "Fout",
        "pl-PL": "Błąd",
        "pt-BR": "Erro",
        "pt-PT": "Erro",
        "ro-RO": "Eroare",
        "ru-RU": "Ошибка",
        "sk-SK": "Chyba",
        "sv-FI": "Fel",
        "sv-SE": "Fel",
        "th-TH": "ข้อผิดพลาด",
        "tr-TR": "Hata",
        "uk-UA": "Помилка",
        "vi-VN": "Lỗi",
        "zh-CN": "错误",
        "zh-SG": "错误",
        "zh-TW": "錯誤",
      },
      description: "Tool-call card: error section heading.",
    },
    "ai-chat-tool-waiting": {
      defaultValue: "Waiting…",
      translations: {
        "ar-AE": "في الانتظار…",
        "ar-BH": "في الانتظار…",
        "ar-DZ": "في الانتظار…",
        "ar-EG": "في الانتظار…",
        "ar-IQ": "في الانتظار…",
        "ar-JO": "في الانتظار…",
        "ar-KW": "في الانتظار…",
        "ar-LB": "في الانتظار…",
        "ar-LY": "في الانتظار…",
        "ar-MA": "في الانتظار…",
        "ar-OM": "في الانتظار…",
        "ar-QA": "في الانتظار…",
        "ar-SA": "في الانتظار…",
        "ar-SY": "في الانتظار…",
        "ar-TN": "في الانتظار…",
        "ar-YE": "في الانتظار…",
        "cs-CZ": "Čekání…",
        da: "Venter…",
        "de-AT": "Warten…",
        "de-CH": "Warten…",
        "de-DE": "Warten…",
        "de-LI": "Warten…",
        "de-LU": "Warten…",
        "el-GR": "Αναμονή…",
        "en-AU": "Waiting…",
        "en-BZ": "Waiting…",
        "en-CA": "Waiting…",
        "en-GB": "Waiting…",
        "en-IE": "Waiting…",
        "en-JM": "Waiting…",
        "en-NZ": "Waiting…",
        "en-PH": "Waiting…",
        "en-TT": "Waiting…",
        "en-US": "Waiting…",
        "en-ZA": "Waiting…",
        "en-ZW": "Waiting…",
        "es-AR": "Esperando…",
        "es-BO": "Esperando…",
        "es-CL": "Esperando…",
        "es-CO": "Esperando…",
        "es-CR": "Esperando…",
        "es-DO": "Esperando…",
        "es-EC": "Esperando…",
        "es-ES": "Esperando…",
        "es-GT": "Esperando…",
        "es-HN": "Esperando…",
        "es-MX": "Esperando…",
        "es-NI": "Esperando…",
        "es-PA": "Esperando…",
        "es-PE": "Esperando…",
        "es-PR": "Esperando…",
        "es-PY": "Esperando…",
        "es-SV": "Esperando…",
        "es-UY": "Esperando…",
        "es-VE": "Esperando…",
        "fi-FI": "Odottaa…",
        "fr-BE": "En attente…",
        "fr-CA": "En attente…",
        "fr-CH": "En attente…",
        "fr-FR": "En attente…",
        "fr-LU": "En attente…",
        "fr-MC": "En attente…",
        "he-IL": "ממתין…",
        "hi-IN": "प्रतीक्षारत…",
        "hu-HU": "Várakozás…",
        "id-ID": "Menunggu…",
        "it-CH": "In attesa…",
        "it-IT": "In attesa…",
        "ja-JP": "待機中…",
        "ko-KR": "대기 중…",
        "nb-NO": "Venter…",
        "nl-BE": "Wachten…",
        "nl-NL": "Wachten…",
        "pl-PL": "Oczekiwanie…",
        "pt-BR": "Aguardando…",
        "pt-PT": "A aguardar…",
        "ro-RO": "Se așteaptă…",
        "ru-RU": "Ожидание…",
        "sk-SK": "Čaká sa…",
        "sv-FI": "Väntar…",
        "sv-SE": "Väntar…",
        "th-TH": "กำลังรอ…",
        "tr-TR": "Bekleniyor…",
        "uk-UA": "Очікування…",
        "vi-VN": "Đang chờ…",
        "zh-CN": "等待中…",
        "zh-SG": "等待中…",
        "zh-TW": "等待中…",
      },
      description: "Tool-call card: placeholder while there is no I/O yet.",
    },
    "ai-chat-tool-calling": {
      defaultValue: "Calling…",
      translations: {
        "ar-AE": "جارٍ الاستدعاء…",
        "ar-BH": "جارٍ الاستدعاء…",
        "ar-DZ": "جارٍ الاستدعاء…",
        "ar-EG": "جارٍ الاستدعاء…",
        "ar-IQ": "جارٍ الاستدعاء…",
        "ar-JO": "جارٍ الاستدعاء…",
        "ar-KW": "جارٍ الاستدعاء…",
        "ar-LB": "جارٍ الاستدعاء…",
        "ar-LY": "جارٍ الاستدعاء…",
        "ar-MA": "جارٍ الاستدعاء…",
        "ar-OM": "جارٍ الاستدعاء…",
        "ar-QA": "جارٍ الاستدعاء…",
        "ar-SA": "جارٍ الاستدعاء…",
        "ar-SY": "جارٍ الاستدعاء…",
        "ar-TN": "جارٍ الاستدعاء…",
        "ar-YE": "جارٍ الاستدعاء…",
        "cs-CZ": "Volání…",
        da: "Kalder…",
        "de-AT": "Aufruf…",
        "de-CH": "Aufruf…",
        "de-DE": "Aufruf…",
        "de-LI": "Aufruf…",
        "de-LU": "Aufruf…",
        "el-GR": "Κλήση…",
        "en-AU": "Calling…",
        "en-BZ": "Calling…",
        "en-CA": "Calling…",
        "en-GB": "Calling…",
        "en-IE": "Calling…",
        "en-JM": "Calling…",
        "en-NZ": "Calling…",
        "en-PH": "Calling…",
        "en-TT": "Calling…",
        "en-US": "Calling…",
        "en-ZA": "Calling…",
        "en-ZW": "Calling…",
        "es-AR": "Llamando…",
        "es-BO": "Llamando…",
        "es-CL": "Llamando…",
        "es-CO": "Llamando…",
        "es-CR": "Llamando…",
        "es-DO": "Llamando…",
        "es-EC": "Llamando…",
        "es-ES": "Llamando…",
        "es-GT": "Llamando…",
        "es-HN": "Llamando…",
        "es-MX": "Llamando…",
        "es-NI": "Llamando…",
        "es-PA": "Llamando…",
        "es-PE": "Llamando…",
        "es-PR": "Llamando…",
        "es-PY": "Llamando…",
        "es-SV": "Llamando…",
        "es-UY": "Llamando…",
        "es-VE": "Llamando…",
        "fi-FI": "Kutsutaan…",
        "fr-BE": "Appel…",
        "fr-CA": "Appel…",
        "fr-CH": "Appel…",
        "fr-FR": "Appel…",
        "fr-LU": "Appel…",
        "fr-MC": "Appel…",
        "he-IL": "מפעיל…",
        "hi-IN": "कॉल हो रहा है…",
        "hu-HU": "Hívás…",
        "id-ID": "Memanggil…",
        "it-CH": "Chiamata…",
        "it-IT": "Chiamata…",
        "ja-JP": "呼び出し中…",
        "ko-KR": "호출 중…",
        "nb-NO": "Kaller…",
        "nl-BE": "Aanroepen…",
        "nl-NL": "Aanroepen…",
        "pl-PL": "Wywoływanie…",
        "pt-BR": "Chamando…",
        "pt-PT": "A chamar…",
        "ro-RO": "Se apelează…",
        "ru-RU": "Вызов…",
        "sk-SK": "Volanie…",
        "sv-FI": "Anropar…",
        "sv-SE": "Anropar…",
        "th-TH": "กำลังเรียก…",
        "tr-TR": "Çağrılıyor…",
        "uk-UA": "Виклик…",
        "vi-VN": "Đang gọi…",
        "zh-CN": "调用中…",
        "zh-SG": "调用中…",
        "zh-TW": "呼叫中…",
      },
      description: "Tool state badge: input streaming.",
    },
    "ai-chat-tool-waiting-output": {
      defaultValue: "Waiting for output…",
      translations: {
        "ar-AE": "في انتظار المخرجات…",
        "ar-BH": "في انتظار المخرجات…",
        "ar-DZ": "في انتظار المخرجات…",
        "ar-EG": "في انتظار المخرجات…",
        "ar-IQ": "في انتظار المخرجات…",
        "ar-JO": "في انتظار المخرجات…",
        "ar-KW": "في انتظار المخرجات…",
        "ar-LB": "في انتظار المخرجات…",
        "ar-LY": "في انتظار المخرجات…",
        "ar-MA": "في انتظار المخرجات…",
        "ar-OM": "في انتظار المخرجات…",
        "ar-QA": "في انتظار المخرجات…",
        "ar-SA": "في انتظار المخرجات…",
        "ar-SY": "في انتظار المخرجات…",
        "ar-TN": "في انتظار المخرجات…",
        "ar-YE": "في انتظار المخرجات…",
        "cs-CZ": "Čekání na výstup…",
        da: "Venter på output…",
        "de-AT": "Warte auf Ausgabe…",
        "de-CH": "Warte auf Ausgabe…",
        "de-DE": "Warte auf Ausgabe…",
        "de-LI": "Warte auf Ausgabe…",
        "de-LU": "Warte auf Ausgabe…",
        "el-GR": "Αναμονή για έξοδο…",
        "en-AU": "Waiting for output…",
        "en-BZ": "Waiting for output…",
        "en-CA": "Waiting for output…",
        "en-GB": "Waiting for output…",
        "en-IE": "Waiting for output…",
        "en-JM": "Waiting for output…",
        "en-NZ": "Waiting for output…",
        "en-PH": "Waiting for output…",
        "en-TT": "Waiting for output…",
        "en-US": "Waiting for output…",
        "en-ZA": "Waiting for output…",
        "en-ZW": "Waiting for output…",
        "es-AR": "Esperando la salida…",
        "es-BO": "Esperando la salida…",
        "es-CL": "Esperando la salida…",
        "es-CO": "Esperando la salida…",
        "es-CR": "Esperando la salida…",
        "es-DO": "Esperando la salida…",
        "es-EC": "Esperando la salida…",
        "es-ES": "Esperando la salida…",
        "es-GT": "Esperando la salida…",
        "es-HN": "Esperando la salida…",
        "es-MX": "Esperando la salida…",
        "es-NI": "Esperando la salida…",
        "es-PA": "Esperando la salida…",
        "es-PE": "Esperando la salida…",
        "es-PR": "Esperando la salida…",
        "es-PY": "Esperando la salida…",
        "es-SV": "Esperando la salida…",
        "es-UY": "Esperando la salida…",
        "es-VE": "Esperando la salida…",
        "fi-FI": "Odotetaan tulostetta…",
        "fr-BE": "En attente de la sortie…",
        "fr-CA": "En attente de la sortie…",
        "fr-CH": "En attente de la sortie…",
        "fr-FR": "En attente de la sortie…",
        "fr-LU": "En attente de la sortie…",
        "fr-MC": "En attente de la sortie…",
        "he-IL": "ממתין לפלט…",
        "hi-IN": "आउटपुट की प्रतीक्षा…",
        "hu-HU": "Kimenetre várva…",
        "id-ID": "Menunggu output…",
        "it-CH": "In attesa dell'output…",
        "it-IT": "In attesa dell'output…",
        "ja-JP": "出力を待機中…",
        "ko-KR": "출력 대기 중…",
        "nb-NO": "Venter på utdata…",
        "nl-BE": "Wachten op uitvoer…",
        "nl-NL": "Wachten op uitvoer…",
        "pl-PL": "Oczekiwanie na dane wyjściowe…",
        "pt-BR": "Aguardando a saída…",
        "pt-PT": "A aguardar a saída…",
        "ro-RO": "Se așteaptă ieșirea…",
        "ru-RU": "Ожидание вывода…",
        "sk-SK": "Čaká sa na výstup…",
        "sv-FI": "Väntar på utdata…",
        "sv-SE": "Väntar på utdata…",
        "th-TH": "กำลังรอเอาต์พุต…",
        "tr-TR": "Çıktı bekleniyor…",
        "uk-UA": "Очікування виводу…",
        "vi-VN": "Đang chờ đầu ra…",
        "zh-CN": "等待输出…",
        "zh-SG": "等待输出…",
        "zh-TW": "等待輸出…",
      },
      description: "Tool state badge: input available, awaiting output.",
    },
    "ai-chat-tool-completed": {
      defaultValue: "Completed",
      translations: {
        "ar-AE": "اكتمل",
        "ar-BH": "اكتمل",
        "ar-DZ": "اكتمل",
        "ar-EG": "اكتمل",
        "ar-IQ": "اكتمل",
        "ar-JO": "اكتمل",
        "ar-KW": "اكتمل",
        "ar-LB": "اكتمل",
        "ar-LY": "اكتمل",
        "ar-MA": "اكتمل",
        "ar-OM": "اكتمل",
        "ar-QA": "اكتمل",
        "ar-SA": "اكتمل",
        "ar-SY": "اكتمل",
        "ar-TN": "اكتمل",
        "ar-YE": "اكتمل",
        "cs-CZ": "Dokončeno",
        da: "Fuldført",
        "de-AT": "Abgeschlossen",
        "de-CH": "Abgeschlossen",
        "de-DE": "Abgeschlossen",
        "de-LI": "Abgeschlossen",
        "de-LU": "Abgeschlossen",
        "el-GR": "Ολοκληρώθηκε",
        "en-AU": "Completed",
        "en-BZ": "Completed",
        "en-CA": "Completed",
        "en-GB": "Completed",
        "en-IE": "Completed",
        "en-JM": "Completed",
        "en-NZ": "Completed",
        "en-PH": "Completed",
        "en-TT": "Completed",
        "en-US": "Completed",
        "en-ZA": "Completed",
        "en-ZW": "Completed",
        "es-AR": "Completado",
        "es-BO": "Completado",
        "es-CL": "Completado",
        "es-CO": "Completado",
        "es-CR": "Completado",
        "es-DO": "Completado",
        "es-EC": "Completado",
        "es-ES": "Completado",
        "es-GT": "Completado",
        "es-HN": "Completado",
        "es-MX": "Completado",
        "es-NI": "Completado",
        "es-PA": "Completado",
        "es-PE": "Completado",
        "es-PR": "Completado",
        "es-PY": "Completado",
        "es-SV": "Completado",
        "es-UY": "Completado",
        "es-VE": "Completado",
        "fi-FI": "Valmis",
        "fr-BE": "Terminé",
        "fr-CA": "Terminé",
        "fr-CH": "Terminé",
        "fr-FR": "Terminé",
        "fr-LU": "Terminé",
        "fr-MC": "Terminé",
        "he-IL": "הושלם",
        "hi-IN": "पूर्ण",
        "hu-HU": "Befejezve",
        "id-ID": "Selesai",
        "it-CH": "Completato",
        "it-IT": "Completato",
        "ja-JP": "完了",
        "ko-KR": "완료됨",
        "nb-NO": "Fullført",
        "nl-BE": "Voltooid",
        "nl-NL": "Voltooid",
        "pl-PL": "Zakończono",
        "pt-BR": "Concluído",
        "pt-PT": "Concluído",
        "ro-RO": "Finalizat",
        "ru-RU": "Завершено",
        "sk-SK": "Dokončené",
        "sv-FI": "Slutförd",
        "sv-SE": "Slutförd",
        "th-TH": "เสร็จสิ้น",
        "tr-TR": "Tamamlandı",
        "uk-UA": "Завершено",
        "vi-VN": "Hoàn thành",
        "zh-CN": "已完成",
        "zh-SG": "已完成",
        "zh-TW": "已完成",
      },
      description: "Tool state badge: output available.",
    },
    "ai-chat-tool-errored": {
      defaultValue: "Errored",
      translations: {
        "ar-AE": "حدث خطأ",
        "ar-BH": "حدث خطأ",
        "ar-DZ": "حدث خطأ",
        "ar-EG": "حدث خطأ",
        "ar-IQ": "حدث خطأ",
        "ar-JO": "حدث خطأ",
        "ar-KW": "حدث خطأ",
        "ar-LB": "حدث خطأ",
        "ar-LY": "حدث خطأ",
        "ar-MA": "حدث خطأ",
        "ar-OM": "حدث خطأ",
        "ar-QA": "حدث خطأ",
        "ar-SA": "حدث خطأ",
        "ar-SY": "حدث خطأ",
        "ar-TN": "حدث خطأ",
        "ar-YE": "حدث خطأ",
        "cs-CZ": "Chyba",
        da: "Fejlede",
        "de-AT": "Fehlgeschlagen",
        "de-CH": "Fehlgeschlagen",
        "de-DE": "Fehlgeschlagen",
        "de-LI": "Fehlgeschlagen",
        "de-LU": "Fehlgeschlagen",
        "el-GR": "Σφάλμα",
        "en-AU": "Errored",
        "en-BZ": "Errored",
        "en-CA": "Errored",
        "en-GB": "Errored",
        "en-IE": "Errored",
        "en-JM": "Errored",
        "en-NZ": "Errored",
        "en-PH": "Errored",
        "en-TT": "Errored",
        "en-US": "Errored",
        "en-ZA": "Errored",
        "en-ZW": "Errored",
        "es-AR": "Con error",
        "es-BO": "Con error",
        "es-CL": "Con error",
        "es-CO": "Con error",
        "es-CR": "Con error",
        "es-DO": "Con error",
        "es-EC": "Con error",
        "es-ES": "Con error",
        "es-GT": "Con error",
        "es-HN": "Con error",
        "es-MX": "Con error",
        "es-NI": "Con error",
        "es-PA": "Con error",
        "es-PE": "Con error",
        "es-PR": "Con error",
        "es-PY": "Con error",
        "es-SV": "Con error",
        "es-UY": "Con error",
        "es-VE": "Con error",
        "fi-FI": "Virhe",
        "fr-BE": "En erreur",
        "fr-CA": "En erreur",
        "fr-CH": "En erreur",
        "fr-FR": "En erreur",
        "fr-LU": "En erreur",
        "fr-MC": "En erreur",
        "he-IL": "נכשל",
        "hi-IN": "त्रुटि हुई",
        "hu-HU": "Hibás",
        "id-ID": "Gagal",
        "it-CH": "Con errore",
        "it-IT": "Con errore",
        "ja-JP": "エラー発生",
        "ko-KR": "오류 발생",
        "nb-NO": "Feilet",
        "nl-BE": "Mislukt",
        "nl-NL": "Mislukt",
        "pl-PL": "Błąd",
        "pt-BR": "Com erro",
        "pt-PT": "Com erro",
        "ro-RO": "Cu erori",
        "ru-RU": "Ошибка",
        "sk-SK": "Chyba",
        "sv-FI": "Misslyckades",
        "sv-SE": "Misslyckades",
        "th-TH": "เกิดข้อผิดพลาด",
        "tr-TR": "Hata oluştu",
        "uk-UA": "Помилка",
        "vi-VN": "Bị lỗi",
        "zh-CN": "出错",
        "zh-SG": "出错",
        "zh-TW": "發生錯誤",
      },
      description: "Tool state badge: output error.",
    },
    "ai-chat-tool-awaiting-approval": {
      defaultValue: "Awaiting approval",
      translations: {
        "ar-AE": "بانتظار الموافقة",
        "ar-BH": "بانتظار الموافقة",
        "ar-DZ": "بانتظار الموافقة",
        "ar-EG": "بانتظار الموافقة",
        "ar-IQ": "بانتظار الموافقة",
        "ar-JO": "بانتظار الموافقة",
        "ar-KW": "بانتظار الموافقة",
        "ar-LB": "بانتظار الموافقة",
        "ar-LY": "بانتظار الموافقة",
        "ar-MA": "بانتظار الموافقة",
        "ar-OM": "بانتظار الموافقة",
        "ar-QA": "بانتظار الموافقة",
        "ar-SA": "بانتظار الموافقة",
        "ar-SY": "بانتظار الموافقة",
        "ar-TN": "بانتظار الموافقة",
        "ar-YE": "بانتظار الموافقة",
        "cs-CZ": "Čeká na schválení",
        da: "Afventer godkendelse",
        "de-AT": "Warten auf Genehmigung",
        "de-CH": "Warten auf Genehmigung",
        "de-DE": "Warten auf Genehmigung",
        "de-LI": "Warten auf Genehmigung",
        "de-LU": "Warten auf Genehmigung",
        "el-GR": "Αναμονή έγκρισης",
        "en-AU": "Awaiting approval",
        "en-BZ": "Awaiting approval",
        "en-CA": "Awaiting approval",
        "en-GB": "Awaiting approval",
        "en-IE": "Awaiting approval",
        "en-JM": "Awaiting approval",
        "en-NZ": "Awaiting approval",
        "en-PH": "Awaiting approval",
        "en-TT": "Awaiting approval",
        "en-US": "Awaiting approval",
        "en-ZA": "Awaiting approval",
        "en-ZW": "Awaiting approval",
        "es-AR": "Esperando aprobación",
        "es-BO": "Esperando aprobación",
        "es-CL": "Esperando aprobación",
        "es-CO": "Esperando aprobación",
        "es-CR": "Esperando aprobación",
        "es-DO": "Esperando aprobación",
        "es-EC": "Esperando aprobación",
        "es-ES": "Esperando aprobación",
        "es-GT": "Esperando aprobación",
        "es-HN": "Esperando aprobación",
        "es-MX": "Esperando aprobación",
        "es-NI": "Esperando aprobación",
        "es-PA": "Esperando aprobación",
        "es-PE": "Esperando aprobación",
        "es-PR": "Esperando aprobación",
        "es-PY": "Esperando aprobación",
        "es-SV": "Esperando aprobación",
        "es-UY": "Esperando aprobación",
        "es-VE": "Esperando aprobación",
        "fi-FI": "Odottaa hyväksyntää",
        "fr-BE": "En attente d'approbation",
        "fr-CA": "En attente d'approbation",
        "fr-CH": "En attente d'approbation",
        "fr-FR": "En attente d'approbation",
        "fr-LU": "En attente d'approbation",
        "fr-MC": "En attente d'approbation",
        "he-IL": "ממתין לאישור",
        "hi-IN": "अनुमोदन की प्रतीक्षा",
        "hu-HU": "Jóváhagyásra vár",
        "id-ID": "Menunggu persetujuan",
        "it-CH": "In attesa di approvazione",
        "it-IT": "In attesa di approvazione",
        "ja-JP": "承認待ち",
        "ko-KR": "승인 대기 중",
        "nb-NO": "Venter på godkjenning",
        "nl-BE": "Wacht op goedkeuring",
        "nl-NL": "Wacht op goedkeuring",
        "pl-PL": "Oczekuje na zatwierdzenie",
        "pt-BR": "Aguardando aprovação",
        "pt-PT": "A aguardar aprovação",
        "ro-RO": "În așteptarea aprobării",
        "ru-RU": "Ожидает одобрения",
        "sk-SK": "Čaká na schválenie",
        "sv-FI": "Väntar på godkännande",
        "sv-SE": "Väntar på godkännande",
        "th-TH": "รอการอนุมัติ",
        "tr-TR": "Onay bekleniyor",
        "uk-UA": "Очікує схвалення",
        "vi-VN": "Đang chờ phê duyệt",
        "zh-CN": "等待批准",
        "zh-SG": "等待批准",
        "zh-TW": "等待核准",
      },
      description: "Tool state badge: approval requested.",
    },
    "ai-chat-tool-approval-responded": {
      defaultValue: "Approval responded",
      translations: {
        "ar-AE": "تمت الاستجابة للموافقة",
        "ar-BH": "تمت الاستجابة للموافقة",
        "ar-DZ": "تمت الاستجابة للموافقة",
        "ar-EG": "تمت الاستجابة للموافقة",
        "ar-IQ": "تمت الاستجابة للموافقة",
        "ar-JO": "تمت الاستجابة للموافقة",
        "ar-KW": "تمت الاستجابة للموافقة",
        "ar-LB": "تمت الاستجابة للموافقة",
        "ar-LY": "تمت الاستجابة للموافقة",
        "ar-MA": "تمت الاستجابة للموافقة",
        "ar-OM": "تمت الاستجابة للموافقة",
        "ar-QA": "تمت الاستجابة للموافقة",
        "ar-SA": "تمت الاستجابة للموافقة",
        "ar-SY": "تمت الاستجابة للموافقة",
        "ar-TN": "تمت الاستجابة للموافقة",
        "ar-YE": "تمت الاستجابة للموافقة",
        "cs-CZ": "Na schválení odpovězeno",
        da: "Godkendelse besvaret",
        "de-AT": "Genehmigung beantwortet",
        "de-CH": "Genehmigung beantwortet",
        "de-DE": "Genehmigung beantwortet",
        "de-LI": "Genehmigung beantwortet",
        "de-LU": "Genehmigung beantwortet",
        "el-GR": "Απάντηση έγκρισης",
        "en-AU": "Approval responded",
        "en-BZ": "Approval responded",
        "en-CA": "Approval responded",
        "en-GB": "Approval responded",
        "en-IE": "Approval responded",
        "en-JM": "Approval responded",
        "en-NZ": "Approval responded",
        "en-PH": "Approval responded",
        "en-TT": "Approval responded",
        "en-US": "Approval responded",
        "en-ZA": "Approval responded",
        "en-ZW": "Approval responded",
        "es-AR": "Aprobación respondida",
        "es-BO": "Aprobación respondida",
        "es-CL": "Aprobación respondida",
        "es-CO": "Aprobación respondida",
        "es-CR": "Aprobación respondida",
        "es-DO": "Aprobación respondida",
        "es-EC": "Aprobación respondida",
        "es-ES": "Aprobación respondida",
        "es-GT": "Aprobación respondida",
        "es-HN": "Aprobación respondida",
        "es-MX": "Aprobación respondida",
        "es-NI": "Aprobación respondida",
        "es-PA": "Aprobación respondida",
        "es-PE": "Aprobación respondida",
        "es-PR": "Aprobación respondida",
        "es-PY": "Aprobación respondida",
        "es-SV": "Aprobación respondida",
        "es-UY": "Aprobación respondida",
        "es-VE": "Aprobación respondida",
        "fi-FI": "Hyväksyntään vastattu",
        "fr-BE": "Approbation traitée",
        "fr-CA": "Approbation traitée",
        "fr-CH": "Approbation traitée",
        "fr-FR": "Approbation traitée",
        "fr-LU": "Approbation traitée",
        "fr-MC": "Approbation traitée",
        "he-IL": "האישור נענה",
        "hi-IN": "अनुमोदन का उत्तर दिया",
        "hu-HU": "Jóváhagyás megválaszolva",
        "id-ID": "Persetujuan ditanggapi",
        "it-CH": "Approvazione elaborata",
        "it-IT": "Approvazione elaborata",
        "ja-JP": "承認に応答済み",
        "ko-KR": "승인 응답됨",
        "nb-NO": "Godkjenning besvart",
        "nl-BE": "Goedkeuring beantwoord",
        "nl-NL": "Goedkeuring beantwoord",
        "pl-PL": "Odpowiedziano na zatwierdzenie",
        "pt-BR": "Aprovação respondida",
        "pt-PT": "Aprovação respondida",
        "ro-RO": "Aprobare procesată",
        "ru-RU": "Ответ на одобрение получен",
        "sk-SK": "Na schválenie odpovedané",
        "sv-FI": "Godkännande besvarat",
        "sv-SE": "Godkännande besvarat",
        "th-TH": "ตอบกลับการอนุมัติแล้ว",
        "tr-TR": "Onay yanıtlandı",
        "uk-UA": "Відповідь на схвалення надано",
        "vi-VN": "Đã phản hồi phê duyệt",
        "zh-CN": "已回应批准",
        "zh-SG": "已回应批准",
        "zh-TW": "已回應核准",
      },
      description: "Tool state badge: approval responded.",
    },
    "ai-chat-tool-denied": {
      defaultValue: "Denied",
      translations: {
        "ar-AE": "مرفوض",
        "ar-BH": "مرفوض",
        "ar-DZ": "مرفوض",
        "ar-EG": "مرفوض",
        "ar-IQ": "مرفوض",
        "ar-JO": "مرفوض",
        "ar-KW": "مرفوض",
        "ar-LB": "مرفوض",
        "ar-LY": "مرفوض",
        "ar-MA": "مرفوض",
        "ar-OM": "مرفوض",
        "ar-QA": "مرفوض",
        "ar-SA": "مرفوض",
        "ar-SY": "مرفوض",
        "ar-TN": "مرفوض",
        "ar-YE": "مرفوض",
        "cs-CZ": "Zamítnuto",
        da: "Afvist",
        "de-AT": "Abgelehnt",
        "de-CH": "Abgelehnt",
        "de-DE": "Abgelehnt",
        "de-LI": "Abgelehnt",
        "de-LU": "Abgelehnt",
        "el-GR": "Απορρίφθηκε",
        "en-AU": "Denied",
        "en-BZ": "Denied",
        "en-CA": "Denied",
        "en-GB": "Denied",
        "en-IE": "Denied",
        "en-JM": "Denied",
        "en-NZ": "Denied",
        "en-PH": "Denied",
        "en-TT": "Denied",
        "en-US": "Denied",
        "en-ZA": "Denied",
        "en-ZW": "Denied",
        "es-AR": "Denegado",
        "es-BO": "Denegado",
        "es-CL": "Denegado",
        "es-CO": "Denegado",
        "es-CR": "Denegado",
        "es-DO": "Denegado",
        "es-EC": "Denegado",
        "es-ES": "Denegado",
        "es-GT": "Denegado",
        "es-HN": "Denegado",
        "es-MX": "Denegado",
        "es-NI": "Denegado",
        "es-PA": "Denegado",
        "es-PE": "Denegado",
        "es-PR": "Denegado",
        "es-PY": "Denegado",
        "es-SV": "Denegado",
        "es-UY": "Denegado",
        "es-VE": "Denegado",
        "fi-FI": "Evätty",
        "fr-BE": "Refusé",
        "fr-CA": "Refusé",
        "fr-CH": "Refusé",
        "fr-FR": "Refusé",
        "fr-LU": "Refusé",
        "fr-MC": "Refusé",
        "he-IL": "נדחה",
        "hi-IN": "अस्वीकृत",
        "hu-HU": "Elutasítva",
        "id-ID": "Ditolak",
        "it-CH": "Negato",
        "it-IT": "Negato",
        "ja-JP": "拒否済み",
        "ko-KR": "거부됨",
        "nb-NO": "Avvist",
        "nl-BE": "Geweigerd",
        "nl-NL": "Geweigerd",
        "pl-PL": "Odrzucono",
        "pt-BR": "Negado",
        "pt-PT": "Recusado",
        "ro-RO": "Respins",
        "ru-RU": "Отклонено",
        "sk-SK": "Zamietnuté",
        "sv-FI": "Nekad",
        "sv-SE": "Nekad",
        "th-TH": "ปฏิเสธ",
        "tr-TR": "Reddedildi",
        "uk-UA": "Відхилено",
        "vi-VN": "Đã từ chối",
        "zh-CN": "已拒绝",
        "zh-SG": "已拒绝",
        "zh-TW": "已拒絕",
      },
      description: "Tool state badge: output denied.",
    },
  },
} satisfies DictionaryRecipe;

export default aiChatUiLabelsToolsRecipe;
