import type { DictionaryRecipe } from "@sitecoreai-labs/sitecoreai-cli/recipe";

/**
 * AI Chat UI Labels — Composer — a shard of the AI Chat UI Labels phrase library, split so no
 * single Dictionary recipe pushes more item versions than one sandbox can
 * apply. Phrase keys are unchanged; only which recipe authors them differs.
 */
export const aiChatUiLabelsComposerRecipe = {
  kind: "dictionary",
  schemaVersion: "1",
  handle: "ai-chat-ui-labels-composer@1",
  name: "AiChatUiLabelsComposer",
  displayName: "AI Chat UI Labels — Composer",
  description:
    "AI Chat dictionary shard — composer region: input, attach, dictation, stop, and streaming-status phrases. Keep the single-brace {name} token in ai-chat-remove-attachment intact in every translation.",
  primaryLocale: "en",
  phrases: {
    "ai-chat-send": {
      defaultValue: "Send",
      translations: {
        "ar-AE": "إرسال",
        "ar-BH": "إرسال",
        "ar-DZ": "إرسال",
        "ar-EG": "إرسال",
        "ar-IQ": "إرسال",
        "ar-JO": "إرسال",
        "ar-KW": "إرسال",
        "ar-LB": "إرسال",
        "ar-LY": "إرسال",
        "ar-MA": "إرسال",
        "ar-OM": "إرسال",
        "ar-QA": "إرسال",
        "ar-SA": "إرسال",
        "ar-SY": "إرسال",
        "ar-TN": "إرسال",
        "ar-YE": "إرسال",
        "cs-CZ": "Odeslat",
        da: "Send",
        "de-AT": "Senden",
        "de-CH": "Senden",
        "de-DE": "Senden",
        "de-LI": "Senden",
        "de-LU": "Senden",
        "el-GR": "Αποστολή",
        "en-AU": "Send",
        "en-BZ": "Send",
        "en-CA": "Send",
        "en-GB": "Send",
        "en-IE": "Send",
        "en-JM": "Send",
        "en-NZ": "Send",
        "en-PH": "Send",
        "en-TT": "Send",
        "en-US": "Send",
        "en-ZA": "Send",
        "en-ZW": "Send",
        "es-AR": "Enviar",
        "es-BO": "Enviar",
        "es-CL": "Enviar",
        "es-CO": "Enviar",
        "es-CR": "Enviar",
        "es-DO": "Enviar",
        "es-EC": "Enviar",
        "es-ES": "Enviar",
        "es-GT": "Enviar",
        "es-HN": "Enviar",
        "es-MX": "Enviar",
        "es-NI": "Enviar",
        "es-PA": "Enviar",
        "es-PE": "Enviar",
        "es-PR": "Enviar",
        "es-PY": "Enviar",
        "es-SV": "Enviar",
        "es-UY": "Enviar",
        "es-VE": "Enviar",
        "fi-FI": "Lähetä",
        "fr-BE": "Envoyer",
        "fr-CA": "Envoyer",
        "fr-CH": "Envoyer",
        "fr-FR": "Envoyer",
        "fr-LU": "Envoyer",
        "fr-MC": "Envoyer",
        "he-IL": "שליחה",
        "hi-IN": "भेजें",
        "hu-HU": "Küldés",
        "id-ID": "Kirim",
        "it-CH": "Invia",
        "it-IT": "Invia",
        "ja-JP": "送信",
        "ko-KR": "보내기",
        "nb-NO": "Send",
        "nl-BE": "Verzenden",
        "nl-NL": "Verzenden",
        "pl-PL": "Wyślij",
        "pt-BR": "Enviar",
        "pt-PT": "Enviar",
        "ro-RO": "Trimite",
        "ru-RU": "Отправить",
        "sk-SK": "Odoslať",
        "sv-FI": "Skicka",
        "sv-SE": "Skicka",
        "th-TH": "ส่ง",
        "tr-TR": "Gönder",
        "uk-UA": "Надіслати",
        "vi-VN": "Gửi",
        "zh-CN": "发送",
        "zh-SG": "发送",
        "zh-TW": "傳送",
      },
      description: "Composer send button label.",
    },
    "ai-chat-composer-aria": {
      defaultValue: "Chat message",
      translations: {
        "ar-AE": "رسالة الدردشة",
        "ar-BH": "رسالة الدردشة",
        "ar-DZ": "رسالة الدردشة",
        "ar-EG": "رسالة الدردشة",
        "ar-IQ": "رسالة الدردشة",
        "ar-JO": "رسالة الدردشة",
        "ar-KW": "رسالة الدردشة",
        "ar-LB": "رسالة الدردشة",
        "ar-LY": "رسالة الدردشة",
        "ar-MA": "رسالة الدردشة",
        "ar-OM": "رسالة الدردشة",
        "ar-QA": "رسالة الدردشة",
        "ar-SA": "رسالة الدردشة",
        "ar-SY": "رسالة الدردشة",
        "ar-TN": "رسالة الدردشة",
        "ar-YE": "رسالة الدردشة",
        "cs-CZ": "Zpráva chatu",
        da: "Chatbesked",
        "de-AT": "Chatnachricht",
        "de-CH": "Chatnachricht",
        "de-DE": "Chatnachricht",
        "de-LI": "Chatnachricht",
        "de-LU": "Chatnachricht",
        "el-GR": "Μήνυμα συνομιλίας",
        "en-AU": "Chat message",
        "en-BZ": "Chat message",
        "en-CA": "Chat message",
        "en-GB": "Chat message",
        "en-IE": "Chat message",
        "en-JM": "Chat message",
        "en-NZ": "Chat message",
        "en-PH": "Chat message",
        "en-TT": "Chat message",
        "en-US": "Chat message",
        "en-ZA": "Chat message",
        "en-ZW": "Chat message",
        "es-AR": "Mensaje de chat",
        "es-BO": "Mensaje de chat",
        "es-CL": "Mensaje de chat",
        "es-CO": "Mensaje de chat",
        "es-CR": "Mensaje de chat",
        "es-DO": "Mensaje de chat",
        "es-EC": "Mensaje de chat",
        "es-ES": "Mensaje de chat",
        "es-GT": "Mensaje de chat",
        "es-HN": "Mensaje de chat",
        "es-MX": "Mensaje de chat",
        "es-NI": "Mensaje de chat",
        "es-PA": "Mensaje de chat",
        "es-PE": "Mensaje de chat",
        "es-PR": "Mensaje de chat",
        "es-PY": "Mensaje de chat",
        "es-SV": "Mensaje de chat",
        "es-UY": "Mensaje de chat",
        "es-VE": "Mensaje de chat",
        "fi-FI": "Chat-viesti",
        "fr-BE": "Message de chat",
        "fr-CA": "Message de chat",
        "fr-CH": "Message de chat",
        "fr-FR": "Message de chat",
        "fr-LU": "Message de chat",
        "fr-MC": "Message de chat",
        "he-IL": "הודעת צ'אט",
        "hi-IN": "चैट संदेश",
        "hu-HU": "Csevegőüzenet",
        "id-ID": "Pesan obrolan",
        "it-CH": "Messaggio della chat",
        "it-IT": "Messaggio della chat",
        "ja-JP": "チャットメッセージ",
        "ko-KR": "채팅 메시지",
        "nb-NO": "Chatmelding",
        "nl-BE": "Chatbericht",
        "nl-NL": "Chatbericht",
        "pl-PL": "Wiadomość czatu",
        "pt-BR": "Mensagem de chat",
        "pt-PT": "Mensagem de chat",
        "ro-RO": "Mesaj de chat",
        "ru-RU": "Сообщение чата",
        "sk-SK": "Správa četu",
        "sv-FI": "Chattmeddelande",
        "sv-SE": "Chattmeddelande",
        "th-TH": "ข้อความแชท",
        "tr-TR": "Sohbet mesajı",
        "uk-UA": "Повідомлення чату",
        "vi-VN": "Tin nhắn trò chuyện",
        "zh-CN": "聊天消息",
        "zh-SG": "聊天消息",
        "zh-TW": "聊天訊息",
      },
      description: "Screen-reader label for the composer textarea.",
    },
    "ai-chat-listening-placeholder": {
      defaultValue: "Listening…",
      translations: {
        "ar-AE": "جارٍ الاستماع…",
        "ar-BH": "جارٍ الاستماع…",
        "ar-DZ": "جارٍ الاستماع…",
        "ar-EG": "جارٍ الاستماع…",
        "ar-IQ": "جارٍ الاستماع…",
        "ar-JO": "جارٍ الاستماع…",
        "ar-KW": "جارٍ الاستماع…",
        "ar-LB": "جارٍ الاستماع…",
        "ar-LY": "جارٍ الاستماع…",
        "ar-MA": "جارٍ الاستماع…",
        "ar-OM": "جارٍ الاستماع…",
        "ar-QA": "جارٍ الاستماع…",
        "ar-SA": "جارٍ الاستماع…",
        "ar-SY": "جارٍ الاستماع…",
        "ar-TN": "جارٍ الاستماع…",
        "ar-YE": "جارٍ الاستماع…",
        "cs-CZ": "Poslouchám…",
        da: "Lytter…",
        "de-AT": "Höre zu…",
        "de-CH": "Höre zu…",
        "de-DE": "Höre zu…",
        "de-LI": "Höre zu…",
        "de-LU": "Höre zu…",
        "el-GR": "Ακούω…",
        "en-AU": "Listening…",
        "en-BZ": "Listening…",
        "en-CA": "Listening…",
        "en-GB": "Listening…",
        "en-IE": "Listening…",
        "en-JM": "Listening…",
        "en-NZ": "Listening…",
        "en-PH": "Listening…",
        "en-TT": "Listening…",
        "en-US": "Listening…",
        "en-ZA": "Listening…",
        "en-ZW": "Listening…",
        "es-AR": "Escuchando…",
        "es-BO": "Escuchando…",
        "es-CL": "Escuchando…",
        "es-CO": "Escuchando…",
        "es-CR": "Escuchando…",
        "es-DO": "Escuchando…",
        "es-EC": "Escuchando…",
        "es-ES": "Escuchando…",
        "es-GT": "Escuchando…",
        "es-HN": "Escuchando…",
        "es-MX": "Escuchando…",
        "es-NI": "Escuchando…",
        "es-PA": "Escuchando…",
        "es-PE": "Escuchando…",
        "es-PR": "Escuchando…",
        "es-PY": "Escuchando…",
        "es-SV": "Escuchando…",
        "es-UY": "Escuchando…",
        "es-VE": "Escuchando…",
        "fi-FI": "Kuuntelee…",
        "fr-BE": "Écoute…",
        "fr-CA": "Écoute…",
        "fr-CH": "Écoute…",
        "fr-FR": "Écoute…",
        "fr-LU": "Écoute…",
        "fr-MC": "Écoute…",
        "he-IL": "מקשיב…",
        "hi-IN": "सुन रहा है…",
        "hu-HU": "Hallgatom…",
        "id-ID": "Mendengarkan…",
        "it-CH": "In ascolto…",
        "it-IT": "In ascolto…",
        "ja-JP": "音声認識中…",
        "ko-KR": "듣는 중…",
        "nb-NO": "Lytter…",
        "nl-BE": "Luistert…",
        "nl-NL": "Luistert…",
        "pl-PL": "Słucham…",
        "pt-BR": "Ouvindo…",
        "pt-PT": "A ouvir…",
        "ro-RO": "Ascult…",
        "ru-RU": "Слушаю…",
        "sk-SK": "Počúvam…",
        "sv-FI": "Lyssnar…",
        "sv-SE": "Lyssnar…",
        "th-TH": "กำลังฟัง…",
        "tr-TR": "Dinleniyor…",
        "uk-UA": "Слухаю…",
        "vi-VN": "Đang nghe…",
        "zh-CN": "正在聆听…",
        "zh-SG": "正在聆听…",
        "zh-TW": "正在聆聽…",
      },
      description: "Composer placeholder shown while dictation is recording.",
    },
    "ai-chat-composer-hint": {
      defaultValue: "Enter to send · Shift+Enter for newline",
      translations: {
        "ar-AE": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-BH": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-DZ": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-EG": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-IQ": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-JO": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-KW": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-LB": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-LY": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-MA": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-OM": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-QA": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-SA": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-SY": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-TN": "Enter للإرسال · Shift+Enter لسطر جديد",
        "ar-YE": "Enter للإرسال · Shift+Enter لسطر جديد",
        "cs-CZ": "Enter odešle · Shift+Enter nový řádek",
        da: "Enter for at sende · Shift+Enter for ny linje",
        "de-AT": "Enter zum Senden · Umschalt+Enter für neue Zeile",
        "de-CH": "Enter zum Senden · Umschalt+Enter für neue Zeile",
        "de-DE": "Enter zum Senden · Umschalt+Enter für neue Zeile",
        "de-LI": "Enter zum Senden · Umschalt+Enter für neue Zeile",
        "de-LU": "Enter zum Senden · Umschalt+Enter für neue Zeile",
        "el-GR": "Enter για αποστολή · Shift+Enter για νέα γραμμή",
        "en-AU": "Enter to send · Shift+Enter for newline",
        "en-BZ": "Enter to send · Shift+Enter for newline",
        "en-CA": "Enter to send · Shift+Enter for newline",
        "en-GB": "Enter to send · Shift+Enter for newline",
        "en-IE": "Enter to send · Shift+Enter for newline",
        "en-JM": "Enter to send · Shift+Enter for newline",
        "en-NZ": "Enter to send · Shift+Enter for newline",
        "en-PH": "Enter to send · Shift+Enter for newline",
        "en-TT": "Enter to send · Shift+Enter for newline",
        "en-US": "Enter to send · Shift+Enter for newline",
        "en-ZA": "Enter to send · Shift+Enter for newline",
        "en-ZW": "Enter to send · Shift+Enter for newline",
        "es-AR": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-BO": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-CL": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-CO": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-CR": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-DO": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-EC": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-ES": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-GT": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-HN": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-MX": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-NI": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-PA": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-PE": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-PR": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-PY": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-SV": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-UY": "Intro para enviar · Mayús+Intro para nueva línea",
        "es-VE": "Intro para enviar · Mayús+Intro para nueva línea",
        "fi-FI": "Enter lähettää · Shift+Enter rivinvaihto",
        "fr-BE": "Entrée pour envoyer · Maj+Entrée pour un saut de ligne",
        "fr-CA": "Entrée pour envoyer · Maj+Entrée pour un saut de ligne",
        "fr-CH": "Entrée pour envoyer · Maj+Entrée pour un saut de ligne",
        "fr-FR": "Entrée pour envoyer · Maj+Entrée pour un saut de ligne",
        "fr-LU": "Entrée pour envoyer · Maj+Entrée pour un saut de ligne",
        "fr-MC": "Entrée pour envoyer · Maj+Entrée pour un saut de ligne",
        "he-IL": "Enter לשליחה · Shift+Enter לשורה חדשה",
        "hi-IN": "भेजने के लिए Enter · नई लाइन के लिए Shift+Enter",
        "hu-HU": "Enter a küldéshez · Shift+Enter új sorhoz",
        "id-ID": "Enter untuk mengirim · Shift+Enter untuk baris baru",
        "it-CH": "Invio per inviare · Maiusc+Invio per andare a capo",
        "it-IT": "Invio per inviare · Maiusc+Invio per andare a capo",
        "ja-JP": "Enter で送信 · Shift+Enter で改行",
        "ko-KR": "Enter로 보내기 · Shift+Enter로 줄 바꿈",
        "nb-NO": "Enter for å sende · Shift+Enter for ny linje",
        "nl-BE": "Enter om te verzenden · Shift+Enter voor nieuwe regel",
        "nl-NL": "Enter om te verzenden · Shift+Enter voor nieuwe regel",
        "pl-PL": "Enter wysyła · Shift+Enter nowa linia",
        "pt-BR": "Enter para enviar · Shift+Enter para nova linha",
        "pt-PT": "Enter para enviar · Shift+Enter para nova linha",
        "ro-RO": "Enter pentru trimitere · Shift+Enter pentru rând nou",
        "ru-RU": "Enter — отправить · Shift+Enter — новая строка",
        "sk-SK": "Enter odošle · Shift+Enter nový riadok",
        "sv-FI": "Enter för att skicka · Shift+Enter för ny rad",
        "sv-SE": "Enter för att skicka · Shift+Enter för ny rad",
        "th-TH": "Enter เพื่อส่ง · Shift+Enter เพื่อขึ้นบรรทัดใหม่",
        "tr-TR": "Göndermek için Enter · Yeni satır için Shift+Enter",
        "uk-UA": "Enter — надіслати · Shift+Enter — новий рядок",
        "vi-VN": "Enter để gửi · Shift+Enter để xuống dòng",
        "zh-CN": "Enter 发送 · Shift+Enter 换行",
        "zh-SG": "Enter 发送 · Shift+Enter 换行",
        "zh-TW": "Enter 傳送 · Shift+Enter 換行",
      },
      description: "Keyboard hint below the composer.",
    },
    "ai-chat-listening-hint": {
      defaultValue: "Listening — click the mic to stop.",
      translations: {
        "ar-AE": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-BH": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-DZ": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-EG": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-IQ": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-JO": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-KW": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-LB": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-LY": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-MA": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-OM": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-QA": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-SA": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-SY": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-TN": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "ar-YE": "جارٍ الاستماع — انقر على الميكروفون للإيقاف.",
        "cs-CZ": "Poslouchám — kliknutím na mikrofon zastavíte.",
        da: "Lytter — klik på mikrofonen for at stoppe.",
        "de-AT": "Höre zu — zum Stoppen aufs Mikrofon klicken.",
        "de-CH": "Höre zu — zum Stoppen aufs Mikrofon klicken.",
        "de-DE": "Höre zu — zum Stoppen aufs Mikrofon klicken.",
        "de-LI": "Höre zu — zum Stoppen aufs Mikrofon klicken.",
        "de-LU": "Höre zu — zum Stoppen aufs Mikrofon klicken.",
        "el-GR": "Ακούω — κάντε κλικ στο μικρόφωνο για διακοπή.",
        "en-AU": "Listening — click the mic to stop.",
        "en-BZ": "Listening — click the mic to stop.",
        "en-CA": "Listening — click the mic to stop.",
        "en-GB": "Listening — click the mic to stop.",
        "en-IE": "Listening — click the mic to stop.",
        "en-JM": "Listening — click the mic to stop.",
        "en-NZ": "Listening — click the mic to stop.",
        "en-PH": "Listening — click the mic to stop.",
        "en-TT": "Listening — click the mic to stop.",
        "en-US": "Listening — click the mic to stop.",
        "en-ZA": "Listening — click the mic to stop.",
        "en-ZW": "Listening — click the mic to stop.",
        "es-AR": "Escuchando — haz clic en el micrófono para detener.",
        "es-BO": "Escuchando — haz clic en el micrófono para detener.",
        "es-CL": "Escuchando — haz clic en el micrófono para detener.",
        "es-CO": "Escuchando — haz clic en el micrófono para detener.",
        "es-CR": "Escuchando — haz clic en el micrófono para detener.",
        "es-DO": "Escuchando — haz clic en el micrófono para detener.",
        "es-EC": "Escuchando — haz clic en el micrófono para detener.",
        "es-ES": "Escuchando — haz clic en el micrófono para detener.",
        "es-GT": "Escuchando — haz clic en el micrófono para detener.",
        "es-HN": "Escuchando — haz clic en el micrófono para detener.",
        "es-MX": "Escuchando — haz clic en el micrófono para detener.",
        "es-NI": "Escuchando — haz clic en el micrófono para detener.",
        "es-PA": "Escuchando — haz clic en el micrófono para detener.",
        "es-PE": "Escuchando — haz clic en el micrófono para detener.",
        "es-PR": "Escuchando — haz clic en el micrófono para detener.",
        "es-PY": "Escuchando — haz clic en el micrófono para detener.",
        "es-SV": "Escuchando — haz clic en el micrófono para detener.",
        "es-UY": "Escuchando — haz clic en el micrófono para detener.",
        "es-VE": "Escuchando — haz clic en el micrófono para detener.",
        "fi-FI": "Kuuntelee — lopeta napsauttamalla mikrofonia.",
        "fr-BE": "Écoute — cliquez sur le micro pour arrêter.",
        "fr-CA": "Écoute — cliquez sur le micro pour arrêter.",
        "fr-CH": "Écoute — cliquez sur le micro pour arrêter.",
        "fr-FR": "Écoute — cliquez sur le micro pour arrêter.",
        "fr-LU": "Écoute — cliquez sur le micro pour arrêter.",
        "fr-MC": "Écoute — cliquez sur le micro pour arrêter.",
        "he-IL": "מקשיב — לחץ על המיקרופון כדי לעצור.",
        "hi-IN": "सुन रहा है — रोकने के लिए माइक पर क्लिक करें.",
        "hu-HU": "Hallgatom — a leállításhoz kattints a mikrofonra.",
        "id-ID": "Mendengarkan — klik mikrofon untuk berhenti.",
        "it-CH": "In ascolto — fai clic sul microfono per interrompere.",
        "it-IT": "In ascolto — fai clic sul microfono per interrompere.",
        "ja-JP": "音声認識中 — 停止するにはマイクをクリックします。",
        "ko-KR": "듣는 중 — 중지하려면 마이크를 클릭하세요.",
        "nb-NO": "Lytter — klikk på mikrofonen for å stoppe.",
        "nl-BE": "Luistert — klik op de microfoon om te stoppen.",
        "nl-NL": "Luistert — klik op de microfoon om te stoppen.",
        "pl-PL": "Słucham — kliknij mikrofon, aby zatrzymać.",
        "pt-BR": "Ouvindo — clique no microfone para parar.",
        "pt-PT": "A ouvir — clique no microfone para parar.",
        "ro-RO": "Ascult — dă clic pe microfon pentru a opri.",
        "ru-RU": "Слушаю — нажмите на микрофон, чтобы остановить.",
        "sk-SK": "Počúvam — kliknutím na mikrofón zastavíte.",
        "sv-FI": "Lyssnar — klicka på mikrofonen för att stoppa.",
        "sv-SE": "Lyssnar — klicka på mikrofonen för att stoppa.",
        "th-TH": "กำลังฟัง — คลิกไมโครโฟนเพื่อหยุด",
        "tr-TR": "Dinleniyor — durdurmak için mikrofona tıklayın.",
        "uk-UA": "Слухаю — натисніть мікрофон, щоб зупинити.",
        "vi-VN": "Đang nghe — nhấp vào micrô để dừng.",
        "zh-CN": "正在聆听 — 点击麦克风停止。",
        "zh-SG": "正在聆听 — 点击麦克风停止。",
        "zh-TW": "正在聆聽 — 點擊麥克風停止。",
      },
      description: "Replaces the keyboard hint while dictation is active.",
    },
    "ai-chat-attach": {
      defaultValue: "Attach files",
      translations: {
        "ar-AE": "إرفاق ملفات",
        "ar-BH": "إرفاق ملفات",
        "ar-DZ": "إرفاق ملفات",
        "ar-EG": "إرفاق ملفات",
        "ar-IQ": "إرفاق ملفات",
        "ar-JO": "إرفاق ملفات",
        "ar-KW": "إرفاق ملفات",
        "ar-LB": "إرفاق ملفات",
        "ar-LY": "إرفاق ملفات",
        "ar-MA": "إرفاق ملفات",
        "ar-OM": "إرفاق ملفات",
        "ar-QA": "إرفاق ملفات",
        "ar-SA": "إرفاق ملفات",
        "ar-SY": "إرفاق ملفات",
        "ar-TN": "إرفاق ملفات",
        "ar-YE": "إرفاق ملفات",
        "cs-CZ": "Připojit soubory",
        da: "Vedhæft filer",
        "de-AT": "Dateien anhängen",
        "de-CH": "Dateien anhängen",
        "de-DE": "Dateien anhängen",
        "de-LI": "Dateien anhängen",
        "de-LU": "Dateien anhängen",
        "el-GR": "Επισύναψη αρχείων",
        "en-AU": "Attach files",
        "en-BZ": "Attach files",
        "en-CA": "Attach files",
        "en-GB": "Attach files",
        "en-IE": "Attach files",
        "en-JM": "Attach files",
        "en-NZ": "Attach files",
        "en-PH": "Attach files",
        "en-TT": "Attach files",
        "en-US": "Attach files",
        "en-ZA": "Attach files",
        "en-ZW": "Attach files",
        "es-AR": "Adjuntar archivos",
        "es-BO": "Adjuntar archivos",
        "es-CL": "Adjuntar archivos",
        "es-CO": "Adjuntar archivos",
        "es-CR": "Adjuntar archivos",
        "es-DO": "Adjuntar archivos",
        "es-EC": "Adjuntar archivos",
        "es-ES": "Adjuntar archivos",
        "es-GT": "Adjuntar archivos",
        "es-HN": "Adjuntar archivos",
        "es-MX": "Adjuntar archivos",
        "es-NI": "Adjuntar archivos",
        "es-PA": "Adjuntar archivos",
        "es-PE": "Adjuntar archivos",
        "es-PR": "Adjuntar archivos",
        "es-PY": "Adjuntar archivos",
        "es-SV": "Adjuntar archivos",
        "es-UY": "Adjuntar archivos",
        "es-VE": "Adjuntar archivos",
        "fi-FI": "Liitä tiedostoja",
        "fr-BE": "Joindre des fichiers",
        "fr-CA": "Joindre des fichiers",
        "fr-CH": "Joindre des fichiers",
        "fr-FR": "Joindre des fichiers",
        "fr-LU": "Joindre des fichiers",
        "fr-MC": "Joindre des fichiers",
        "he-IL": "צירוף קבצים",
        "hi-IN": "फ़ाइलें अटैच करें",
        "hu-HU": "Fájlok csatolása",
        "id-ID": "Lampirkan file",
        "it-CH": "Allega file",
        "it-IT": "Allega file",
        "ja-JP": "ファイルを添付",
        "ko-KR": "파일 첨부",
        "nb-NO": "Legg ved filer",
        "nl-BE": "Bestanden bijvoegen",
        "nl-NL": "Bestanden bijvoegen",
        "pl-PL": "Załącz pliki",
        "pt-BR": "Anexar arquivos",
        "pt-PT": "Anexar ficheiros",
        "ro-RO": "Atașează fișiere",
        "ru-RU": "Прикрепить файлы",
        "sk-SK": "Priložiť súbory",
        "sv-FI": "Bifoga filer",
        "sv-SE": "Bifoga filer",
        "th-TH": "แนบไฟล์",
        "tr-TR": "Dosya ekle",
        "uk-UA": "Прикріпити файли",
        "vi-VN": "Đính kèm tệp",
        "zh-CN": "附加文件",
        "zh-SG": "附加文件",
        "zh-TW": "附加檔案",
      },
      description: "Aria-label for the paperclip attach button.",
    },
    "ai-chat-attach-hint": {
      defaultValue: "Attach files for context",
      translations: {
        "ar-AE": "إرفاق ملفات كسياق",
        "ar-BH": "إرفاق ملفات كسياق",
        "ar-DZ": "إرفاق ملفات كسياق",
        "ar-EG": "إرفاق ملفات كسياق",
        "ar-IQ": "إرفاق ملفات كسياق",
        "ar-JO": "إرفاق ملفات كسياق",
        "ar-KW": "إرفاق ملفات كسياق",
        "ar-LB": "إرفاق ملفات كسياق",
        "ar-LY": "إرفاق ملفات كسياق",
        "ar-MA": "إرفاق ملفات كسياق",
        "ar-OM": "إرفاق ملفات كسياق",
        "ar-QA": "إرفاق ملفات كسياق",
        "ar-SA": "إرفاق ملفات كسياق",
        "ar-SY": "إرفاق ملفات كسياق",
        "ar-TN": "إرفاق ملفات كسياق",
        "ar-YE": "إرفاق ملفات كسياق",
        "cs-CZ": "Připojit soubory jako kontext",
        da: "Vedhæft filer som kontekst",
        "de-AT": "Dateien als Kontext anhängen",
        "de-CH": "Dateien als Kontext anhängen",
        "de-DE": "Dateien als Kontext anhängen",
        "de-LI": "Dateien als Kontext anhängen",
        "de-LU": "Dateien als Kontext anhängen",
        "el-GR": "Επισύναψη αρχείων ως πλαίσιο",
        "en-AU": "Attach files for context",
        "en-BZ": "Attach files for context",
        "en-CA": "Attach files for context",
        "en-GB": "Attach files for context",
        "en-IE": "Attach files for context",
        "en-JM": "Attach files for context",
        "en-NZ": "Attach files for context",
        "en-PH": "Attach files for context",
        "en-TT": "Attach files for context",
        "en-US": "Attach files for context",
        "en-ZA": "Attach files for context",
        "en-ZW": "Attach files for context",
        "es-AR": "Adjuntar archivos como contexto",
        "es-BO": "Adjuntar archivos como contexto",
        "es-CL": "Adjuntar archivos como contexto",
        "es-CO": "Adjuntar archivos como contexto",
        "es-CR": "Adjuntar archivos como contexto",
        "es-DO": "Adjuntar archivos como contexto",
        "es-EC": "Adjuntar archivos como contexto",
        "es-ES": "Adjuntar archivos como contexto",
        "es-GT": "Adjuntar archivos como contexto",
        "es-HN": "Adjuntar archivos como contexto",
        "es-MX": "Adjuntar archivos como contexto",
        "es-NI": "Adjuntar archivos como contexto",
        "es-PA": "Adjuntar archivos como contexto",
        "es-PE": "Adjuntar archivos como contexto",
        "es-PR": "Adjuntar archivos como contexto",
        "es-PY": "Adjuntar archivos como contexto",
        "es-SV": "Adjuntar archivos como contexto",
        "es-UY": "Adjuntar archivos como contexto",
        "es-VE": "Adjuntar archivos como contexto",
        "fi-FI": "Liitä tiedostoja kontekstiksi",
        "fr-BE": "Joindre des fichiers comme contexte",
        "fr-CA": "Joindre des fichiers comme contexte",
        "fr-CH": "Joindre des fichiers comme contexte",
        "fr-FR": "Joindre des fichiers comme contexte",
        "fr-LU": "Joindre des fichiers comme contexte",
        "fr-MC": "Joindre des fichiers comme contexte",
        "he-IL": "צירוף קבצים כהקשר",
        "hi-IN": "संदर्भ के लिए फ़ाइलें अटैच करें",
        "hu-HU": "Fájlok csatolása kontextusként",
        "id-ID": "Lampirkan file sebagai konteks",
        "it-CH": "Allega file come contesto",
        "it-IT": "Allega file come contesto",
        "ja-JP": "コンテキストとしてファイルを添付",
        "ko-KR": "컨텍스트로 파일 첨부",
        "nb-NO": "Legg ved filer som kontekst",
        "nl-BE": "Bestanden als context bijvoegen",
        "nl-NL": "Bestanden als context bijvoegen",
        "pl-PL": "Załącz pliki jako kontekst",
        "pt-BR": "Anexar arquivos como contexto",
        "pt-PT": "Anexar ficheiros como contexto",
        "ro-RO": "Atașează fișiere ca context",
        "ru-RU": "Прикрепить файлы для контекста",
        "sk-SK": "Priložiť súbory ako kontext",
        "sv-FI": "Bifoga filer som kontext",
        "sv-SE": "Bifoga filer som kontext",
        "th-TH": "แนบไฟล์เป็นบริบท",
        "tr-TR": "Bağlam için dosya ekle",
        "uk-UA": "Прикріпити файли як контекст",
        "vi-VN": "Đính kèm tệp làm ngữ cảnh",
        "zh-CN": "附加文件作为上下文",
        "zh-SG": "附加文件作为上下文",
        "zh-TW": "附加檔案作為上下文",
      },
      description: "Tooltip (title) for the attach button.",
    },
    "ai-chat-start-dictation": {
      defaultValue: "Start dictation",
      translations: {
        "ar-AE": "بدء الإملاء",
        "ar-BH": "بدء الإملاء",
        "ar-DZ": "بدء الإملاء",
        "ar-EG": "بدء الإملاء",
        "ar-IQ": "بدء الإملاء",
        "ar-JO": "بدء الإملاء",
        "ar-KW": "بدء الإملاء",
        "ar-LB": "بدء الإملاء",
        "ar-LY": "بدء الإملاء",
        "ar-MA": "بدء الإملاء",
        "ar-OM": "بدء الإملاء",
        "ar-QA": "بدء الإملاء",
        "ar-SA": "بدء الإملاء",
        "ar-SY": "بدء الإملاء",
        "ar-TN": "بدء الإملاء",
        "ar-YE": "بدء الإملاء",
        "cs-CZ": "Spustit diktování",
        da: "Start diktering",
        "de-AT": "Diktat starten",
        "de-CH": "Diktat starten",
        "de-DE": "Diktat starten",
        "de-LI": "Diktat starten",
        "de-LU": "Diktat starten",
        "el-GR": "Έναρξη υπαγόρευσης",
        "en-AU": "Start dictation",
        "en-BZ": "Start dictation",
        "en-CA": "Start dictation",
        "en-GB": "Start dictation",
        "en-IE": "Start dictation",
        "en-JM": "Start dictation",
        "en-NZ": "Start dictation",
        "en-PH": "Start dictation",
        "en-TT": "Start dictation",
        "en-US": "Start dictation",
        "en-ZA": "Start dictation",
        "en-ZW": "Start dictation",
        "es-AR": "Iniciar dictado",
        "es-BO": "Iniciar dictado",
        "es-CL": "Iniciar dictado",
        "es-CO": "Iniciar dictado",
        "es-CR": "Iniciar dictado",
        "es-DO": "Iniciar dictado",
        "es-EC": "Iniciar dictado",
        "es-ES": "Iniciar dictado",
        "es-GT": "Iniciar dictado",
        "es-HN": "Iniciar dictado",
        "es-MX": "Iniciar dictado",
        "es-NI": "Iniciar dictado",
        "es-PA": "Iniciar dictado",
        "es-PE": "Iniciar dictado",
        "es-PR": "Iniciar dictado",
        "es-PY": "Iniciar dictado",
        "es-SV": "Iniciar dictado",
        "es-UY": "Iniciar dictado",
        "es-VE": "Iniciar dictado",
        "fi-FI": "Aloita sanelu",
        "fr-BE": "Démarrer la dictée",
        "fr-CA": "Démarrer la dictée",
        "fr-CH": "Démarrer la dictée",
        "fr-FR": "Démarrer la dictée",
        "fr-LU": "Démarrer la dictée",
        "fr-MC": "Démarrer la dictée",
        "he-IL": "התחלת הכתבה",
        "hi-IN": "डिक्टेशन शुरू करें",
        "hu-HU": "Diktálás indítása",
        "id-ID": "Mulai dikte",
        "it-CH": "Avvia dettatura",
        "it-IT": "Avvia dettatura",
        "ja-JP": "音声入力を開始",
        "ko-KR": "받아쓰기 시작",
        "nb-NO": "Start diktering",
        "nl-BE": "Dicteren starten",
        "nl-NL": "Dicteren starten",
        "pl-PL": "Rozpocznij dyktowanie",
        "pt-BR": "Iniciar ditado",
        "pt-PT": "Iniciar ditado",
        "ro-RO": "Începe dictarea",
        "ru-RU": "Начать диктовку",
        "sk-SK": "Spustiť diktovanie",
        "sv-FI": "Starta diktering",
        "sv-SE": "Starta diktering",
        "th-TH": "เริ่มการบอกตามคำ",
        "tr-TR": "Dikteyi başlat",
        "uk-UA": "Почати диктування",
        "vi-VN": "Bắt đầu đọc chính tả",
        "zh-CN": "开始语音输入",
        "zh-SG": "开始语音输入",
        "zh-TW": "開始語音輸入",
      },
      description: "Aria-label for the mic button when idle.",
    },
    "ai-chat-stop-dictation": {
      defaultValue: "Stop dictation",
      translations: {
        "ar-AE": "إيقاف الإملاء",
        "ar-BH": "إيقاف الإملاء",
        "ar-DZ": "إيقاف الإملاء",
        "ar-EG": "إيقاف الإملاء",
        "ar-IQ": "إيقاف الإملاء",
        "ar-JO": "إيقاف الإملاء",
        "ar-KW": "إيقاف الإملاء",
        "ar-LB": "إيقاف الإملاء",
        "ar-LY": "إيقاف الإملاء",
        "ar-MA": "إيقاف الإملاء",
        "ar-OM": "إيقاف الإملاء",
        "ar-QA": "إيقاف الإملاء",
        "ar-SA": "إيقاف الإملاء",
        "ar-SY": "إيقاف الإملاء",
        "ar-TN": "إيقاف الإملاء",
        "ar-YE": "إيقاف الإملاء",
        "cs-CZ": "Zastavit diktování",
        da: "Stop diktering",
        "de-AT": "Diktat beenden",
        "de-CH": "Diktat beenden",
        "de-DE": "Diktat beenden",
        "de-LI": "Diktat beenden",
        "de-LU": "Diktat beenden",
        "el-GR": "Διακοπή υπαγόρευσης",
        "en-AU": "Stop dictation",
        "en-BZ": "Stop dictation",
        "en-CA": "Stop dictation",
        "en-GB": "Stop dictation",
        "en-IE": "Stop dictation",
        "en-JM": "Stop dictation",
        "en-NZ": "Stop dictation",
        "en-PH": "Stop dictation",
        "en-TT": "Stop dictation",
        "en-US": "Stop dictation",
        "en-ZA": "Stop dictation",
        "en-ZW": "Stop dictation",
        "es-AR": "Detener dictado",
        "es-BO": "Detener dictado",
        "es-CL": "Detener dictado",
        "es-CO": "Detener dictado",
        "es-CR": "Detener dictado",
        "es-DO": "Detener dictado",
        "es-EC": "Detener dictado",
        "es-ES": "Detener dictado",
        "es-GT": "Detener dictado",
        "es-HN": "Detener dictado",
        "es-MX": "Detener dictado",
        "es-NI": "Detener dictado",
        "es-PA": "Detener dictado",
        "es-PE": "Detener dictado",
        "es-PR": "Detener dictado",
        "es-PY": "Detener dictado",
        "es-SV": "Detener dictado",
        "es-UY": "Detener dictado",
        "es-VE": "Detener dictado",
        "fi-FI": "Lopeta sanelu",
        "fr-BE": "Arrêter la dictée",
        "fr-CA": "Arrêter la dictée",
        "fr-CH": "Arrêter la dictée",
        "fr-FR": "Arrêter la dictée",
        "fr-LU": "Arrêter la dictée",
        "fr-MC": "Arrêter la dictée",
        "he-IL": "עצירת הכתבה",
        "hi-IN": "डिक्टेशन बंद करें",
        "hu-HU": "Diktálás leállítása",
        "id-ID": "Hentikan dikte",
        "it-CH": "Interrompi dettatura",
        "it-IT": "Interrompi dettatura",
        "ja-JP": "音声入力を停止",
        "ko-KR": "받아쓰기 중지",
        "nb-NO": "Stopp diktering",
        "nl-BE": "Dicteren stoppen",
        "nl-NL": "Dicteren stoppen",
        "pl-PL": "Zatrzymaj dyktowanie",
        "pt-BR": "Parar ditado",
        "pt-PT": "Parar ditado",
        "ro-RO": "Oprește dictarea",
        "ru-RU": "Остановить диктовку",
        "sk-SK": "Zastaviť diktovanie",
        "sv-FI": "Stoppa diktering",
        "sv-SE": "Stoppa diktering",
        "th-TH": "หยุดการบอกตามคำ",
        "tr-TR": "Dikteyi durdur",
        "uk-UA": "Зупинити диктування",
        "vi-VN": "Dừng đọc chính tả",
        "zh-CN": "停止语音输入",
        "zh-SG": "停止语音输入",
        "zh-TW": "停止語音輸入",
      },
      description: "Aria-label/tooltip for the mic button while recording.",
    },
    "ai-chat-dictate-hint": {
      defaultValue: "Speak to type",
      translations: {
        "ar-AE": "تحدث لتكتب",
        "ar-BH": "تحدث لتكتب",
        "ar-DZ": "تحدث لتكتب",
        "ar-EG": "تحدث لتكتب",
        "ar-IQ": "تحدث لتكتب",
        "ar-JO": "تحدث لتكتب",
        "ar-KW": "تحدث لتكتب",
        "ar-LB": "تحدث لتكتب",
        "ar-LY": "تحدث لتكتب",
        "ar-MA": "تحدث لتكتب",
        "ar-OM": "تحدث لتكتب",
        "ar-QA": "تحدث لتكتب",
        "ar-SA": "تحدث لتكتب",
        "ar-SY": "تحدث لتكتب",
        "ar-TN": "تحدث لتكتب",
        "ar-YE": "تحدث لتكتب",
        "cs-CZ": "Mluvte pro psaní",
        da: "Tal for at skrive",
        "de-AT": "Sprechen zum Schreiben",
        "de-CH": "Sprechen zum Schreiben",
        "de-DE": "Sprechen zum Schreiben",
        "de-LI": "Sprechen zum Schreiben",
        "de-LU": "Sprechen zum Schreiben",
        "el-GR": "Μιλήστε για πληκτρολόγηση",
        "en-AU": "Speak to type",
        "en-BZ": "Speak to type",
        "en-CA": "Speak to type",
        "en-GB": "Speak to type",
        "en-IE": "Speak to type",
        "en-JM": "Speak to type",
        "en-NZ": "Speak to type",
        "en-PH": "Speak to type",
        "en-TT": "Speak to type",
        "en-US": "Speak to type",
        "en-ZA": "Speak to type",
        "en-ZW": "Speak to type",
        "es-AR": "Habla para escribir",
        "es-BO": "Habla para escribir",
        "es-CL": "Habla para escribir",
        "es-CO": "Habla para escribir",
        "es-CR": "Habla para escribir",
        "es-DO": "Habla para escribir",
        "es-EC": "Habla para escribir",
        "es-ES": "Habla para escribir",
        "es-GT": "Habla para escribir",
        "es-HN": "Habla para escribir",
        "es-MX": "Habla para escribir",
        "es-NI": "Habla para escribir",
        "es-PA": "Habla para escribir",
        "es-PE": "Habla para escribir",
        "es-PR": "Habla para escribir",
        "es-PY": "Habla para escribir",
        "es-SV": "Habla para escribir",
        "es-UY": "Habla para escribir",
        "es-VE": "Habla para escribir",
        "fi-FI": "Puhu kirjoittaaksesi",
        "fr-BE": "Parlez pour écrire",
        "fr-CA": "Parlez pour écrire",
        "fr-CH": "Parlez pour écrire",
        "fr-FR": "Parlez pour écrire",
        "fr-LU": "Parlez pour écrire",
        "fr-MC": "Parlez pour écrire",
        "he-IL": "דבר כדי להקליד",
        "hi-IN": "टाइप करने के लिए बोलें",
        "hu-HU": "Beszéljen a gépeléshez",
        "id-ID": "Bicara untuk mengetik",
        "it-CH": "Parla per scrivere",
        "it-IT": "Parla per scrivere",
        "ja-JP": "話して入力",
        "ko-KR": "말하여 입력",
        "nb-NO": "Snakk for å skrive",
        "nl-BE": "Spreek om te typen",
        "nl-NL": "Spreek om te typen",
        "pl-PL": "Mów, aby pisać",
        "pt-BR": "Fale para digitar",
        "pt-PT": "Fale para escrever",
        "ro-RO": "Vorbește pentru a scrie",
        "ru-RU": "Говорите, чтобы печатать",
        "sk-SK": "Hovorte na písanie",
        "sv-FI": "Tala för att skriva",
        "sv-SE": "Tala för att skriva",
        "th-TH": "พูดเพื่อพิมพ์",
        "tr-TR": "Yazmak için konuşun",
        "uk-UA": "Говоріть, щоб друкувати",
        "vi-VN": "Nói để nhập",
        "zh-CN": "说话即可输入",
        "zh-SG": "说话即可输入",
        "zh-TW": "說話即可輸入",
      },
      description: "Tooltip for the mic button when idle.",
    },
    "ai-chat-thinking": {
      defaultValue: "Assistant is thinking…",
      translations: {
        "ar-AE": "المساعد يفكر…",
        "ar-BH": "المساعد يفكر…",
        "ar-DZ": "المساعد يفكر…",
        "ar-EG": "المساعد يفكر…",
        "ar-IQ": "المساعد يفكر…",
        "ar-JO": "المساعد يفكر…",
        "ar-KW": "المساعد يفكر…",
        "ar-LB": "المساعد يفكر…",
        "ar-LY": "المساعد يفكر…",
        "ar-MA": "المساعد يفكر…",
        "ar-OM": "المساعد يفكر…",
        "ar-QA": "المساعد يفكر…",
        "ar-SA": "المساعد يفكر…",
        "ar-SY": "المساعد يفكر…",
        "ar-TN": "المساعد يفكر…",
        "ar-YE": "المساعد يفكر…",
        "cs-CZ": "Asistent přemýšlí…",
        da: "Assistenten tænker…",
        "de-AT": "Der Assistent denkt nach…",
        "de-CH": "Der Assistent denkt nach…",
        "de-DE": "Der Assistent denkt nach…",
        "de-LI": "Der Assistent denkt nach…",
        "de-LU": "Der Assistent denkt nach…",
        "el-GR": "Ο βοηθός σκέφτεται…",
        "en-AU": "Assistant is thinking…",
        "en-BZ": "Assistant is thinking…",
        "en-CA": "Assistant is thinking…",
        "en-GB": "Assistant is thinking…",
        "en-IE": "Assistant is thinking…",
        "en-JM": "Assistant is thinking…",
        "en-NZ": "Assistant is thinking…",
        "en-PH": "Assistant is thinking…",
        "en-TT": "Assistant is thinking…",
        "en-US": "Assistant is thinking…",
        "en-ZA": "Assistant is thinking…",
        "en-ZW": "Assistant is thinking…",
        "es-AR": "El asistente está pensando…",
        "es-BO": "El asistente está pensando…",
        "es-CL": "El asistente está pensando…",
        "es-CO": "El asistente está pensando…",
        "es-CR": "El asistente está pensando…",
        "es-DO": "El asistente está pensando…",
        "es-EC": "El asistente está pensando…",
        "es-ES": "El asistente está pensando…",
        "es-GT": "El asistente está pensando…",
        "es-HN": "El asistente está pensando…",
        "es-MX": "El asistente está pensando…",
        "es-NI": "El asistente está pensando…",
        "es-PA": "El asistente está pensando…",
        "es-PE": "El asistente está pensando…",
        "es-PR": "El asistente está pensando…",
        "es-PY": "El asistente está pensando…",
        "es-SV": "El asistente está pensando…",
        "es-UY": "El asistente está pensando…",
        "es-VE": "El asistente está pensando…",
        "fi-FI": "Avustaja miettii…",
        "fr-BE": "L'assistant réfléchit…",
        "fr-CA": "L'assistant réfléchit…",
        "fr-CH": "L'assistant réfléchit…",
        "fr-FR": "L'assistant réfléchit…",
        "fr-LU": "L'assistant réfléchit…",
        "fr-MC": "L'assistant réfléchit…",
        "he-IL": "העוזר חושב…",
        "hi-IN": "सहायक सोच रहा है…",
        "hu-HU": "Az asszisztens gondolkodik…",
        "id-ID": "Asisten sedang berpikir…",
        "it-CH": "L'assistente sta pensando…",
        "it-IT": "L'assistente sta pensando…",
        "ja-JP": "アシスタントが考えています…",
        "ko-KR": "어시스턴트가 생각 중…",
        "nb-NO": "Assistenten tenker…",
        "nl-BE": "De assistent denkt na…",
        "nl-NL": "De assistent denkt na…",
        "pl-PL": "Asystent myśli…",
        "pt-BR": "O assistente está pensando…",
        "pt-PT": "O assistente está a pensar…",
        "ro-RO": "Asistentul se gândește…",
        "ru-RU": "Ассистент думает…",
        "sk-SK": "Asistent premýšľa…",
        "sv-FI": "Assistenten tänker…",
        "sv-SE": "Assistenten tänker…",
        "th-TH": "ผู้ช่วยกำลังคิด…",
        "tr-TR": "Asistan düşünüyor…",
        "uk-UA": "Асистент думає…",
        "vi-VN": "Trợ lý đang suy nghĩ…",
        "zh-CN": "助手正在思考…",
        "zh-SG": "助手正在思考…",
        "zh-TW": "助手正在思考…",
      },
      description: "Streaming status banner text.",
    },
    "ai-chat-thinking-aria": {
      defaultValue: "Assistant is thinking",
      translations: {
        "ar-AE": "المساعد يفكر",
        "ar-BH": "المساعد يفكر",
        "ar-DZ": "المساعد يفكر",
        "ar-EG": "المساعد يفكر",
        "ar-IQ": "المساعد يفكر",
        "ar-JO": "المساعد يفكر",
        "ar-KW": "المساعد يفكر",
        "ar-LB": "المساعد يفكر",
        "ar-LY": "المساعد يفكر",
        "ar-MA": "المساعد يفكر",
        "ar-OM": "المساعد يفكر",
        "ar-QA": "المساعد يفكر",
        "ar-SA": "المساعد يفكر",
        "ar-SY": "المساعد يفكر",
        "ar-TN": "المساعد يفكر",
        "ar-YE": "المساعد يفكر",
        "cs-CZ": "Asistent přemýšlí",
        da: "Assistenten tænker",
        "de-AT": "Der Assistent denkt nach",
        "de-CH": "Der Assistent denkt nach",
        "de-DE": "Der Assistent denkt nach",
        "de-LI": "Der Assistent denkt nach",
        "de-LU": "Der Assistent denkt nach",
        "el-GR": "Ο βοηθός σκέφτεται",
        "en-AU": "Assistant is thinking",
        "en-BZ": "Assistant is thinking",
        "en-CA": "Assistant is thinking",
        "en-GB": "Assistant is thinking",
        "en-IE": "Assistant is thinking",
        "en-JM": "Assistant is thinking",
        "en-NZ": "Assistant is thinking",
        "en-PH": "Assistant is thinking",
        "en-TT": "Assistant is thinking",
        "en-US": "Assistant is thinking",
        "en-ZA": "Assistant is thinking",
        "en-ZW": "Assistant is thinking",
        "es-AR": "El asistente está pensando",
        "es-BO": "El asistente está pensando",
        "es-CL": "El asistente está pensando",
        "es-CO": "El asistente está pensando",
        "es-CR": "El asistente está pensando",
        "es-DO": "El asistente está pensando",
        "es-EC": "El asistente está pensando",
        "es-ES": "El asistente está pensando",
        "es-GT": "El asistente está pensando",
        "es-HN": "El asistente está pensando",
        "es-MX": "El asistente está pensando",
        "es-NI": "El asistente está pensando",
        "es-PA": "El asistente está pensando",
        "es-PE": "El asistente está pensando",
        "es-PR": "El asistente está pensando",
        "es-PY": "El asistente está pensando",
        "es-SV": "El asistente está pensando",
        "es-UY": "El asistente está pensando",
        "es-VE": "El asistente está pensando",
        "fi-FI": "Avustaja miettii",
        "fr-BE": "L'assistant réfléchit",
        "fr-CA": "L'assistant réfléchit",
        "fr-CH": "L'assistant réfléchit",
        "fr-FR": "L'assistant réfléchit",
        "fr-LU": "L'assistant réfléchit",
        "fr-MC": "L'assistant réfléchit",
        "he-IL": "העוזר חושב",
        "hi-IN": "सहायक सोच रहा है",
        "hu-HU": "Az asszisztens gondolkodik",
        "id-ID": "Asisten sedang berpikir",
        "it-CH": "L'assistente sta pensando",
        "it-IT": "L'assistente sta pensando",
        "ja-JP": "アシスタントが考えています",
        "ko-KR": "어시스턴트가 생각 중",
        "nb-NO": "Assistenten tenker",
        "nl-BE": "De assistent denkt na",
        "nl-NL": "De assistent denkt na",
        "pl-PL": "Asystent myśli",
        "pt-BR": "O assistente está pensando",
        "pt-PT": "O assistente está a pensar",
        "ro-RO": "Asistentul se gândește",
        "ru-RU": "Ассистент думает",
        "sk-SK": "Asistent premýšľa",
        "sv-FI": "Assistenten tänker",
        "sv-SE": "Assistenten tänker",
        "th-TH": "ผู้ช่วยกำลังคิด",
        "tr-TR": "Asistan düşünüyor",
        "uk-UA": "Асистент думає",
        "vi-VN": "Trợ lý đang suy nghĩ",
        "zh-CN": "助手正在思考",
        "zh-SG": "助手正在思考",
        "zh-TW": "助手正在思考",
      },
      description: "Aria-label for the streaming spinner.",
    },
    "ai-chat-stop": {
      defaultValue: "Stop",
      translations: {
        "ar-AE": "إيقاف",
        "ar-BH": "إيقاف",
        "ar-DZ": "إيقاف",
        "ar-EG": "إيقاف",
        "ar-IQ": "إيقاف",
        "ar-JO": "إيقاف",
        "ar-KW": "إيقاف",
        "ar-LB": "إيقاف",
        "ar-LY": "إيقاف",
        "ar-MA": "إيقاف",
        "ar-OM": "إيقاف",
        "ar-QA": "إيقاف",
        "ar-SA": "إيقاف",
        "ar-SY": "إيقاف",
        "ar-TN": "إيقاف",
        "ar-YE": "إيقاف",
        "cs-CZ": "Zastavit",
        da: "Stop",
        "de-AT": "Stopp",
        "de-CH": "Stopp",
        "de-DE": "Stopp",
        "de-LI": "Stopp",
        "de-LU": "Stopp",
        "el-GR": "Διακοπή",
        "en-AU": "Stop",
        "en-BZ": "Stop",
        "en-CA": "Stop",
        "en-GB": "Stop",
        "en-IE": "Stop",
        "en-JM": "Stop",
        "en-NZ": "Stop",
        "en-PH": "Stop",
        "en-TT": "Stop",
        "en-US": "Stop",
        "en-ZA": "Stop",
        "en-ZW": "Stop",
        "es-AR": "Detener",
        "es-BO": "Detener",
        "es-CL": "Detener",
        "es-CO": "Detener",
        "es-CR": "Detener",
        "es-DO": "Detener",
        "es-EC": "Detener",
        "es-ES": "Detener",
        "es-GT": "Detener",
        "es-HN": "Detener",
        "es-MX": "Detener",
        "es-NI": "Detener",
        "es-PA": "Detener",
        "es-PE": "Detener",
        "es-PR": "Detener",
        "es-PY": "Detener",
        "es-SV": "Detener",
        "es-UY": "Detener",
        "es-VE": "Detener",
        "fi-FI": "Pysäytä",
        "fr-BE": "Arrêter",
        "fr-CA": "Arrêter",
        "fr-CH": "Arrêter",
        "fr-FR": "Arrêter",
        "fr-LU": "Arrêter",
        "fr-MC": "Arrêter",
        "he-IL": "עצירה",
        "hi-IN": "रोकें",
        "hu-HU": "Leállítás",
        "id-ID": "Hentikan",
        "it-CH": "Interrompi",
        "it-IT": "Interrompi",
        "ja-JP": "停止",
        "ko-KR": "중지",
        "nb-NO": "Stopp",
        "nl-BE": "Stoppen",
        "nl-NL": "Stoppen",
        "pl-PL": "Zatrzymaj",
        "pt-BR": "Parar",
        "pt-PT": "Parar",
        "ro-RO": "Oprește",
        "ru-RU": "Остановить",
        "sk-SK": "Zastaviť",
        "sv-FI": "Stoppa",
        "sv-SE": "Stoppa",
        "th-TH": "หยุด",
        "tr-TR": "Durdur",
        "uk-UA": "Зупинити",
        "vi-VN": "Dừng",
        "zh-CN": "停止",
        "zh-SG": "停止",
        "zh-TW": "停止",
      },
      description: "Stop-streaming button label.",
    },
    "ai-chat-stop-hint": {
      defaultValue: "Stop (Esc)",
      translations: {
        "ar-AE": "إيقاف (Esc)",
        "ar-BH": "إيقاف (Esc)",
        "ar-DZ": "إيقاف (Esc)",
        "ar-EG": "إيقاف (Esc)",
        "ar-IQ": "إيقاف (Esc)",
        "ar-JO": "إيقاف (Esc)",
        "ar-KW": "إيقاف (Esc)",
        "ar-LB": "إيقاف (Esc)",
        "ar-LY": "إيقاف (Esc)",
        "ar-MA": "إيقاف (Esc)",
        "ar-OM": "إيقاف (Esc)",
        "ar-QA": "إيقاف (Esc)",
        "ar-SA": "إيقاف (Esc)",
        "ar-SY": "إيقاف (Esc)",
        "ar-TN": "إيقاف (Esc)",
        "ar-YE": "إيقاف (Esc)",
        "cs-CZ": "Zastavit (Esc)",
        da: "Stop (Esc)",
        "de-AT": "Stopp (Esc)",
        "de-CH": "Stopp (Esc)",
        "de-DE": "Stopp (Esc)",
        "de-LI": "Stopp (Esc)",
        "de-LU": "Stopp (Esc)",
        "el-GR": "Διακοπή (Esc)",
        "en-AU": "Stop (Esc)",
        "en-BZ": "Stop (Esc)",
        "en-CA": "Stop (Esc)",
        "en-GB": "Stop (Esc)",
        "en-IE": "Stop (Esc)",
        "en-JM": "Stop (Esc)",
        "en-NZ": "Stop (Esc)",
        "en-PH": "Stop (Esc)",
        "en-TT": "Stop (Esc)",
        "en-US": "Stop (Esc)",
        "en-ZA": "Stop (Esc)",
        "en-ZW": "Stop (Esc)",
        "es-AR": "Detener (Esc)",
        "es-BO": "Detener (Esc)",
        "es-CL": "Detener (Esc)",
        "es-CO": "Detener (Esc)",
        "es-CR": "Detener (Esc)",
        "es-DO": "Detener (Esc)",
        "es-EC": "Detener (Esc)",
        "es-ES": "Detener (Esc)",
        "es-GT": "Detener (Esc)",
        "es-HN": "Detener (Esc)",
        "es-MX": "Detener (Esc)",
        "es-NI": "Detener (Esc)",
        "es-PA": "Detener (Esc)",
        "es-PE": "Detener (Esc)",
        "es-PR": "Detener (Esc)",
        "es-PY": "Detener (Esc)",
        "es-SV": "Detener (Esc)",
        "es-UY": "Detener (Esc)",
        "es-VE": "Detener (Esc)",
        "fi-FI": "Pysäytä (Esc)",
        "fr-BE": "Arrêter (Échap)",
        "fr-CA": "Arrêter (Échap)",
        "fr-CH": "Arrêter (Échap)",
        "fr-FR": "Arrêter (Échap)",
        "fr-LU": "Arrêter (Échap)",
        "fr-MC": "Arrêter (Échap)",
        "he-IL": "עצירה (Esc)",
        "hi-IN": "रोकें (Esc)",
        "hu-HU": "Leállítás (Esc)",
        "id-ID": "Hentikan (Esc)",
        "it-CH": "Interrompi (Esc)",
        "it-IT": "Interrompi (Esc)",
        "ja-JP": "停止 (Esc)",
        "ko-KR": "중지 (Esc)",
        "nb-NO": "Stopp (Esc)",
        "nl-BE": "Stoppen (Esc)",
        "nl-NL": "Stoppen (Esc)",
        "pl-PL": "Zatrzymaj (Esc)",
        "pt-BR": "Parar (Esc)",
        "pt-PT": "Parar (Esc)",
        "ro-RO": "Oprește (Esc)",
        "ru-RU": "Остановить (Esc)",
        "sk-SK": "Zastaviť (Esc)",
        "sv-FI": "Stoppa (Esc)",
        "sv-SE": "Stoppa (Esc)",
        "th-TH": "หยุด (Esc)",
        "tr-TR": "Durdur (Esc)",
        "uk-UA": "Зупинити (Esc)",
        "vi-VN": "Dừng (Esc)",
        "zh-CN": "停止 (Esc)",
        "zh-SG": "停止 (Esc)",
        "zh-TW": "停止 (Esc)",
      },
      description: "Tooltip for the stop button (Esc shortcut).",
    },
    "ai-chat-send-error": {
      defaultValue:
        "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
      translations: {
        "ar-AE":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-BH":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-DZ":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-EG":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-IQ":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-JO":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-KW":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-LB":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-LY":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-MA":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-OM":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-QA":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-SA":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-SY":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-TN":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "ar-YE":
          "تعذّر إرسال رسالتك. حاول مرة أخرى، أو أعد تحميل الصفحة إذا استمر الفشل.",
        "cs-CZ":
          "Zprávu se nepodařilo odeslat. Zkuste to znovu nebo obnovte stránku, pokud problém přetrvává.",
        da: "Din besked kunne ikke sendes. Prøv igen, eller genindlæs siden, hvis det bliver ved.",
        "de-AT":
          "Ihre Nachricht konnte nicht gesendet werden. Versuchen Sie es erneut oder aktualisieren Sie die Seite, wenn es weiterhin fehlschlägt.",
        "de-CH":
          "Ihre Nachricht konnte nicht gesendet werden. Versuchen Sie es erneut oder aktualisieren Sie die Seite, wenn es weiterhin fehlschlägt.",
        "de-DE":
          "Ihre Nachricht konnte nicht gesendet werden. Versuchen Sie es erneut oder aktualisieren Sie die Seite, wenn es weiterhin fehlschlägt.",
        "de-LI":
          "Ihre Nachricht konnte nicht gesendet werden. Versuchen Sie es erneut oder aktualisieren Sie die Seite, wenn es weiterhin fehlschlägt.",
        "de-LU":
          "Ihre Nachricht konnte nicht gesendet werden. Versuchen Sie es erneut oder aktualisieren Sie die Seite, wenn es weiterhin fehlschlägt.",
        "el-GR":
          "Δεν ήταν δυνατή η αποστολή του μηνύματός σας. Δοκιμάστε ξανά ή ανανεώστε τη σελίδα αν συνεχίζει.",
        "en-AU":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-BZ":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-CA":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-GB":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-IE":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-JM":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-NZ":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-PH":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-TT":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-US":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-ZA":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "en-ZW":
          "Couldn't send your message. Try again, or refresh the page if it keeps failing.",
        "es-AR":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-BO":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-CL":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-CO":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-CR":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-DO":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-EC":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-ES":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-GT":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-HN":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-MX":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-NI":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-PA":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-PE":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-PR":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-PY":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-SV":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-UY":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "es-VE":
          "No se pudo enviar tu mensaje. Inténtalo de nuevo o actualiza la página si sigue fallando.",
        "fi-FI":
          "Viestin lähettäminen epäonnistui. Yritä uudelleen tai päivitä sivu, jos ongelma jatkuu.",
        "fr-BE":
          "Impossible d'envoyer votre message. Réessayez ou actualisez la page si le problème persiste.",
        "fr-CA":
          "Impossible d'envoyer votre message. Réessayez ou actualisez la page si le problème persiste.",
        "fr-CH":
          "Impossible d'envoyer votre message. Réessayez ou actualisez la page si le problème persiste.",
        "fr-FR":
          "Impossible d'envoyer votre message. Réessayez ou actualisez la page si le problème persiste.",
        "fr-LU":
          "Impossible d'envoyer votre message. Réessayez ou actualisez la page si le problème persiste.",
        "fr-MC":
          "Impossible d'envoyer votre message. Réessayez ou actualisez la page si le problème persiste.",
        "he-IL":
          "לא ניתן היה לשלוח את ההודעה שלך. נסה שוב, או רענן את הדף אם התקלה נמשכת.",
        "hi-IN":
          "आपका संदेश नहीं भेजा जा सका. फिर से प्रयास करें, या बार-बार विफल होने पर पेज रीफ़्रेश करें.",
        "hu-HU":
          "Az üzenet küldése nem sikerült. Próbáld újra, vagy frissítsd az oldalt, ha továbbra sem működik.",
        "id-ID":
          "Pesan Anda tidak dapat dikirim. Coba lagi, atau muat ulang halaman jika terus gagal.",
        "it-CH":
          "Impossibile inviare il messaggio. Riprova o aggiorna la pagina se il problema persiste.",
        "it-IT":
          "Impossibile inviare il messaggio. Riprova o aggiorna la pagina se il problema persiste.",
        "ja-JP":
          "メッセージを送信できませんでした。もう一度お試しください。解決しない場合はページを再読み込みしてください。",
        "ko-KR":
          "메시지를 보내지 못했습니다. 다시 시도하거나, 계속 실패하면 페이지를 새로 고치세요.",
        "nb-NO":
          "Meldingen kunne ikke sendes. Prøv igjen, eller last inn siden på nytt hvis det fortsetter.",
        "nl-BE":
          "Je bericht kon niet worden verzonden. Probeer het opnieuw of vernieuw de pagina als het blijft mislukken.",
        "nl-NL":
          "Je bericht kon niet worden verzonden. Probeer het opnieuw of vernieuw de pagina als het blijft mislukken.",
        "pl-PL":
          "Nie udało się wysłać wiadomości. Spróbuj ponownie lub odśwież stronę, jeśli problem się powtarza.",
        "pt-BR":
          "Não foi possível enviar sua mensagem. Tente novamente ou atualize a página se continuar falhando.",
        "pt-PT":
          "Não foi possível enviar a sua mensagem. Tente novamente ou atualize a página se continuar a falhar.",
        "ro-RO":
          "Mesajul nu a putut fi trimis. Încearcă din nou sau reîncarcă pagina dacă problema persistă.",
        "ru-RU":
          "Не удалось отправить сообщение. Повторите попытку или обновите страницу, если ошибка повторяется.",
        "sk-SK":
          "Správu sa nepodarilo odoslať. Skúste to znova alebo obnovte stránku, ak problém pretrváva.",
        "sv-FI":
          "Meddelandet kunde inte skickas. Försök igen, eller uppdatera sidan om det fortsätter.",
        "sv-SE":
          "Meddelandet kunde inte skickas. Försök igen, eller uppdatera sidan om det fortsätter.",
        "th-TH": "ไม่สามารถส่งข้อความของคุณได้ ลองอีกครั้ง หรือรีเฟรชหน้าหากยังคงล้มเหลว",
        "tr-TR":
          "Mesajınız gönderilemedi. Tekrar deneyin veya sorun devam ederse sayfayı yenileyin.",
        "uk-UA":
          "Не вдалося надіслати повідомлення. Повторіть спробу або оновіть сторінку, якщо помилка повторюється.",
        "vi-VN":
          "Không thể gửi tin nhắn của bạn. Hãy thử lại, hoặc tải lại trang nếu vẫn lỗi.",
        "zh-CN": "无法发送您的消息。请重试，如果持续失败请刷新页面。",
        "zh-SG": "无法发送您的消息。请重试，如果持续失败请刷新页面。",
        "zh-TW": "無法傳送您的訊息。請重試，若持續失敗請重新整理頁面。",
      },
      description: "Fallback error banner when a send fails with no message.",
    },
    "ai-chat-unreadable-file": {
      defaultValue: "Picked up, but this file type isn't read as text yet.",
      translations: {
        "ar-AE": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-BH": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-DZ": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-EG": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-IQ": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-JO": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-KW": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-LB": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-LY": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-MA": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-OM": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-QA": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-SA": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-SY": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-TN": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "ar-YE": "تم الالتقاط، لكن هذا النوع من الملفات لا يُقرأ كنص بعد.",
        "cs-CZ": "Přijato, ale tento typ souboru se zatím nečte jako text.",
        da: "Modtaget, men denne filtype læses endnu ikke som tekst.",
        "de-AT":
          "Übernommen, aber dieser Dateityp wird noch nicht als Text gelesen.",
        "de-CH":
          "Übernommen, aber dieser Dateityp wird noch nicht als Text gelesen.",
        "de-DE":
          "Übernommen, aber dieser Dateityp wird noch nicht als Text gelesen.",
        "de-LI":
          "Übernommen, aber dieser Dateityp wird noch nicht als Text gelesen.",
        "de-LU":
          "Übernommen, aber dieser Dateityp wird noch nicht als Text gelesen.",
        "el-GR":
          "Ελήφθη, αλλά αυτός ο τύπος αρχείου δεν διαβάζεται ακόμη ως κείμενο.",
        "en-AU": "Picked up, but this file type isn't read as text yet.",
        "en-BZ": "Picked up, but this file type isn't read as text yet.",
        "en-CA": "Picked up, but this file type isn't read as text yet.",
        "en-GB": "Picked up, but this file type isn't read as text yet.",
        "en-IE": "Picked up, but this file type isn't read as text yet.",
        "en-JM": "Picked up, but this file type isn't read as text yet.",
        "en-NZ": "Picked up, but this file type isn't read as text yet.",
        "en-PH": "Picked up, but this file type isn't read as text yet.",
        "en-TT": "Picked up, but this file type isn't read as text yet.",
        "en-US": "Picked up, but this file type isn't read as text yet.",
        "en-ZA": "Picked up, but this file type isn't read as text yet.",
        "en-ZW": "Picked up, but this file type isn't read as text yet.",
        "es-AR": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-BO": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-CL": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-CO": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-CR": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-DO": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-EC": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-ES": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-GT": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-HN": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-MX": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-NI": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-PA": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-PE": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-PR": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-PY": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-SV": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-UY": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "es-VE": "Añadido, pero este tipo de archivo aún no se lee como texto.",
        "fi-FI":
          "Vastaanotettu, mutta tätä tiedostotyyppiä ei vielä lueta tekstinä.",
        "fr-BE":
          "Pris en compte, mais ce type de fichier n'est pas encore lu comme du texte.",
        "fr-CA":
          "Pris en compte, mais ce type de fichier n'est pas encore lu comme du texte.",
        "fr-CH":
          "Pris en compte, mais ce type de fichier n'est pas encore lu comme du texte.",
        "fr-FR":
          "Pris en compte, mais ce type de fichier n'est pas encore lu comme du texte.",
        "fr-LU":
          "Pris en compte, mais ce type de fichier n'est pas encore lu comme du texte.",
        "fr-MC":
          "Pris en compte, mais ce type de fichier n'est pas encore lu comme du texte.",
        "he-IL": "התקבל, אך סוג קובץ זה עדיין אינו נקרא כטקסט.",
        "hi-IN":
          "प्राप्त हुआ, लेकिन इस फ़ाइल प्रकार को अभी टेक्स्ट के रूप में नहीं पढ़ा जाता.",
        "hu-HU": "Fogadva, de ez a fájltípus még nem olvasható szövegként.",
        "id-ID": "Diterima, tetapi jenis file ini belum dibaca sebagai teks.",
        "it-CH":
          "Acquisito, ma questo tipo di file non viene ancora letto come testo.",
        "it-IT":
          "Acquisito, ma questo tipo di file non viene ancora letto come testo.",
        "ja-JP":
          "受け取りましたが、このファイル形式はまだテキストとして読み取れません。",
        "ko-KR": "받았지만 이 파일 형식은 아직 텍스트로 읽지 않습니다.",
        "nb-NO": "Mottatt, men denne filtypen leses ennå ikke som tekst.",
        "nl-BE":
          "Ontvangen, maar dit bestandstype wordt nog niet als tekst gelezen.",
        "nl-NL":
          "Ontvangen, maar dit bestandstype wordt nog niet als tekst gelezen.",
        "pl-PL":
          "Odebrano, ale ten typ pliku nie jest jeszcze odczytywany jako tekst.",
        "pt-BR":
          "Adicionado, mas este tipo de arquivo ainda não é lido como texto.",
        "pt-PT":
          "Adicionado, mas este tipo de ficheiro ainda não é lido como texto.",
        "ro-RO": "Preluat, dar acest tip de fișier nu este încă citit ca text.",
        "ru-RU": "Получено, но этот тип файла пока не читается как текст.",
        "sk-SK": "Prijaté, ale tento typ súboru sa zatiaľ nečíta ako text.",
        "sv-FI": "Mottagen, men den här filtypen läses ännu inte som text.",
        "sv-SE": "Mottagen, men den här filtypen läses ännu inte som text.",
        "th-TH": "รับแล้ว แต่ยังไม่สามารถอ่านไฟล์ประเภทนี้เป็นข้อความได้",
        "tr-TR": "Alındı, ancak bu dosya türü henüz metin olarak okunmuyor.",
        "uk-UA": "Отримано, але цей тип файлу поки не читається як текст.",
        "vi-VN": "Đã nhận, nhưng loại tệp này chưa được đọc dưới dạng văn bản.",
        "zh-CN": "已接收，但此文件类型尚不能作为文本读取。",
        "zh-SG": "已接收，但此文件类型尚不能作为文本读取。",
        "zh-TW": "已接收，但此檔案類型尚無法作為文字讀取。",
      },
      description: "Tooltip on an attached file that can't be read as text.",
    },
    "ai-chat-remove-attachment": {
      defaultValue: "Remove {name}",
      translations: {
        "ar-AE": "إزالة {name}",
        "ar-BH": "إزالة {name}",
        "ar-DZ": "إزالة {name}",
        "ar-EG": "إزالة {name}",
        "ar-IQ": "إزالة {name}",
        "ar-JO": "إزالة {name}",
        "ar-KW": "إزالة {name}",
        "ar-LB": "إزالة {name}",
        "ar-LY": "إزالة {name}",
        "ar-MA": "إزالة {name}",
        "ar-OM": "إزالة {name}",
        "ar-QA": "إزالة {name}",
        "ar-SA": "إزالة {name}",
        "ar-SY": "إزالة {name}",
        "ar-TN": "إزالة {name}",
        "ar-YE": "إزالة {name}",
        "cs-CZ": "Odebrat {name}",
        da: "Fjern {name}",
        "de-AT": "{name} entfernen",
        "de-CH": "{name} entfernen",
        "de-DE": "{name} entfernen",
        "de-LI": "{name} entfernen",
        "de-LU": "{name} entfernen",
        "el-GR": "Κατάργηση {name}",
        "en-AU": "Remove {name}",
        "en-BZ": "Remove {name}",
        "en-CA": "Remove {name}",
        "en-GB": "Remove {name}",
        "en-IE": "Remove {name}",
        "en-JM": "Remove {name}",
        "en-NZ": "Remove {name}",
        "en-PH": "Remove {name}",
        "en-TT": "Remove {name}",
        "en-US": "Remove {name}",
        "en-ZA": "Remove {name}",
        "en-ZW": "Remove {name}",
        "es-AR": "Eliminar {name}",
        "es-BO": "Eliminar {name}",
        "es-CL": "Eliminar {name}",
        "es-CO": "Eliminar {name}",
        "es-CR": "Eliminar {name}",
        "es-DO": "Eliminar {name}",
        "es-EC": "Eliminar {name}",
        "es-ES": "Eliminar {name}",
        "es-GT": "Eliminar {name}",
        "es-HN": "Eliminar {name}",
        "es-MX": "Eliminar {name}",
        "es-NI": "Eliminar {name}",
        "es-PA": "Eliminar {name}",
        "es-PE": "Eliminar {name}",
        "es-PR": "Eliminar {name}",
        "es-PY": "Eliminar {name}",
        "es-SV": "Eliminar {name}",
        "es-UY": "Eliminar {name}",
        "es-VE": "Eliminar {name}",
        "fi-FI": "Poista {name}",
        "fr-BE": "Supprimer {name}",
        "fr-CA": "Supprimer {name}",
        "fr-CH": "Supprimer {name}",
        "fr-FR": "Supprimer {name}",
        "fr-LU": "Supprimer {name}",
        "fr-MC": "Supprimer {name}",
        "he-IL": "הסרת {name}",
        "hi-IN": "{name} हटाएँ",
        "hu-HU": "{name} eltávolítása",
        "id-ID": "Hapus {name}",
        "it-CH": "Rimuovi {name}",
        "it-IT": "Rimuovi {name}",
        "ja-JP": "{name} を削除",
        "ko-KR": "{name} 제거",
        "nb-NO": "Fjern {name}",
        "nl-BE": "{name} verwijderen",
        "nl-NL": "{name} verwijderen",
        "pl-PL": "Usuń {name}",
        "pt-BR": "Remover {name}",
        "pt-PT": "Remover {name}",
        "ro-RO": "Elimină {name}",
        "ru-RU": "Удалить {name}",
        "sk-SK": "Odstrániť {name}",
        "sv-FI": "Ta bort {name}",
        "sv-SE": "Ta bort {name}",
        "th-TH": "ลบ {name}",
        "tr-TR": "{name} öğesini kaldır",
        "uk-UA": "Видалити {name}",
        "vi-VN": "Xóa {name}",
        "zh-CN": "移除 {name}",
        "zh-SG": "移除 {name}",
        "zh-TW": "移除 {name}",
      },
      description:
        "Aria-label to remove an attachment. Keep the `{name}` token — it is replaced with the file name.",
    },
  },
} satisfies DictionaryRecipe;

export default aiChatUiLabelsComposerRecipe;
