---
ID: "353214d1-61cf-4359-8db8-3e5cb954aff6"
Parent: "e7bb0585-74b7-4f0e-ba84-207df7310bda"
Template: "e7bb0585-74b7-4f0e-ba84-207df7310bda"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/destinations-carousel/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{2E7DE4DB-9677-4C2F-A338-9207D2318D10}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a5098b98-304f-474e-b75b-e81e3875dad0"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T014307Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d128113b-682d-41f7-9e30-e3b6bb114b09"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "bd2d9bc9-ad04-43fd-bc76-b6c4924fe59a"
      Hint: Title
      Value: Featured destinations
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T014307Z
