---
ID: "5e0c8547-72df-4f02-a994-42c47a842dcf"
Parent: "2e0171d4-0925-4f02-99a3-3ec0b8a6c499"
Template: "2e0171d4-0925-4f02-99a3-3ec0b8a6c499"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/Component Folders/articles-carousel Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{1BBF4341-42D8-4628-BDB0-0436AAED2F12}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "7396b342-ed05-408d-a0c0-c86eb9c5edac"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T013710Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d84cc3e2-80a0-4b16-ad7c-32e35c01cf13"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T013710Z
