---
ID: "b4db30b0-c153-44fa-89c5-08b27583d72b"
Parent: "881dc37e-41ec-4815-9918-d7edf22ae7ac"
Template: "881dc37e-41ec-4815-9918-d7edf22ae7ac"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/search/filter-panel/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "filter-panel@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "8e8f0a61-f50d-481d-93c2-c4b73f5c9f44"
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: مسح الكل
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: عوامل التصفية
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: عوامل التصفية
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "f1e5243a-5431-422b-bf9b-16d250b192c1"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: ar-SA
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: مسح الكل
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151800Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: عوامل التصفية
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: عوامل التصفية
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "af3926ed-8930-47c5-922a-50b95fee2144"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151800Z
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Ryd alt
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filtre
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filtre
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "142c6e71-4f43-44de-9c2e-ca017a3f4c53"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Alle löschen
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filter
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filter
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "9ee1a6ab-6435-4001-9d90-00235227c192"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Alle löschen
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151800Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filter
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filter
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "e1cfc095-7335-45e9-af10-0a66b93b70a0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151800Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Clear all
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215722Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filters
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filters
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "0ca721ef-6c1e-418a-86a2-982a6ec89b0d"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215722Z
- Language: es
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Borrar todo
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filtros
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filtros
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "3fc02f20-0735-4360-af0c-66ecfa028516"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: es-ES
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Borrar todo
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151800Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filtros
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filtros
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "ab8c9637-3362-41d1-bd5d-9e40a6f93387"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151800Z
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Tout effacer
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filtres
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filtres
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "b77de81e-0c56-4a4a-b0eb-34293edb99a0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: fr-FR
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Tout effacer
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151800Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filtres
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filtres
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "ae422ba4-2f49-49ed-a2b3-dc638fad922c"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151800Z
- Language: it
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: Cancella tutto
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: Filtri
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: Filtri
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "9e228b7d-cda7-44db-b549-0cd40acafefd"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: ja
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: すべてクリア
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: フィルター
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: フィルター
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "a2a9a469-9214-43e9-a27f-485b975d4046"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: zh-CN
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: 全部清除
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: 筛选
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: 筛选
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "c796537b-82ba-4cca-a3dc-d22f51c28cd9"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
- Language: zh-TW
  Versions:
  - Version: 1
    Fields:
    - ID: 1b51d62e-2764-469c-a5c5-d2f1d1766069
      Hint: ClearLabel
      Value: 全部清除
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215723Z
    - ID: 3ac011a9-5c74-4231-991d-9884793e1f40
      Hint: Title
      Value: 篩選
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 86925549-8287-4138-a3cc-e4513f30176e
      Hint: TriggerLabel
      Value: 篩選
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "6707569a-0c7d-4cf1-af4d-417af6d547b4"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215724Z
DB: master
