---
ID: "279a4040-ffc3-482c-a748-313ffe8b8268"
Parent: "a6a12f25-db45-4887-af56-7de7d106d6d2"
Template: "a6a12f25-db45-4887-af56-7de7d106d6d2"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/cards-and-lists/Component Folders/locations-map Data Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{55FB8DE7-3CF6-5B9F-A49D-E5394E7D5896}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "cef00b6e-3ee8-4e03-93d2-9983c02c7582"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260904T161634Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "07199b45-e75c-4bab-8910-c1c93e6f70a1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260904T161634Z
