---
ID: "a0a6c469-c293-41d4-9250-bfe415620069"
Parent: "0e0660c8-4a55-41fb-a5d1-1ba0cea7bcc5"
Template: "0e0660c8-4a55-41fb-a5d1-1ba0cea7bcc5"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/locations-carousel/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{D7085589-CFB8-49E2-9DB6-693BC75890E5}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ef5ab01a-0958-4da7-9ae2-e3c297320c66"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T015130Z
    - ID: "38c86359-a0cc-40e4-adac-7095b059327d"
      Hint: Title
      Value: Nearby locations
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1d3daa66-2b24-4951-b88b-b0d1a18193f4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T015130Z
