---
ID: "a4604984-0514-4007-b902-2f6959fe5531"
Parent: "3b4fea24-db8d-4eb5-8ae6-05e0cc3fe003"
Template: "3b4fea24-db8d-4eb5-8ae6-05e0cc3fe003"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/forms/form-select-field/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{51809B31-B9C5-4554-A415-457BB2A3843C}"
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "form-select-field@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9f5a8de1-34f7-478c-8487-4efbe3f91e34"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T014703Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "607b10ca-d1bc-401e-8746-e98b595ad99d"
      Hint: Label
      Value: Choose one
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "95b5f7cd-5520-4592-a91c-a09e42ad62f9"
    - ID: "956eae26-f724-4062-9b56-0696da94ffed"
      Hint: Placeholder
      Value: Select an option
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "c9c20d84-bc6a-44f9-a2e0-455e89eef495"
      Hint: Name
      Value: selection
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T014704Z
