---
ID: "4a4b0554-3888-4ffe-aad0-84c1f1149eb9"
Parent: "f714d4a5-7a70-4777-90a2-66a2ead2abf7"
Template: "7dae6839-465b-4364-a4e6-658ff5f1dbbd"
Path: "/sitecore/content/starter-collection/starter/Presentation/Enumerations/Graphics/IconName/chart"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "icon-name@1"
- ID: "85ade29a-4684-4471-8a2d-a0937f1e85fd"
  Hint: Value
  Value: chart
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "7f8c13ac-13bd-4bf5-ab9b-7b331c66571b"
Languages:
- Language: "en"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "0d6d2b4f-8f87-4fff-bdb3-c3233c6c6533"
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: Reports, statistics, or account activity graphs.
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Chart
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T220226Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e6d4b4dc-94d2-46d5-b30b-07271979b1af"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T220226Z
