---
ID: "2315e5f7-e30d-4252-bfaf-355ef8794fdd"
Parent: "436e59e5-afa1-49c5-a34e-8b41d02dd689"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: "/sitecore/layout/Renderings/Project/starter-collection/prospera/Components/cards-and-lists/product-card"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 037fe404-dd19-4bf7-8e30-4dadf68b27b0
  Hint: componentName
  Value: "product-card"
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  Hint: __Icon
  Value: "/-/media/2e0658a744f94eab898f0d2d3d446a2c.ashx?thn=1&db=master&v=2"
- ID: 1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f
  Hint: Datasource Template
  Value: "{590320C0-1570-423B-A9BD-7F7B414DECFC}"
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "product-card@1"
- ID: 7d8ae35f-9ed1-43b5-96a2-0a5f040d4e4e
  Hint: Open Properties after Add
  Value: 0
- ID: a77e8568-1ab3-44f1-a664-b7c37ec7810d
  Hint: Parameters Template
  Value: "{3A5B3645-C490-48E0-B1B5-D0139D0BF621}"
- ID: b5b27af1-25ef-405c-87ce-369b3a004016
  Hint: Datasource Location
  Value: "./Data/Products|/sitecore/content/starter-collection/prospera/Data/Products"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "0cad3f89-056e-40c3-9d49-aeb26a174040"
- ID: e829c217-5e94-4306-9c48-2634b094fdc2
  Hint: OtherProperties
  Value: IsAutoDatasourceRendering=true
Languages:
- Language: en
  Fields:
  - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
    Hint: __Unversioned revision
    Value: "6a60e43c-cc51-4e4c-8cdc-782467fcd08f"
  - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
    Hint: __Display name
    Value: Product Card
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260916T020044Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "e54e7cec-f2a2-48eb-95b6-5735aa15cda0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260916T020045Z
DB: master
