---
ID: "52d06807-7cbc-47fe-9d4f-f1d3b9289bac"
Parent: "87f7095e-7fba-49de-857a-29bdbb7d5253"
Template: "87f7095e-7fba-49de-857a-29bdbb7d5253"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/forms/form-phone-field/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "form-phone-field@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "dcea921e-9209-45b5-aeb1-8a3e972361b9"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 1c1683fa-22fe-4f3b-9816-3b7383b6cff9
      Hint: Label
      Value: Phone number
    - ID: 1ee249ff-912c-4ecf-987b-a291397faea4
      Hint: DefaultCountry
      Value: US
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260916T014631Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 71a89fe2-1e20-4816-8f34-9073512a1f58
      Hint: Name
      Value: phone
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "98c1c32e-b69d-49ac-8082-1f0aaed3848d"
    - ID: 951ffb5b-5079-4a44-b244-d7f29fba441f
      Hint: Required
      Value: 1
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260916T014631Z
DB: master
