---
ID: "8a58a195-e7b3-46d2-becb-295cbc3fd6f7"
Parent: "780e3368-6db9-411d-8212-d6ba4a7b34d0"
Template: "780e3368-6db9-411d-8212-d6ba4a7b34d0"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/feedback/alert-banner/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "alert-banner@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "690d67d0-dd6b-47a8-81d4-9b365ff78a05"
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214613Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>أضف نصًا توضيحيًا يشرح التنبيه.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: تنبيه
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "0d3d38d6-f158-41dd-af2a-04a24fe80371"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: ar-SA
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151713Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>أضف نصًا توضيحيًا يشرح التنبيه.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: تنبيه
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "29b82698-7208-4968-84b3-e199ec696063"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151713Z
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Tilføj en uddybende tekst, der forklarer notifikationen.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Bemærk
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "153b972e-13aa-43b4-b88d-a09ea8d98276"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Fügen Sie einen erläuternden Text zur Meldung hinzu.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Hinweis
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "20dfbc7b-10e1-4f83-accc-0f2fb1e06931"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151713Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Fügen Sie einen erläuternden Text zur Meldung hinzu.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Hinweis
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "d62beab2-d5b9-4e89-b2bb-996308a4e68b"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151713Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214613Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Add supporting copy that explains the alert.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Heads up
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "1b34ec5e-9b11-406a-9688-57c1c5a74b65"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: bf340f9d-f68f-4d08-9384-2ed9b139a8af
      Hint: Link
      Value: |
        <link text="Learn more" linktype="external" url="/" />
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214613Z
- Language: es
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Añade un texto de apoyo que explique la alerta.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Atención
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "235a3a9f-6511-473e-b458-47e521d1db54"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: es-ES
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151713Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Añade un texto de apoyo que explique la alerta.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Atención
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "97360c52-a7f8-4f2d-8a3d-c0b92a57cada"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151713Z
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Ajoutez un texte explicatif pour l'alerte.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: À noter
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "2079e4cf-4795-451d-aec2-a641bc9e4583"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214614Z
- Language: fr-FR
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151712Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Ajoutez un texte explicatif pour l'alerte.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: À noter
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "a98e3ab5-c9b5-455c-baf8-504da01a504e"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151713Z
- Language: it
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>Aggiungi un testo di supporto che spieghi l'avviso.</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: Attenzione
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "93cde76b-78bf-4986-8942-eed0fedd6891"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: ja
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>アラートを説明する補足テキストを追加してください。</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: ご注意
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "7dee20ef-2c98-4f5b-9944-8ab0620b51a6"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: zh-CN
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>添加用于说明该提醒的辅助文案。</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: 温馨提示
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "7eba9a60-a464-4c46-a899-02b511f1ca31"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
- Language: zh-TW
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214614Z
    - ID: 27c6393c-c743-4318-bebc-a43b4cff7c9b
      Hint: Description
      Value: <p>新增用於說明該提醒的輔助文案。</p>
    - ID: 52752ae1-0d49-4d6d-bc72-487d3ceba080
      Hint: Title
      Value: 溫馨提示
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "01685c95-afc5-433c-8a93-1c8fc1f3a491"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214615Z
DB: master
