---
ID: "0ad6b7c9-b7a1-4fe3-b2e0-dde92beb63fb"
Parent: "4077c41f-a518-462c-8c6d-81e89f60fa18"
Template: "4077c41f-a518-462c-8c6d-81e89f60fa18"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/Component Folders/stories-rail Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{B0699975-C2C3-451C-93DB-1AF8929450D0}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9ad4d340-7fe8-40c6-b194-fe2de8fb4230"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T020858Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "693324da-bcce-4f5a-889a-960ed3d7dd7f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T020858Z
