---
ID: "8521e946-7ee1-490f-8431-cd3d7ab37235"
Parent: "af9803c5-f29d-4cc0-8270-436ecbfdd93e"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: "/sitecore/layout/Renderings/Project/starter-collection/starter/Components/heros-and-promos/product-details"
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: "product-details"
- ID: "069a8361-b1cd-437c-8c32-a3be78941446"
  Hint: Placeholders
  Value: |
    {9FC74D60-27D4-4245-9FFA-B87697F84540}
    {54C68E03-1B67-4296-8BF9-9C9A2A10CEB2}
    {57E7550F-955C-4EE2-9372-BB806248724D}
    {3DE0234B-3FD9-466C-91F0-34C097014DAE}
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/-/media/7cb408f1e87140e8b57dfd78fe451b08.ashx?thn=1&db=master&v=2"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: "{824578A4-80ED-4356-AE6B-6B9DEAE1CCF7}"
- ID: "7d8ae35f-9ed1-43b5-96a2-0a5f040d4e4e"
  Hint: Open Properties after Add
  Value: 0
- ID: "a3411ff6-c978-40aa-b059-a49b9ca2209b"
  Hint: Can select Page as a data source
  Value: 1
- ID: "a77e8568-1ab3-44f1-a664-b7c37ec7810d"
  Hint: Parameters Template
  Value: "{35F985CB-2BD2-45AC-A208-2C0EB16AE590}"
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "./Data/Product Details|/sitecore/content/starter-collection/starter/Data/Product Details"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "450d6539-b4fc-4881-9b26-a76caeb9678c"
- ID: "e829c217-5e94-4306-9c48-2634b094fdc2"
  Hint: OtherProperties
  Value: IsRenderingsWithDynamicPlaceholders=true&UsePlaceholderDatasourceContext=true
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "071e5985-0e53-42ee-a24c-7ec77d70c2b5"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Details
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260903T224404Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fe36d518-ed2a-457b-bf90-e44b1e8ccab2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260908T231957Z
