---
ID: "9db87691-70b9-404c-a1e1-f979f232fbad"
Parent: "5da9c3e2-2d85-4b94-9681-39def854af29"
Template: "5da9c3e2-2d85-4b94-9681-39def854af29"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/layout/Component Folders/section-wrapper Data Folder/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{06E6AD1A-5CC5-4DAB-88FB-F6D323B21791}"
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "section-wrapper@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "484d1879-2cac-4299-b7aa-8021cec0818d"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T020600Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "45de9841-5e7a-40d3-ae84-ab90ddd23f68"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T020601Z
