---
ID: "de0707c0-2f48-4220-91d5-d7b642f3c621"
Parent: "bb216ca3-01c0-4fa3-bc7b-e3324f5da864"
Template: "bb216ca3-01c0-4fa3-bc7b-e3324f5da864"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/search/Presentation Parameters/search-bar Parameters/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "adc74bed-5106-4295-b041-a6b183ad026c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T020500Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d88d140a-4f97-4ac9-b1f6-5e1392379885"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T020500Z
    - ID: "e1a4f17b-b360-463f-b1cd-57c7e3cfb4b2"
      Hint: Variant
      Value: "{FA91DEA2-6048-4DAB-8FFA-A929F92F9A4E}"
