---
ID: "03267bd7-a745-4ad5-9e76-cefc6c83bc28"
Parent: "1ae3c3ce-c59a-494e-8bae-c50cc7c8b27e"
Template: "1ae3c3ce-c59a-494e-8bae-c50cc7c8b27e"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/page-details/product-details/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "product-details@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "33fc1abd-07a1-4be8-ad06-6f26113f552c"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260908T182025Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dc3b2d0b-8622-4bd2-8742-1021e2662430"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260908T182025Z
