---
ID: "118170de-530a-4c17-a0cb-883f29374224"
Parent: "9487e5e8-4af7-442b-8934-f584ea53a31d"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/starter-collection/starter/Presentation/Headless Variants/case-study-details/Default"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "case-study-details@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "7f4179b8-98b4-48e8-ba87-ccda9028b5a7"
Languages:
- Language: en
  Fields:
  - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
    Hint: __Unversioned revision
    Value: "bfec6ce9-9872-481b-b851-da1f186fc3cb"
  - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
    Hint: __Display name
    Value: Default
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260904T154251Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "51e689ba-f9b7-4bd2-bca2-45225004a8ed"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260904T154251Z
DB: master
