---
ID: "43f64e47-d5df-4db1-aac9-195a333f0867"
Parent: "c31798eb-ee42-4514-b44a-4da70b756bbf"
Template: "c31798eb-ee42-4514-b44a-4da70b756bbf"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/cards-and-lists/Presentation Parameters/video Parameters/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ebf96f7e-365d-4186-8094-53dad672928d"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T021129Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "64a00a71-2c9d-4bb7-9d7f-2ba021e18fa4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T021129Z
    - ID: "f23d9ebd-d112-4c24-bb2c-f051fd62d58d"
      Hint: MediaControls
      Value: 1
    - ID: "fd6940eb-a2e9-4571-92a2-153164cca142"
      Hint: MediaPreload
      Value: "{34044D89-30F5-4052-B3CB-AE006798E541}"
