---
ID: "4af1f599-5f52-4ceb-8eea-2d1679cdf20a"
Parent: "43e1812c-ecbc-41f3-9239-cdf1053813a2"
Template: "43e1812c-ecbc-41f3-9239-cdf1053813a2"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/forms/form-address-field/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "form-address-field@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "cead1887-6cf5-4ce6-b91e-64c6dd741627"
Languages:
- Language: "ar"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215757Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: العنوان البريدي
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "70a5aa64-7ebd-49f0-bf6d-c16d7eb5ef33"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "ar-SA"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151801Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: العنوان البريدي
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6d7d2655-2d55-46eb-91c8-53b10b340b39"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151802Z
- Language: "da"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215757Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Postadresse
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "79ffffc2-0b2d-4432-9f68-f1b614101297"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "de"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Postanschrift
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3dde42b1-10ad-47d0-bfad-020118671e02"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151802Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Postanschrift
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a9c1dd48-d3f4-4ad4-afa8-2e481dd12010"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151802Z
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "171c2363-a823-475b-80e7-0934c4eaf00a"
      Hint: Name
      Value: address
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215757Z
    - ID: "5159674e-0e8c-4c66-89e7-543ede1566ff"
      Hint: DefaultCountry
      Value: US
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Mailing address
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "52cd9e45-f6b1-4e09-94f0-cfafa59e569f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215757Z
    - ID: "e72c19a2-ff29-4b07-9879-ca6c4f58ffdb"
      Hint: Required
      Value: 1
- Language: "es"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Dirección postal
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ab03ea31-de04-45e8-859a-118ec78a3aff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151802Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Dirección postal
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8fc54d1c-751e-4cbc-a0a8-95fccb8a0ab7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151802Z
- Language: "fr"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Adresse postale
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bccc3f95-1c78-4226-adae-531e69c9d491"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260909T151802Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Adresse postale
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "74ee41d0-2e9a-4cd2-9062-9b2e5268cc1a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260909T151802Z
- Language: "it"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: Indirizzo postale
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "20eb44c4-3c16-4711-b1d3-9aa931f35fc9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "ja"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: 郵送先住所
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53bd343c-7ef3-4b4a-b383-22b62c5da20b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "zh-CN"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: 邮寄地址
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cdee6e0f-4f3e-4520-b39c-d0f477c28bac"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215758Z
- Language: "zh-TW"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215758Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7d7aa13a-1efa-4e6e-94f2-a1284848529d"
      Hint: Legend
      Value: 郵寄地址
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57783155-38a3-46d1-b611-f4507dd4def5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215759Z
