---
ID: "3a6fa270-45b4-43f9-bfaa-a9114ef2be6f"
Parent: "7aa732ca-4cbb-4364-a252-ec3135cd3abf"
Template: "7aa732ca-4cbb-4364-a252-ec3135cd3abf"
Path: "/sitecore/templates/Project/starter-collection/Pages/Destination/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{7AA732CA-4CBB-4364-A252-EC3135CD3ABF}"
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: destination@1
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "232fd430-c34f-43e5-a049-51647c024971"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}"></d>
    </r>
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260903T224304Z
    - ID: "2ac1f449-5a7c-4b5e-8199-d34566311ebf"
      Hint: ChangeFrequency
      Value: monthly
    - ID: "4945f5b5-90d8-4e59-8906-c898a028b3fc"
      Hint: SitemapPriority
      Value: 0.6
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5d4db039-6ecd-47c9-854a-c9b78a2551c9"
      Hint: TwitterCard
      Value: summary_large_image
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "7a5a5e78-6f2b-4447-80ae-e2b28ed0d8ef"
      Hint: IncludeInSitemap
      Value: 1
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5a534ebd-5973-4037-9e91-135c4c0376ea"
    - ID: "a5de7317-4c1f-498b-97ea-0697734299ad"
      Hint: OgType
      Value: website
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260903T224305Z
