---
ID: "9a2d934f-356e-4ae9-8b2f-0a9d74430ab9"
Parent: "3cee17a4-e0e2-4ed3-a78a-de1c9cb75570"
Template: "3cee17a4-e0e2-4ed3-a78a-de1c9cb75570"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/page-details/Component Folders/offer-details Data Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9EFA9304-A6CB-4F48-9046-0CC8FC082299}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "cf4add9d-7f3a-44ee-93fd-1a7ffca667b0"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260908T181906Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "faf90abe-c125-4d74-9140-2452a6458230"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260908T181906Z
