---
ID: "eb725076-7077-43e7-948c-aa0b86256d16"
Parent: "0e2809be-d04e-4207-a2fa-1590330787ca"
Template: "0e2809be-d04e-4207-a2fa-1590330787ca"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/cards-and-lists/media-wall/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  Hint: __Masters
  Value: "{493D6860-924E-45BB-8A1B-E66BF1C2987C}"
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "media-wall@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "98c27f7e-79f5-454e-b218-53ce89844211"
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221033Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: جدار الوسائط
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "642eb75e-54d3-4413-9ab0-9598b7ef0ab0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: ar-SA
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151859Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: جدار الوسائط
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "dcac0860-700b-4150-9180-06b92059a36d"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151859Z
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221033Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Medievæg
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "98572f69-41d2-4842-841f-a1a59fcf9f0d"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221033Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Medienwand
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "98105146-bc5f-4da7-b1bc-f88b5af372f8"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151859Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Medienwand
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "fee1fe57-8875-4cd0-b772-bde38dd1581a"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151900Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221033Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Media wall
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "d3989a40-e907-4b0c-a04d-bb5e415ca753"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260816T232532Z
- Language: es
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221033Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Muro multimedia
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "2bdc0730-c572-4e53-a869-c1bd1a069a03"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: es-ES
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151859Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Muro multimedia
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "f0331658-9c3d-4053-a941-2c1d71524e21"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151900Z
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221033Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Mur multimédia
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "9a798410-bd66-448e-b257-d8763ce21c81"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: fr-FR
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151859Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Mur multimédia
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "ada3c048-16e1-4355-90af-86e15fef93f0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151900Z
- Language: it
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221034Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: Parete multimediale
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "aaa72c2d-c50c-4e72-a1af-632cb9a6bb80"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: ja
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221034Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: メディアウォール
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "f0feeecb-1320-4114-80b4-6258a5b36bc9"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: zh-CN
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221034Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: 媒体墙
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "1c57cd25-89f6-47bd-85bf-5e71b30253aa"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
- Language: zh-TW
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221034Z
    - ID: 46682109-7874-4635-8778-8e2e14c668f5
      Hint: Title
      Value: 媒體牆
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "3e8c72bf-26a9-4512-9445-d3390b438282"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260815T163853Z
DB: master
