---
ID: "f5d1493a-100c-4ff4-81b5-a2731d563d86"
Parent: "6efcea24-241b-4297-b65b-e09527fc2f7c"
Template: "6efcea24-241b-4297-b65b-e09527fc2f7c"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/search/travel-search/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "travel-search@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "162f0ea4-7ff6-424e-bf38-d06ecb47bafd"
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "a25a6c78-3aa0-484c-94fc-a7971c100ea8"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: بحث
- Language: ar-SA
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T152041Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "28bbf8bc-b0f6-4118-8681-ba8473f572d4"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T152041Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: بحث
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "1b0eaea2-3fb3-4d6b-b51a-bba8efbff414"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Søg
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "cae86a12-6c66-4670-9efd-d147aceb5e24"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Suchen
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T152041Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "8b9dc5c9-7d63-47b4-85fa-8133f4f649c4"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T152041Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Suchen
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "04ced308-ca79-48a0-8c89-bd5028dbfaa0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223057Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Search
- Language: es
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "1b1d6105-6df3-4145-aa47-e51385c3634f"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Buscar
- Language: es-ES
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T152041Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "f9c46a6f-9f0f-4dc1-9f1c-4f407bce5ee3"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T152041Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Buscar
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "9be514d3-e692-434b-a41c-50d8f2e0d397"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Rechercher
- Language: fr-FR
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T152041Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "036f7146-62e8-4a2a-b7e8-344c12b5a784"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T152041Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Rechercher
- Language: it
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223057Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "b159b86b-b08d-43a3-8cbd-55d63292d047"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: Cerca
- Language: ja
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223058Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "ba684f3c-ba57-4338-aa43-20b44f709fef"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: 検索
- Language: zh-CN
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223058Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "6f1b533d-2ff4-4e4a-8f3d-5ed396b3b5f0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: 搜索
- Language: zh-TW
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T223058Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "377c96f0-cdd3-4587-a4ec-bcc158d8c452"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T223058Z
    - ID: fbc83376-c087-4afa-b16c-bcd58ac75bcf
      Hint: SearchLabel
      Value: 搜尋
DB: master
