---
ID: "baa3cf37-6057-4ff1-afef-e243abcad0e4"
Parent: "dc56b2e3-a426-47b6-9413-411756fb015c"
Template: "dc56b2e3-a426-47b6-9413-411756fb015c"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/ui/Component Folders/avatar-block Site Shared UI - Authors Data Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{456CD052-D43F-4EE3-B4AC-549210BBB8C4}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "48d8a5b4-762e-49ae-8d3d-e54c1ad231c1"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T013837Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b7a0e735-1068-41f3-8589-e0a9ee7594ca"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T013837Z
