---
ID: "e71d9b87-1afc-4a74-8659-f3916010add4"
Parent: "df0eac7e-1fe2-46b7-a6a4-4cdbac962b41"
Template: "df0eac7e-1fe2-46b7-a6a4-4cdbac962b41"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/cards-and-lists/person-carousel/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  Hint: __Masters
  Value: "{9F5C7447-DFE9-41FD-9CC5-24678EFBE3B5}"
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "person-carousel@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "d7fd342a-bdba-491f-ba0b-2253199aa15a"
Languages:
- Language: ar
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: تعرّف على الفريق
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221423Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "c98173aa-69f1-47de-8c3c-63ab6a06f9d3"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: ar-SA
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: تعرّف على الفريق
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151917Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "b64fbd17-57aa-4316-a606-a6d018c22584"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151917Z
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Mød teamet
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "60955ec2-540c-49db-a4a3-825248e844a0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: de
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Das Team
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "243cdff4-a92b-4bd0-8eb2-73de15af99bc"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: de-DE
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Das Team
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151917Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "4dcf4b46-87d5-4189-b961-898eb9083415"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151918Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Meet the team
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221423Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "79c9d6c3-f77a-4fc7-839a-862f79775d1a"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221425Z
- Language: es
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Conoce al equipo
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "b07772ac-81c2-4fc2-bdcc-d34c0f1dcda4"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: es-ES
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Conoce al equipo
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151917Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "b6d38d41-1f95-4ac3-b023-08b2c3aa8031"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151918Z
- Language: fr
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Découvrez l'équipe
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "51d09fd5-3250-4c18-8a91-d02dd4b39db4"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: fr-FR
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Découvrez l'équipe
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260909T151917Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "703dbbc4-839c-48a0-b0ef-f33eea0314ce"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260909T151918Z
- Language: it
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: Il nostro team
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "21cd8cec-6d09-4c77-8e83-fc5da347df0c"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: ja
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: チーム紹介
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "41ae9c4b-5ef6-419c-88f8-86594bc19bf3"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: zh-CN
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: 团队介绍
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "cda7b42c-e58d-4432-ab27-5cc3acc7d9a1"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221424Z
- Language: zh-TW
  Versions:
  - Version: 1
    Fields:
    - ID: 1cf56b53-caa7-4c0a-b678-75f41be321dc
      Hint: Title
      Value: 團隊介紹
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T221424Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "2ea97656-f4b3-41af-8351-16b55ab2a299"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T221425Z
DB: master
