---
ID: "4b518c3c-10ea-46f9-b892-f96890905cd6"
Parent: "ed1027e2-a8c9-43fd-9467-9674a6f69c34"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/starter-collection/coreworks/Presentation/Headless Variants/accordion-item-rendering/Default"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "accordion-item-rendering@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "d9016bee-d7a3-4bcc-8b8f-67fb743c9590"
Languages:
- Language: en
  Fields:
  - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
    Hint: __Unversioned revision
    Value: "6eda9f0b-f6a8-4fe2-b9ea-afdaa00d2671"
  - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
    Hint: __Display name
    Value: Default
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T214450Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "af2a4725-c7d6-4c2b-b431-f2770ddc8d4a"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T214450Z
DB: master
