---
ID: "4062a256-3ab1-4968-a30c-f72bf9c33e21"
Parent: "7cb0c9ee-39e4-492f-b406-6539ce072d29"
Template: "7dae6839-465b-4364-a4e6-658ff5f1dbbd"
Path: "/sitecore/content/starter-collection/prospera/Presentation/Enumerations/Components/Carousel/CarouselButtonStyle/default"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "carousel-button-style@1"
- ID: 85ade29a-4684-4471-8a2d-a0937f1e85fd
  Hint: Value
  Value: default
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "0a900089-aeca-428d-ab1d-6dcd2443cae3"
Languages:
- Language: en
  Fields:
  - ID: 30e85e5d-e00a-4864-b358-7624d511deb4
    Hint: __Unversioned revision
    Value: "1812c7d0-6aad-4036-bbaa-aa5e48b98bd9"
  - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
    Hint: __Display name
    Value: Default
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260813T215141Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "97f9cf6d-d04c-4a00-937f-f1435298e2b0"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260813T215141Z
DB: master
