---
ID: "5367c9d3-5413-4e03-9a2c-c413321a2df0"
Parent: "d35f680c-3dfd-456e-b2cf-478e42249714"
Template: "d35f680c-3dfd-456e-b2cf-478e42249714"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/heros-and-promos/Component Folders/location-details Data Folder/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  Hint: __Masters
  Value: "{DFBDA919-0B2A-4374-8872-0D76C669E85D}"
- ID: 256ef004-c9b2-4087-a19d-d2649dc52f33
  Hint: Scai Handle
  Value: "location-details@1"
- ID: dbbbeca1-21c7-4906-9dd2-493c1efa59a2
  Hint: __Shared revision
  Value: "3fff99a4-2563-4b0c-8eb7-a556e0fff06c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260904T161552Z
    - ID: 52807595-0f8f-4b20-8d2a-cb71d28c6103
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: 8cdc337e-a112-42fb-bbb4-4143751e123f
      Hint: __Revision
      Value: "61d8527b-ed68-4f1a-b045-b7fae19c93fb"
    - ID: badd9cf9-53e0-4d0c-bcc0-2d784c282f6a
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: d9cf14b1-fa16-4ba6-9288-e8a174d4d522
      Hint: __Updated
      Value: 20260904T161552Z
DB: master
