---
ID: "37b7cfa9-6b9a-4dd6-a9af-55a8890f5d38"
Parent: "a7e1d23f-44c3-48b1-a74b-f17ecea52875"
Template: "a7e1d23f-44c3-48b1-a74b-f17ecea52875"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/search/travel-search/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "travel-search@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a9559632-0a35-4abf-927f-da6381a91eea"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T021034Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "194da29e-6d6b-4fef-a1dd-f3364c30b710"
    - ID: "aa24e0b5-2a2a-41cd-ba82-6474a7b80c37"
      Hint: SearchLabel
      Value: Search
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T021034Z
