"use client";

import {
  faArchive,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowsRotate,
  faArrowsUpDown,
  faArrowUp,
  faBagShopping,
  faBars,
  faBell,
  faBolt,
  faBookmark,
  faBox,
  faCalendar,
  faCalendarDays,
  faCamera,
  faChartBar,
  faChartLine,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCircleQuestion,
  faClipboard,
  faClock,
  faCloud,
  faCreditCard,
  faDownload,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFile,
  faFilter,
  faFlag,
  faFolder,
  faGear,
  faGift,
  faGlobe,
  faGrip,
  faHeart,
  faHouse,
  faImage,
  faKey,
  faLink,
  faList,
  faLocationDot,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMap,
  faMinus,
  faMoon,
  faPause,
  faPenToSquare,
  faPhone,
  faPlay,
  faPlus,
  faRocket,
  faSave,
  faShare,
  faShield,
  faShoppingCart,
  faStar,
  faStop,
  faSun,
  faTag,
  faThumbsDown,
  faThumbsUp,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUser,
  faUserMinus,
  faUserPlus,
  faUsers,
  faVideo,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  FontAwesomeIcon,
  type FontAwesomeIconProps,
} from "@fortawesome/react-fontawesome";

import type { LibraryIconComponent } from "./types";

const fontAwesome = (
  icon: Parameters<typeof FontAwesomeIcon>[0]["icon"],
): LibraryIconComponent => {
  const FontAwesomeWrappedIcon: LibraryIconComponent = ({ style, ...rest }) => (
    <FontAwesomeIcon
      icon={icon}
      {...(rest as Omit<FontAwesomeIconProps, "icon" | "ref">)}
      style={style as FontAwesomeIconProps["style"]}
    />
  );
  FontAwesomeWrappedIcon.displayName = "FontAwesomeWrappedIcon";
  return FontAwesomeWrappedIcon;
};

export const outlineIcons: Record<string, LibraryIconComponent> = {
  activity: fontAwesome(faChartLine),
  x: fontAwesome(faXmark),
  "arrow-left": fontAwesome(faArrowLeft),
  "arrow-right": fontAwesome(faArrowRight),
  "arrow-up": fontAwesome(faArrowUp),
  "arrow-down": fontAwesome(faArrowDown),
  bookmark: fontAwesome(faBookmark),
  "calendar-days": fontAwesome(faCalendarDays),
  camera: fontAwesome(faCamera),
  "chart-bar": fontAwesome(faChartBar),
  "chart-pie": fontAwesome(faChartPie),
  "chevron-left": fontAwesome(faChevronLeft),
  "chevron-right": fontAwesome(faChevronRight),
  "chevron-up": fontAwesome(faChevronUp),
  "chevron-down": fontAwesome(faChevronDown),
  "chevrons-up-down": fontAwesome(faArrowsUpDown),
  clipboard: fontAwesome(faClipboard),
  cloud: fontAwesome(faCloud),
  home: fontAwesome(faHouse),
  "credit-card": fontAwesome(faCreditCard),
  search: fontAwesome(faMagnifyingGlass),
  user: fontAwesome(faUser),
  users: fontAwesome(faUsers),
  "user-plus": fontAwesome(faUserPlus),
  "user-minus": fontAwesome(faUserMinus),
  settings: fontAwesome(faGear),
  bell: fontAwesome(faBell),
  mail: fontAwesome(faEnvelope),
  calendar: fontAwesome(faCalendar),
  clock: fontAwesome(faClock),
  check: fontAwesome(faCheck),
  plus: fontAwesome(faPlus),
  minus: fontAwesome(faMinus),
  menu: fontAwesome(faBars),
  map: fontAwesome(faMap),
  info: fontAwesome(faCircleInfo),
  help: fontAwesome(faCircleQuestion),
  alert: fontAwesome(faCircleExclamation),
  warning: fontAwesome(faTriangleExclamation),
  star: fontAwesome(faStar),
  heart: fontAwesome(faHeart),
  lock: fontAwesome(faLock),
  unlock: fontAwesome(faLockOpen),
  eye: fontAwesome(faEye),
  "eye-off": fontAwesome(faEyeSlash),
  trash: fontAwesome(faTrash),
  edit: fontAwesome(faPenToSquare),
  download: fontAwesome(faDownload),
  upload: fontAwesome(faUpload),
  share: fontAwesome(faShare),
  link: fontAwesome(faLink),
  filter: fontAwesome(faFilter),
  folder: fontAwesome(faFolder),
  file: fontAwesome(faFile),
  flag: fontAwesome(faFlag),
  gift: fontAwesome(faGift),
  globe: fontAwesome(faGlobe),
  grid: fontAwesome(faGrip),
  image: fontAwesome(faImage),
  archive: fontAwesome(faArchive),
  key: fontAwesome(faKey),
  lightning: fontAwesome(faBolt),
  list: fontAwesome(faList),
  "map-pin": fontAwesome(faLocationDot),
  moon: fontAwesome(faMoon),
  package: fontAwesome(faBox),
  pause: fontAwesome(faPause),
  phone: fontAwesome(faPhone),
  play: fontAwesome(faPlay),
  refresh: fontAwesome(faArrowsRotate),
  rocket: fontAwesome(faRocket),
  save: fontAwesome(faSave),
  shield: fontAwesome(faShield),
  "shopping-cart": fontAwesome(faShoppingCart),
  "shopping-bag": fontAwesome(faBagShopping),
  stop: fontAwesome(faStop),
  sun: fontAwesome(faSun),
  tag: fontAwesome(faTag),
  "thumbs-down": fontAwesome(faThumbsDown),
  "thumbs-up": fontAwesome(faThumbsUp),
  video: fontAwesome(faVideo),
};
