"use client";

import {
  PresentationChartLineIcon as HeroActivity,
  ExclamationCircleIcon as HeroAlert,
  ArchiveBoxIcon as HeroArchive,
  ArrowDownIcon as HeroArrowDown,
  ArrowLeftIcon as HeroArrowLeft,
  ArrowRightIcon as HeroArrowRight,
  ArrowUpIcon as HeroArrowUp,
  BellIcon as HeroBell,
  BookmarkIcon as HeroBookmark,
  CalendarIcon as HeroCalendar,
  CalendarDaysIcon as HeroCalendarDays,
  CameraIcon as HeroCamera,
  ChartBarIcon as HeroChartBar,
  ChartPieIcon as HeroChartPie,
  CheckIcon as HeroCheck,
  ChevronDownIcon as HeroChevronDown,
  ChevronLeftIcon as HeroChevronLeft,
  ChevronRightIcon as HeroChevronRight,
  ChevronUpDownIcon as HeroChevronsUpDown,
  ChevronUpIcon as HeroChevronUp,
  ClipboardDocumentIcon as HeroClipboard,
  ClockIcon as HeroClock,
  CloudIcon as HeroCloud,
  CreditCardIcon as HeroCreditCard,
  DocumentTextIcon as HeroDocumentText,
  ArrowDownTrayIcon as HeroDownload,
  PencilSquareIcon as HeroEdit,
  EyeIcon as HeroEye,
  EyeSlashIcon as HeroEyeOff,
  DocumentIcon as HeroFile,
  FunnelIcon as HeroFilter,
  FlagIcon as HeroFlag,
  FolderIcon as HeroFolder,
  GiftIcon as HeroGift,
  GlobeAltIcon as HeroGlobe,
  Squares2X2Icon as HeroGrid,
  HeartIcon as HeroHeart,
  QuestionMarkCircleIcon as HeroHelp,
  HomeIcon as HeroHome,
  PhotoIcon as HeroImage,
  InformationCircleIcon as HeroInfo,
  KeyIcon as HeroKey,
  BoltIcon as HeroLightning,
  LinkIcon as HeroLink,
  ListBulletIcon as HeroList,
  LockClosedIcon as HeroLock,
  EnvelopeIcon as HeroMail,
  MapIcon as HeroMap,
  MapPinIcon as HeroMapPin,
  Bars3Icon as HeroMenu,
  MinusIcon as HeroMinus,
  MoonIcon as HeroMoon,
  CubeIcon as HeroPackage,
  PauseIcon as HeroPause,
  PhoneIcon as HeroPhone,
  PlayIcon as HeroPlay,
  PlusIcon as HeroPlus,
  ArrowPathIcon as HeroRefresh,
  RocketLaunchIcon as HeroRocket,
  MagnifyingGlassIcon as HeroSearch,
  Cog6ToothIcon as HeroSettings,
  ShareIcon as HeroShare,
  ShieldCheckIcon as HeroShield,
  ShoppingBagIcon as HeroShoppingBag,
  ShoppingCartIcon as HeroShoppingCart,
  StarIcon as HeroStar,
  StopIcon as HeroStop,
  SunIcon as HeroSun,
  TagIcon as HeroTag,
  HandThumbDownIcon as HeroThumbsDown,
  HandThumbUpIcon as HeroThumbsUp,
  TrashIcon as HeroTrash,
  LockOpenIcon as HeroUnlock,
  ArrowUpTrayIcon as HeroUpload,
  UserIcon as HeroUser,
  UserMinusIcon as HeroUserMinus,
  UserPlusIcon as HeroUserPlus,
  UsersIcon as HeroUsers,
  VideoCameraIcon as HeroVideo,
  ExclamationTriangleIcon as HeroWarning,
  XMarkIcon as HeroX,
} from "@heroicons/react/24/outline";
import {
  PresentationChartLineIcon as HeroSolidActivity,
  ExclamationCircleIcon as HeroSolidAlert,
  ArchiveBoxIcon as HeroSolidArchive,
  ArrowDownIcon as HeroSolidArrowDown,
  ArrowLeftIcon as HeroSolidArrowLeft,
  ArrowRightIcon as HeroSolidArrowRight,
  ArrowUpIcon as HeroSolidArrowUp,
  BellIcon as HeroSolidBell,
  BookmarkIcon as HeroSolidBookmark,
  CalendarIcon as HeroSolidCalendar,
  CalendarDaysIcon as HeroSolidCalendarDays,
  CameraIcon as HeroSolidCamera,
  ChartBarIcon as HeroSolidChartBar,
  ChartPieIcon as HeroSolidChartPie,
  CheckIcon as HeroSolidCheck,
  ChevronDownIcon as HeroSolidChevronDown,
  ChevronLeftIcon as HeroSolidChevronLeft,
  ChevronRightIcon as HeroSolidChevronRight,
  ChevronUpDownIcon as HeroSolidChevronsUpDown,
  ChevronUpIcon as HeroSolidChevronUp,
  ClipboardDocumentIcon as HeroSolidClipboard,
  ClockIcon as HeroSolidClock,
  CloudIcon as HeroSolidCloud,
  CreditCardIcon as HeroSolidCreditCard,
  DocumentTextIcon as HeroSolidDocumentText,
  ArrowDownTrayIcon as HeroSolidDownload,
  PencilSquareIcon as HeroSolidEdit,
  EyeIcon as HeroSolidEye,
  EyeSlashIcon as HeroSolidEyeOff,
  DocumentIcon as HeroSolidFile,
  FunnelIcon as HeroSolidFilter,
  FlagIcon as HeroSolidFlag,
  FolderIcon as HeroSolidFolder,
  GiftIcon as HeroSolidGift,
  GlobeAltIcon as HeroSolidGlobe,
  Squares2X2Icon as HeroSolidGrid,
  HeartIcon as HeroSolidHeart,
  QuestionMarkCircleIcon as HeroSolidHelp,
  HomeIcon as HeroSolidHome,
  PhotoIcon as HeroSolidImage,
  InformationCircleIcon as HeroSolidInfo,
  KeyIcon as HeroSolidKey,
  BoltIcon as HeroSolidLightning,
  LinkIcon as HeroSolidLink,
  ListBulletIcon as HeroSolidList,
  LockClosedIcon as HeroSolidLock,
  EnvelopeIcon as HeroSolidMail,
  MapIcon as HeroSolidMap,
  MapPinIcon as HeroSolidMapPin,
  Bars3Icon as HeroSolidMenu,
  MinusIcon as HeroSolidMinus,
  MoonIcon as HeroSolidMoon,
  CubeIcon as HeroSolidPackage,
  PauseIcon as HeroSolidPause,
  PhoneIcon as HeroSolidPhone,
  PlayIcon as HeroSolidPlay,
  PlusIcon as HeroSolidPlus,
  ArrowPathIcon as HeroSolidRefresh,
  RocketLaunchIcon as HeroSolidRocket,
  MagnifyingGlassIcon as HeroSolidSearch,
  Cog6ToothIcon as HeroSolidSettings,
  ShareIcon as HeroSolidShare,
  ShieldCheckIcon as HeroSolidShield,
  ShoppingBagIcon as HeroSolidShoppingBag,
  ShoppingCartIcon as HeroSolidShoppingCart,
  StarIcon as HeroSolidStar,
  StopIcon as HeroSolidStop,
  SunIcon as HeroSolidSun,
  TagIcon as HeroSolidTag,
  HandThumbDownIcon as HeroSolidThumbsDown,
  HandThumbUpIcon as HeroSolidThumbsUp,
  TrashIcon as HeroSolidTrash,
  LockOpenIcon as HeroSolidUnlock,
  ArrowUpTrayIcon as HeroSolidUpload,
  UserIcon as HeroSolidUser,
  UserMinusIcon as HeroSolidUserMinus,
  UserPlusIcon as HeroSolidUserPlus,
  UsersIcon as HeroSolidUsers,
  VideoCameraIcon as HeroSolidVideo,
  ExclamationTriangleIcon as HeroSolidWarning,
  XMarkIcon as HeroSolidX,
} from "@heroicons/react/24/solid";

import type { LibraryIconComponent } from "./types";

export const outlineIcons: Record<string, LibraryIconComponent> = {
  activity: HeroActivity,
  x: HeroX,
  "arrow-left": HeroArrowLeft,
  "arrow-right": HeroArrowRight,
  "arrow-up": HeroArrowUp,
  "arrow-down": HeroArrowDown,
  bookmark: HeroBookmark,
  "calendar-days": HeroCalendarDays,
  camera: HeroCamera,
  "chart-bar": HeroChartBar,
  "chart-pie": HeroChartPie,
  "chevron-left": HeroChevronLeft,
  "chevron-right": HeroChevronRight,
  "chevron-up": HeroChevronUp,
  "chevron-down": HeroChevronDown,
  "chevrons-up-down": HeroChevronsUpDown,
  clipboard: HeroClipboard,
  cloud: HeroCloud,
  home: HeroHome,
  "credit-card": HeroCreditCard,
  search: HeroSearch,
  user: HeroUser,
  users: HeroUsers,
  "user-plus": HeroUserPlus,
  "user-minus": HeroUserMinus,
  settings: HeroSettings,
  bell: HeroBell,
  mail: HeroMail,
  calendar: HeroCalendar,
  clock: HeroClock,
  check: HeroCheck,
  plus: HeroPlus,
  minus: HeroMinus,
  menu: HeroMenu,
  map: HeroMap,
  info: HeroInfo,
  help: HeroHelp,
  alert: HeroAlert,
  warning: HeroWarning,
  star: HeroStar,
  heart: HeroHeart,
  lock: HeroLock,
  unlock: HeroUnlock,
  eye: HeroEye,
  "eye-off": HeroEyeOff,
  trash: HeroTrash,
  edit: HeroEdit,
  download: HeroDownload,
  upload: HeroUpload,
  share: HeroShare,
  link: HeroLink,
  filter: HeroFilter,
  folder: HeroFolder,
  file: HeroFile,
  flag: HeroFlag,
  gift: HeroGift,
  globe: HeroGlobe,
  grid: HeroGrid,
  image: HeroImage,
  archive: HeroArchive,
  key: HeroKey,
  list: HeroList,
  moon: HeroMoon,
  "map-pin": HeroMapPin,
  package: HeroPackage,
  pause: HeroPause,
  phone: HeroPhone,
  play: HeroPlay,
  refresh: HeroRefresh,
  rocket: HeroRocket,
  save: HeroDocumentText,
  shield: HeroShield,
  "shopping-cart": HeroShoppingCart,
  "shopping-bag": HeroShoppingBag,
  stop: HeroStop,
  sun: HeroSun,
  tag: HeroTag,
  "thumbs-down": HeroThumbsDown,
  "thumbs-up": HeroThumbsUp,
  lightning: HeroLightning,
  video: HeroVideo,
};

export const solidIcons: Record<string, LibraryIconComponent> = {
  activity: HeroSolidActivity,
  x: HeroSolidX,
  "arrow-left": HeroSolidArrowLeft,
  "arrow-right": HeroSolidArrowRight,
  "arrow-up": HeroSolidArrowUp,
  "arrow-down": HeroSolidArrowDown,
  bookmark: HeroSolidBookmark,
  "calendar-days": HeroSolidCalendarDays,
  camera: HeroSolidCamera,
  "chart-bar": HeroSolidChartBar,
  "chart-pie": HeroSolidChartPie,
  "chevron-left": HeroSolidChevronLeft,
  "chevron-right": HeroSolidChevronRight,
  "chevron-up": HeroSolidChevronUp,
  "chevron-down": HeroSolidChevronDown,
  "chevrons-up-down": HeroSolidChevronsUpDown,
  clipboard: HeroSolidClipboard,
  cloud: HeroSolidCloud,
  home: HeroSolidHome,
  "credit-card": HeroSolidCreditCard,
  search: HeroSolidSearch,
  user: HeroSolidUser,
  users: HeroSolidUsers,
  "user-plus": HeroSolidUserPlus,
  "user-minus": HeroSolidUserMinus,
  settings: HeroSolidSettings,
  bell: HeroSolidBell,
  mail: HeroSolidMail,
  calendar: HeroSolidCalendar,
  clock: HeroSolidClock,
  check: HeroSolidCheck,
  plus: HeroSolidPlus,
  minus: HeroSolidMinus,
  menu: HeroSolidMenu,
  map: HeroSolidMap,
  info: HeroSolidInfo,
  help: HeroSolidHelp,
  alert: HeroSolidAlert,
  warning: HeroSolidWarning,
  star: HeroSolidStar,
  heart: HeroSolidHeart,
  lock: HeroSolidLock,
  unlock: HeroSolidUnlock,
  eye: HeroSolidEye,
  "eye-off": HeroSolidEyeOff,
  trash: HeroSolidTrash,
  edit: HeroSolidEdit,
  download: HeroSolidDownload,
  upload: HeroSolidUpload,
  share: HeroSolidShare,
  link: HeroSolidLink,
  filter: HeroSolidFilter,
  folder: HeroSolidFolder,
  file: HeroSolidFile,
  flag: HeroSolidFlag,
  gift: HeroSolidGift,
  globe: HeroSolidGlobe,
  grid: HeroSolidGrid,
  image: HeroSolidImage,
  archive: HeroSolidArchive,
  key: HeroSolidKey,
  list: HeroSolidList,
  moon: HeroSolidMoon,
  "map-pin": HeroSolidMapPin,
  package: HeroSolidPackage,
  pause: HeroSolidPause,
  phone: HeroSolidPhone,
  play: HeroSolidPlay,
  refresh: HeroSolidRefresh,
  rocket: HeroSolidRocket,
  save: HeroSolidDocumentText,
  shield: HeroSolidShield,
  "shopping-cart": HeroSolidShoppingCart,
  "shopping-bag": HeroSolidShoppingBag,
  stop: HeroSolidStop,
  sun: HeroSolidSun,
  tag: HeroSolidTag,
  "thumbs-down": HeroSolidThumbsDown,
  "thumbs-up": HeroSolidThumbsUp,
  lightning: HeroSolidLightning,
  video: HeroSolidVideo,
};
