---
ID: "dad4f902-61d6-4dbb-907a-873ca9771c0a"
Parent: "17e4a1f4-8358-4a0c-bbb7-efe69b09751c"
Template: "17e4a1f4-8358-4a0c-bbb7-efe69b09751c"
Path: "/sitecore/templates/Project/starter-collection/prospera/Components/forms/form-date-field/__Standard Values"
BranchID: "00000000-0000-0000-0000-000000000000"
SharedFields:
- ID: "256ef004-c9b2-4087-a19d-d2649dc52f33"
  Hint: Scai Handle
  Value: "form-date-field@1"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "2e5a4cc6-ea47-46bc-a450-4f0a80184dab"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260916T014619Z
    - ID: "487e9014-210b-47af-beae-cf221b98f013"
      Hint: Required
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "750cba59-0a60-4930-b392-86703fff07d8"
      Hint: Label
      Value: Date
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f648ee80-6205-4f2a-954c-7b9d8ccd9e28"
    - ID: "92b86f72-fe2d-4356-b990-7878b4a0ef1d"
      Hint: Name
      Value: date
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "cfa44418-2fa4-4cd8-92d7-90b47736b991"
      Hint: AutoComplete
      Value: 1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260916T014619Z
