---
ID: "eedcbe08-38bb-4407-b38d-1b7137555ee6"
Parent: "c5983974-fd79-4b87-84dc-0496923bcf42"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: "/sitecore/templates/Project/starter-collection/starter/Components/cards-and-lists/destination-card/Action"
BranchID: "00000000-0000-0000-0000-000000000000"
Languages:
- Language: "en"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260813T215440Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bf07380b-53d0-4405-817c-e4c6072def26"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260813T215440Z
